"""
Runtime domain models for UAF-81.64.
"""

from .definition import (
    RuntimeState,
    ServiceLifecycle,
    ServiceScope,
    HealthState,
    HealthCheckType,
    ShutdownReason,
    CrashType,
    RestartPolicy,
    WatchdogEscalation,
    CapabilityStatus,
    PreviousSessionStatus,
    StartupPolicy,
    ShutdownPolicy,
    RecoveryAction,
    RuntimeEnvironment,
    ServiceDefinition,
    ServiceInstance,
    HealthCheckResult,
    HealthReport,
    WatchdogEvent,
    CrashReport,
    RuntimeTelemetry,
    DiagnosticBundle,
    RuntimeDiagnosticReport,
)

__all__ = [
    "RuntimeState",
    "ServiceLifecycle",
    "ServiceScope",
    "HealthState",
    "HealthCheckType",
    "ShutdownReason",
    "CrashType",
    "RestartPolicy",
    "WatchdogEscalation",
    "CapabilityStatus",
    "PreviousSessionStatus",
    "StartupPolicy",
    "ShutdownPolicy",
    "RecoveryAction",
    "RuntimeEnvironment",
    "ServiceDefinition",
    "ServiceInstance",
    "HealthCheckResult",
    "HealthReport",
    "WatchdogEvent",
    "CrashReport",
    "RuntimeTelemetry",
    "DiagnosticBundle",
    "RuntimeDiagnosticReport",
]
