"""
UAF-81.84: Universal Runtime VFX, Particle Simulation, Effect Graph & Niagara Integration System.
"""

from .emitter import (
    EmitterConfig,
    Particle,
    SpawnConfig,
    VFXEmitter,
)
from .engine import (
    UniversalRuntimeVFXFabricator,
)
from .forces import (
    CollisionMode,
    CollisionResponse,
    CurlNoiseForce,
    DistanceConstraint,
    DragForce,
    ForceField,
    GravityForce,
    ParticleCollider,
    ParticleConstraint,
    PointForce,
    VelocityConstraint,
    VortexForce,
    WindForce,
)
from .graph import (
    SubEmitterBinding,
    VFXEvent,
    VFXEventBus,
    VFXGraph,
    VFXGraphNode,
)
from .integration import (
    GameplayVFXBridge,
    StreamingCellVFXTracker,
    VFXAttachment,
)
from .management import (
    VFXBudgetManager,
    VFXLODManager,
    VFXLODProfile,
    VFXPool,
)
from .math import (
    ColorGradient,
    ColorStop,
    FloatCurve,
    Keyframe,
    VectorCurve,
    clamp,
    lerp,
    remap,
    saturate,
    smoothstep,
    vec3_add,
    vec3_cross,
    vec3_dot,
    vec3_length,
    vec3_length_sq,
    vec3_lerp,
    vec3_normalize,
    vec3_scale,
    vec3_sub,
)
from .models import (
    DEFAULT_PARTICLE_SCHEMA,
    ColorRGBA,
    ConstraintType,
    DeterminismMode,
    NiagaraBridgeError,
    OverflowPolicy,
    ParticleAttribute,
    ParticleId,
    ParticleLifecycleState,
    ParticleSchema,
    RendererType,
    SimulationBackendType,
    SpawnMode,
    SpriteFacing,
    UnloadPolicy,
    Vec3,
    Vec4,
    VFXBudget,
    VFXBudgetExceededError,
    VFXError,
    VFXGraphCycleError,
    VFXLOD,
    VFXMaterialBinding,
    VFXMetrics,
    VFXNumericSecurityError,
    VFXParameter,
    VFXPriority,
    VFXSnapshot,
    VFXValidationError,
    ensure_finite_float,
    ensure_finite_vec3,
    ensure_finite_vec4,
)
from .networking import (
    NetworkVFXEvent,
    NetworkVFXManager,
)
from .niagara import (
    GoldenVFXFactory,
    NiagaraCompatibilityReport,
    NiagaraExporter,
    NiagaraImporter,
    VFXIRCompiler,
    VFXIREmitter,
    VFXIRModule,
    VFXIRRenderer,
    VFXIRSystem,
)
from .profiling import (
    EmitterProfileStats,
    VFXProfiler,
    VFXRecoveryManager,
    VFXValidationIssue,
    VFXValidator,
)
from .rendering import (
    BeamRenderer,
    DecalRenderer,
    MaterialBindingManager,
    MeshRenderer,
    RibbonRenderer,
    SpriteRenderer,
    TrailRenderer,
    VFXRenderer,
)
from .simulation import (
    CPUSimulationBackend,
    GPUSimulationBackend,
    ReferenceSimulationBackend,
    VFXSimulationBackend,
)

__all__ = [
    # Emitter
    "EmitterConfig",
    "Particle",
    "SpawnConfig",
    "VFXEmitter",
    # Engine
    "UniversalRuntimeVFXFabricator",
    # Forces
    "CollisionMode",
    "CollisionResponse",
    "CurlNoiseForce",
    "DistanceConstraint",
    "DragForce",
    "ForceField",
    "GravityForce",
    "ParticleCollider",
    "ParticleConstraint",
    "PointForce",
    "VelocityConstraint",
    "VortexForce",
    "WindForce",
    # Graph
    "SubEmitterBinding",
    "VFXEvent",
    "VFXEventBus",
    "VFXGraph",
    "VFXGraphNode",
    # Integration
    "GameplayVFXBridge",
    "StreamingCellVFXTracker",
    "VFXAttachment",
    # Management
    "VFXBudgetManager",
    "VFXLODManager",
    "VFXLODProfile",
    "VFXPool",
    # Math
    "ColorGradient",
    "ColorStop",
    "FloatCurve",
    "Keyframe",
    "VectorCurve",
    "clamp",
    "lerp",
    "remap",
    "saturate",
    "smoothstep",
    "vec3_add",
    "vec3_cross",
    "vec3_dot",
    "vec3_length",
    "vec3_length_sq",
    "vec3_lerp",
    "vec3_normalize",
    "vec3_scale",
    "vec3_sub",
    # Models
    "DEFAULT_PARTICLE_SCHEMA",
    "ColorRGBA",
    "ConstraintType",
    "DeterminismMode",
    "NiagaraBridgeError",
    "OverflowPolicy",
    "ParticleAttribute",
    "ParticleId",
    "ParticleLifecycleState",
    "ParticleSchema",
    "RendererType",
    "SimulationBackendType",
    "SpawnMode",
    "SpriteFacing",
    "UnloadPolicy",
    "Vec3",
    "Vec4",
    "VFXBudget",
    "VFXBudgetExceededError",
    "VFXError",
    "VFXGraphCycleError",
    "VFXLOD",
    "VFXMaterialBinding",
    "VFXMetrics",
    "VFXNumericSecurityError",
    "VFXParameter",
    "VFXPriority",
    "VFXSnapshot",
    "VFXValidationError",
    "ensure_finite_float",
    "ensure_finite_vec3",
    "ensure_finite_vec4",
    # Networking
    "NetworkVFXEvent",
    "NetworkVFXManager",
    # Niagara
    "GoldenVFXFactory",
    "NiagaraCompatibilityReport",
    "NiagaraExporter",
    "NiagaraImporter",
    "VFXIRCompiler",
    "VFXIREmitter",
    "VFXIRModule",
    "VFXIRRenderer",
    "VFXIRSystem",
    # Profiling
    "EmitterProfileStats",
    "VFXProfiler",
    "VFXRecoveryManager",
    "VFXValidationIssue",
    "VFXValidator",
    # Rendering
    "BeamRenderer",
    "DecalRenderer",
    "MaterialBindingManager",
    "MeshRenderer",
    "RibbonRenderer",
    "SpriteRenderer",
    "TrailRenderer",
    "VFXRenderer",
    # Simulation
    "CPUSimulationBackend",
    "GPUSimulationBackend",
    "ReferenceSimulationBackend",
    "VFXSimulationBackend",
]
