from enum import Enum

class DefectCategory(str, Enum):
    MISSING_COMPONENT = "MISSING_COMPONENT"
    EXTRA_COMPONENT = "EXTRA_COMPONENT"
    FORBIDDEN_COMPONENT = "FORBIDDEN_COMPONENT"
    WRONG_PROPORTION = "WRONG_PROPORTION"
    WRONG_POSITION = "WRONG_POSITION"
    WRONG_ORIENTATION = "WRONG_ORIENTATION"
    WRONG_SCALE = "WRONG_SCALE"
    WRONG_SILHOUETTE = "WRONG_SILHOUETTE"
    WRONG_MATERIAL = "WRONG_MATERIAL"
    WRONG_COLOR = "WRONG_COLOR"
    STYLE_MISMATCH = "STYLE_MISMATCH"
    EXCESSIVE_DETAIL = "EXCESSIVE_DETAIL"
    INSUFFICIENT_DETAIL = "INSUFFICIENT_DETAIL"
    SPATIAL_ERROR = "SPATIAL_ERROR"
    STRUCTURAL_IDENTITY_FAILURE = "STRUCTURAL_IDENTITY_FAILURE"
    TECHNICAL_ERROR = "TECHNICAL_ERROR"

class DefectSeverity(str, Enum):
    INFO = "INFO"
    MINOR = "MINOR"
    MODERATE = "MODERATE"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"

class CriticRecommendation(str, Enum):
    ACCEPT = "ACCEPT"
    MINOR_FIX = "MINOR_FIX"
    REFINE = "REFINE"
    REGENERATE_COMPONENT = "REGENERATE_COMPONENT"
    REGENERATE_ASSET = "REGENERATE_ASSET"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    REJECT = "REJECT"

class QualityProfile(str, Enum):
    PROTOTYPE = "PROTOTYPE"
    GAMEPLAY = "GAMEPLAY"
    PRODUCTION = "PRODUCTION"
    CINEMATIC = "CINEMATIC"

class CriticCameraView(str, Enum):
    FRONT = "FRONT"
    BACK = "BACK"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    TOP = "TOP"
    BOTTOM = "BOTTOM"
    ISOMETRIC = "ISOMETRIC"

class RequirementType(str, Enum):
    HARD = "HARD"
    SOFT = "SOFT"
    PREFERENCE = "PREFERENCE"
