from enum import Enum

class GeometricDefectCategory(str, Enum):
    INVALID_DATA = "INVALID_DATA"
    DEGENERATE_GEOMETRY = "DEGENERATE_GEOMETRY"
    DUPLICATE_GEOMETRY = "DUPLICATE_GEOMETRY"
    NON_MANIFOLD = "NON_MANIFOLD"
    OPEN_BOUNDARY = "OPEN_BOUNDARY"
    SELF_INTERSECTION = "SELF_INTERSECTION"
    NORMAL_ERROR = "NORMAL_ERROR"
    TRANSFORM_ERROR = "TRANSFORM_ERROR"
    SCALE_ERROR = "SCALE_ERROR"
    DIMENSION_ERROR = "DIMENSION_ERROR"
    TOPOLOGY_ERROR = "TOPOLOGY_ERROR"
    DENSITY_ERROR = "DENSITY_ERROR"
    UV_ERROR = "UV_ERROR"
    ATTRIBUTE_ERROR = "ATTRIBUTE_ERROR"
    MATERIAL_ASSIGNMENT_ERROR = "MATERIAL_ASSIGNMENT_ERROR"
    LOD_ERROR = "LOD_ERROR"
    COLLISION_ERROR = "COLLISION_ERROR"
    SEMANTIC_COMPONENT_ERROR = "SEMANTIC_COMPONENT_ERROR"

class DefectSeverity(str, Enum):
    INFO = "INFO"
    MINOR = "MINOR"
    MODERATE = "MODERATE"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"

class ValidationStatus(str, Enum):
    PASS = "PASS"
    PASS_WITH_WARNINGS = "PASS_WITH_WARNINGS"
    FAIL = "FAIL"
    BLOCKED = "BLOCKED"
    UNKNOWN = "UNKNOWN"

class ValidationProfileType(str, Enum):
    BASIC = "BASIC"
    STANDARD = "STANDARD"
    PRODUCTION = "PRODUCTION"
    UNREAL = "UNREAL"
    CUSTOM = "CUSTOM"

class CorrectionSafetyLevel(str, Enum):
    SAFE_AUTOMATION = "SAFE_AUTOMATION"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    HIGH_RISK = "HIGH_RISK"

class MeshWatertightMode(str, Enum):
    WATERTIGHT_REQUIRED = "WATERTIGHT_REQUIRED"
    OPEN_ALLOWED = "OPEN_ALLOWED"
    MIXED = "MIXED"

class NgonPolicy(str, Enum):
    ALLOWED = "ALLOWED"
    WARNING = "WARNING"
    FORBIDDEN = "FORBIDDEN"
