from enum import Enum

class AgentType(str, Enum):
    PLANNER = "PLANNER"
    SCENE_ANALYST = "SCENE_ANALYST"
    ASSET_BUILDER = "ASSET_BUILDER"
    BLENDER_OPERATOR = "BLENDER_OPERATOR"
    UNREAL_OPERATOR = "UNREAL_OPERATOR"
    VISUAL_QA = "VISUAL_QA"
    GAMEPLAY_QA = "GAMEPLAY_QA"
    TECHNICAL_QA = "TECHNICAL_QA"
    CORRECTION = "CORRECTION"
    OPTIMIZATION = "OPTIMIZATION"
    MEMORY = "MEMORY"
    INTEGRATION = "INTEGRATION"

class TaskState(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    ASSIGNED = "ASSIGNED"
    RUNNING = "RUNNING"
    WAITING_VALIDATION = "WAITING_VALIDATION"
    VALIDATING = "VALIDATING"
    PASSED = "PASSED"
    FAILED = "FAILED"
    CORRECTION_REQUIRED = "CORRECTION_REQUIRED"
    ROLLED_BACK = "ROLLED_BACK"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"

class LockType(str, Enum):
    READ = "READ"
    WRITE = "WRITE"
    EXCLUSIVE = "EXCLUSIVE"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class OrchestratorExecutionMode(str, Enum):
    INTERACTIVE = "INTERACTIVE"
    AUTOMATIC = "AUTOMATIC"
    SAFE = "SAFE"
    DRY_RUN = "DRY_RUN"
    BATCH = "BATCH"
    RECOVERY = "RECOVERY"

ExecutionMode = OrchestratorExecutionMode

class MessageType(str, Enum):
    REQUEST = "REQUEST"
    RESULT = "RESULT"
    ERROR = "ERROR"
    VALIDATION = "VALIDATION"
    PROGRESS = "PROGRESS"
    ESCALATION = "ESCALATION"
    HANDOFF = "HANDOFF"

class ScopeType(str, Enum):
    COMPONENT_SCOPE = "COMPONENT_SCOPE"
    ASSET_SCOPE = "ASSET_SCOPE"
    SCENE_SCOPE = "SCENE_SCOPE"
    LEVEL_SCOPE = "LEVEL_SCOPE"
    PROJECT_SCOPE = "PROJECT_SCOPE"
