from enum import Enum

class SessionState(str, Enum):
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    GENERATING = "GENERATING"
    EVALUATING = "EVALUATING"
    DIAGNOSING = "DIAGNOSING"
    CORRECTING = "CORRECTING"
    REGENERATING = "REGENERATING"
    COMPARING = "COMPARING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"

class CorrectionOp(str, Enum):
    SET = "SET"
    INCREASE = "INCREASE"
    DECREASE = "DECREASE"
    SCALE = "SCALE"
    OFFSET = "OFFSET"
    REPLACE = "REPLACE"
    REGENERATE_COMPONENT = "REGENERATE_COMPONENT"

class ScopeLevel(str, Enum):
    PARAMETER = "PARAMETER"
    FEATURE = "FEATURE"
    COMPONENT = "COMPONENT"
    SUBTREE = "SUBTREE"
    ASSET = "ASSET"

class TerminationReason(str, Enum):
    ACCEPTED = "ACCEPTED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    NO_IMPROVEMENT = "NO_IMPROVEMENT"
    USER_REQUIRED = "USER_REQUIRED"
    UNSATISFIABLE = "UNSATISFIABLE"
    SYSTEM_FAILURE = "SYSTEM_FAILURE"

class AdaptiveRiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ErrorCategory(str, Enum):
    GEOMETRY = "GEOMETRY"
    PROPORTION = "PROPORTION"
    SILHOUETTE = "SILHOUETTE"
    COMPONENT = "COMPONENT"
    POSITION = "POSITION"
    MATERIAL = "MATERIAL"
    STYLE = "STYLE"
    TOPOLOGY = "TOPOLOGY"
    PERFORMANCE = "PERFORMANCE"
    PLATFORM = "PLATFORM"
