"""
Universal Asset Factory (UAF) - Foundation (UAF-81.0)
Normative Foundation Core API
"""

# Context & Budget
from .core.context import ProjectContext, ExecutionContext, ResourceBudget

# Paths & Security
from .core.paths import UAFPathResolver, PathSecurityValidator, PathSecurityViolation

# Identity
from .core.identity import AssetType, AssetIdentity

# Specification
from .core.specification import AssetSpecification

# Hashing
from .core.hashing import CanonicalHasher

# Operations
from .core.operations import (
    Operation,
    OperationType,
    OperationStatus,
    OperationStateMachine,
    OperationResult,
    InvalidStateTransitionError,
)

# Artifacts
from .core.artifacts import (
    Artifact,
    ArtifactLocation,
    ArtifactManifest,
    StorageBackend,
)

# Diagnostics & Errors
from .core.diagnostics import (
    Diagnostic,
    DiagnosticSeverity,
    OperationMetrics,
    UAFError,
    SpecificationError,
    ConfigurationError,
    CapabilityError,
    GenerationError,
    ValidationError,
    ArtifactError,
    PersistenceError,
    PackagingError,
    PermissionError,
    ResourceError,
    ExternalProcessError,
    RecoveryError,
)

# Events
from .core.events import (
    UAFEvent,
    ProductionStarted,
    ProductionCompleted,
    OperationStarted,
    OperationCompleted,
    OperationFailed,
    ArtifactCreated,
    ArtifactValidated,
    ArtifactPublished,
    CheckpointCreated,
    CheckpointRestored,
)

# Configuration
from .core.configuration import UAFConfig, ConfigResolver, deep_merge

# State & Checkpoints
from .core.state import Checkpoint, CheckpointValidator, CheckpointValidationResult

# Contracts & Registries
from .contracts import BaseRegistry, ContractValidator, ValidationReport
from .capabilities import CapabilityDescription, CapabilityRegistry

# Testing & Mock
from .testing import MockGenerator

# Asset Intelligence (UAF-81.1)
from .intelligence import (
    ComplexityLevel,
    SemanticAsset,
    CharacterSemanticModel,
    ANATOMICAL_REGIONS,
    MaterialSemanticModel,
    MaterialLayer,
    TextureSetSemanticModel,
    TextureMapSpecification,
    ModularKitSemanticModel,
    ModularModule,
    ConnectionSocket,
    EnvironmentSemanticModel,
    WorldSemanticModel,
    LevelSemanticModel,
    AssetArchetype,
    ArchetypeRegistry,
    ParameterType,
    ParameterProvenance,
    ParameterMetadata,
    UnitNormalizer,
    ConstraintCategory,
    ConstraintType,
    AssetConstraint,
    ConstraintResolver,
    ResolutionTraceEntry,
    ConflictReport,
    DependencyGraph,
    CyclicDependencyError,
    StyleProfile,
    QualityProfile,
    TargetProfile,
    BlueprintNode,
    AssetBlueprint,
    ResolvedAssetSpecification,
    CapabilityGapReport,
    ResolutionPipeline,
    SpecificationMigrator,
)

# Capability & Generation Strategy Fabric (UAF-81.2)
from .strategy import (
    CapabilityType,
    CapabilityContract,
    ComprehensiveCapability,
    StrategyCategory,
    DeterminismMode,
    GenerationStrategy,
    StrategyRegistry,
    ExecutionBackend,
    ImplementationDescription,
    ImplementationRegistry,
    StrategyScore,
    CandidateEvaluation,
    StrategyDecisionTrace,
    StrategyEvaluator,
    GenerationPlanNode,
    GenerationPlan,
    GenerationPlanner,
    PlanningResult,
    Replanner,
    ReplanRequest,
    ReplanningResult,
)

# Procedural Geometry & Asset Construction Fabric (UAF-81.3)
from .geometry import (
    MultiResLevel,
    DetailRepresentation,
    DetailPolicy,
    Transform3D,
    AABB,
    BoundingSphere,
    MeshData,
    GeometryComponent,
    ModifierType,
    ProceduralModifier,
    ModifierStack,
    LandmarkSystem,
    STANDARD_LANDMARKS,
    AnatomyProfile,
    AttachmentSocket,
    ClothingLayerSystem,
    LayerClearanceReport,
    LAYER_HIERARCHY,
    TopologyProcessor,
    TopologyReport,
    UVGenerator,
    UVReport,
    LODGenerator,
    LODLevel,
    LODChain,
    CollisionGenerator,
    CollisionShape,
    CollisionType,
    GeometryValidator,
    GeometryValidationReport,
    ComponentizedCharacter,
    AssetBuildRecord,
    GeometryGenerator,
    GeometryGeneratorRegistry,
    ProceduralPrimitiveGenerator,
    ComponentizedHeroGenerator,
)

# Material, Texture & Surface Authoring Fabric (UAF-81.4)
from .surface import (
    PBRChannel,
    ColorSpace,
    ShaderModel,
    ChannelPacking,
    TextureDefinition,
    TextureSource,
    MaskType,
    MaskSource,
    BlendMode,
    SurfaceMask,
    MaterialLayer,
    MaterialDefinition,
    MaterialInstance,
    SemanticSurfaceRole,
    SurfaceDefinition,
    MaterialFamily,
    MaterialFamilyRegistry,
    BakeType,
    BakePlan,
    BakeResult,
    BakeEngine,
    SurfaceValidator,
    SurfaceValidationReport,
    SurfaceDependencyTracker,
    SurfaceSynthesizer,
    UnrealSurfacePackage,
    PhysicalClass,
    TexelDensityProfile,
    TextureSet,
    SurfacePackage,
    UVChannel,
    UVStrategy,
    UVOverlapPolicy,
    UVDefinition,
    TrimRegion,
    TrimSheetDefinition,
    TextureAtlasDefinition,
    UDIMDefinition,
    ProceduralPatternType,
    ProceduralTextureSynthesizer,
    SurfaceQualityScore,
    QualityTier,
    SurfaceQualityReport,
    ComprehensiveSurfaceValidator,
)


# Character Rigging, Skinning & Deformation Fabric (UAF-81.5)
from .rigging import (
    BoneRole,
    BoneDefinition,
    BindPoseType,
    SkeletonArchetype,
    CharacterSkeletonDefinition,
    SkeletonBuilder,
    IKType,
    IKConstraint,
    RigLayer,
    RigDefinition,
    WeightMethod,
    VertexWeights,
    SkinningDefinition,
    WeightNormalizer,
    WeightGenerator,
    DeformationZone,
    DeformationTestPose,
    CorrectiveBlendshape,
    DeformationScore,
    DeformationEvaluator,
    FacialRigDefinition,
    STANDARD_FACIAL_BLENDSHAPES,
    PhysicsBody,
    PhysicsConstraint,
    PhysicsAssetDefinition,
    RetargetProfile,
    UE5_MANNEQUIN_BONE_MAP,
    UnrealCharacterPackage,
    RigValidator,
    RigValidationReport,
)

# World Geometry, Modular Blockout & Procedural Level Fabric (UAF-81.6)
from .world import (
    WorldGrid,
    WorldSpecification,
    ConnectorType,
    ConnectorDefinition,
    ModuleCategory,
    ModuleDefinition,
    ModularKitDefinition,
    AssemblyNode,
    AssemblyGraph,
    RoomType,
    RoomDefinition,
    BuildingDefinition,
    CoverType,
    CoverDefinition,
    SpawnPoint,
    ObjectiveDefinition,
    NavigationMeshMetadata,
    DataLayer,
    WorldPartitionCell,
    HLODMetadata,
    WorldQualityScore,
    WorldValidationReport,
    WorldValidator,
    WorldPackage,
)

# Asset Assembly, LOD, Optimization & Unreal Runtime Readiness (UAF-81.8)
from .assembly import (
    PivotType,
    OriginPolicy,
    PivotDefinition,
    SocketType,
    RuntimeSocketDefinition,
    NanitePolicy,
    LODLevel,
    LODChain,
    AssetLifecycleState,
    AssetAssemblyGraph,
    RuntimeAssetQualityScore,
    RuntimeAssetQualityReport,
    RuntimeAssetValidator,
    TransactionalAssetBuilder,
    RuntimeAssetPackage,
)

# Animation, Rigging, Skinning & Character Runtime Fabric (UAF-81.9)
from .animation import (
    CharacterClassification,
    RigProfile,
    Keyframe,
    AnimationTrack,
    AnimationEventType,
    AnimationEvent,
    AnimationClip,
    AnimState,
    AnimTransition,
    AnimStateMachine,
    MontageDefinition,
    AnimationBlueprintContract,
    AnimationLODLevel,
    AnimationLODProfile,
    CharacterBuildState,
    AnimatedCharacterQualityScore,
    AnimatedCharacterQualityReport,
    AnimatedCharacterValidator,
    AnimatedCharacterPackage,
)

# Procedural Character Fabrication & High-Complexity Geometry (UAF-81.10)
from .fabrication import (
    ProportionProfileType,
    ParametricAnatomy,
    ProportionProfile,
    FormLevel,
    BodyComponent,
    SemanticBodyGraph,
    GarmentLayer,
    GarmentDefinition,
    TopologyStrategyType,
    FabricationQuality,
    ProceduralCharacterFabricator,
    FabricationQualityScore,
    FabricationValidationReport,
    FabricationValidator,
    FabricatedCharacterPackage,
)

# Procedural Texture, Material & Surface Authoring Fabric (UAF-81.11)
from .surface_authoring import (
    MaterialFamilyType,
    MaterialLayerBlendMode,
    SurfaceRegion,
    MaterialCompositionLayer,
    MaterialRegionGraph,
    SurfaceAuthoringEngine,
    SurfaceAuthoringQualityScore,
    SurfaceAuthoringValidationReport,
    SurfaceAuthoringValidator,
    AuthoredSurfacePackage,
)

# Procedural Modular Environment & World Fabrication (UAF-81.12)
from .environment import (
    SnapCategory,
    SnapPoint,
    GridProfile,
    ModularPiece,
    ModularGrammarRule,
    ModularGrammar,
    RoomType,
    RoomNode,
    BuildingFacilityGraph,
    ProceduralEnvironmentFabricator,
    EnvironmentQualityScore,
    EnvironmentValidationReport,
    EnvironmentValidator,
    EnvironmentPackage,
)

# Procedural Terrain, Biome & World Surface Fabrication (UAF-81.13)
from .world_surface import (
    TerrainMode,
    ErosionType,
    TerritoryModel,
    LandmarkType,
    NaturalLandmark,
    BiomeType,
    BiomeProfile,
    ProceduralWorldSurfaceFabricator,
    WorldSurfaceQualityScore,
    WorldSurfaceValidationReport,
    WorldSurfaceValidator,
    WorldSurfacePackage,
)

# Character Fabrication & Deformation System (UAF-81.14)
from .character_suite import (
    CharacterClassification,
    CharacterQualityTier,
    CharacterStyle,
    CharacterProfile,
    DeformationProfile,
    FaceProfile,
    CharacterLayer,
    CharacterFabricationPlatform,
    CharacterQualityScore,
    CharacterValidationReport,
    CharacterSuiteValidator,
    CharacterSuitePackage,
)

# Material, Texture & Surface Fabrication System (UAF-81.15)
from .surface_fabrication import (
    MaterialClassification,
    MaterialDomain,
    SurfaceWearType,
    SurfaceProfile,
    MaterialParameterType,
    MaterialGraphContract,
    SurfaceFabricationEngine,
    SurfaceFabricationQualityScore,
    SurfaceFabricationValidationReport,
    SurfaceFabricationValidator,
    SurfaceFabricationPackage,
)

# World, Terrain & Environment Fabrication System (UAF-81.16)
from .world_system import (
    WorldBounds,
    WorldDefinition,
    WaterBodyType,
    WaterBody,
    RoadNetwork,
    DistrictType,
    WorldDistrict,
    GameplayZone,
    WorldFabricationPlatform,
    WorldQualityScore,
    WorldValidationReport,
    WorldValidator,
    WorldFabricationPackage,
)

# Character Rigging, Skinning & Animation Fabrication System (UAF-81.17)
from .character_animation import (
    BoneRole,
    BoneNode,
    SkeletonHierarchy,
    IKSolverType,
    IKChain,
    SkinningMethod,
    SkinningWeightData,
    CharacterAnimationFabricator,
    CharacterAnimationQualityScore,
    CharacterAnimationValidationReport,
    CharacterAnimationValidator,
    CharacterAnimationPackage,
)

# Procedural Texture, Material & Surface Fabrication System (UAF-81.18)
from .surface_production import (
    SurfaceWeatheringState,
    MaterialPBRProfile,
    SurfaceDefinition,
    TexturePackingType,
    TextureChannelDefinition,
    SurfaceProductionFabricator,
    SurfaceProductionQualityScore,
    SurfaceProductionValidationReport,
    SurfaceProductionValidator,
    SurfaceProductionPackage,
)

# Procedural Environment, Modular Kit & World Fabrication System (UAF-81.19)
from .modular_world import (
    EnvironmentType,
    ModularKitProfile,
    EnvironmentDefinition,
    RoomPurpose,
    EnvironmentRoom,
    SpatialConnection,
    SpatialLayoutGraph,
    ModularWorldFabricationPlatform,
    ModularWorldQualityScore,
    ModularWorldValidationReport,
    ModularWorldValidator,
    ModularWorldPackage,
)

# Procedural Gameplay, Level Logic & Playable Scenario Fabrication System (UAF-81.20)
from .gameplay_scenario import (
    GameModeType,
    ScenarioLevelState,
    PlayableScenarioDefinition,
    GameplayNodeType,
    GameplayNode,
    GameplayEdge,
    GameplayGraph,
    ObjectiveType,
    ScenarioObjective,
    EncounterType,
    ScenarioEncounter,
    GameplayScenarioFabricator,
    GameplayQualityScore,
    GameplayValidationReport,
    GameplayScenarioValidator,
    PlayableScenarioPackage,
)

# Procedural Character, Creature & Deformation Fabrication System (UAF-81.21)
from .character_creature import (
    CharacterSpecies,
    AnatomicalLandmarks,
    CharacterDefinition21,
    BodyPartType,
    EquipmentLayerType,
    ModularEquipmentLayer,
    CharacterCreatureFabricationPlatform,
    CharacterCreatureQualityScore,
    CharacterCreatureValidationReport,
    CharacterCreatureValidator,
    CharacterCreaturePackage,
)

# Procedural Material, Texture & Surface Detail Fabrication System (UAF-81.22)
from .surface_detail import (
    PhysicalMaterialClass,
    SurfaceLayerType,
    SurfaceDetailDefinition,
    SurfaceDetailChannel,
    SurfaceDetailFabricationPlatform,
    SurfaceDetailQualityScore,
    SurfaceDetailValidationReport,
    SurfaceDetailValidator,
    SurfaceDetailPackage,
)

# Procedural Rigging, Animation & Motion Fabrication System (UAF-81.23)
from .animation_motion import (
    BoneRoleType,
    RigBoneNode,
    StandardSkeletonHierarchy,
    CharacterRigDefinition,
    MotionClipType,
    MotionClip,
    AnimationMotionFabricationPlatform,
    AnimationMotionQualityScore,
    AnimationMotionValidationReport,
    AnimationMotionValidator,
    AnimationMotionPackage,
)

# Procedural Environment, Modular Architecture & World Fabrication System (UAF-81.24)
from .world_architecture import (
    BiomeType24,
    WorldBoundaryBounds,
    WorldGridCell,
    WorldDefinition24,
    ArchitecturalZoneType,
    ArchitecturalRoomNode,
    ArchitecturalWorldGraph,
    WorldArchitectureFabricationPlatform,
    WorldArchitectureQualityScore,
    WorldArchitectureValidationReport,
    WorldArchitectureValidator,
    WorldArchitecturePackage,
)

# Procedural Lighting, Atmosphere, VFX & Presentation Fabrication System (UAF-81.25)
from .lighting_vfx import (
    LightType25,
    LightMobility,
    LightRole,
    LightSourceDefinition,
    SkyAtmosphereProfile,
    VFXEffectType,
    VFXEffectDefinition,
    PresentationDefinition25,
    LightingVFXFabricationPlatform,
    LightingVFXQualityScore,
    LightingVFXValidationReport,
    LightingVFXValidator,
    LightingVFXPackage,
)

# Character Fabrication, Advanced Anatomy, Clothing, Hair, Skinning & Rigging System (UAF-81.26)
from .character_organic import (
    CharacterArchetype26,
    CharacterProportions,
    LayeredClothingItem,
    OrganicCharacterDefinition,
    CharacterOrganicFabricationPlatform,
    CharacterOrganicQualityScore,
    CharacterOrganicValidationReport,
    CharacterOrganicValidator,
    CharacterOrganicPackage,
)

# Procedural Texture, UV, Material & Surface Detail Fabrication System (UAF-81.27)
from .surface_pipeline import (
    SurfaceClass27,
    UVStrategyType,
    ColorSpace27,
    TextureMapDefinition,
    SurfaceDefinition27,
    SurfacePipelineFabricationPlatform,
    SurfacePipelineQualityScore,
    SurfacePipelineValidationReport,
    SurfacePipelineValidator,
    SurfacePipelinePackage,
)

# Procedural Environment, Modular Kit, Blockout & World Building System (UAF-81.28)
from .world_building import (
    WorldType28,
    ModularCategory,
    SocketType28,
    ModularBlockDefinition,
    PlayableWorldDefinition,
    BlockoutZoneNode,
    BlockoutWorldGraph,
    WorldBuildingFabricationPlatform,
    WorldBuildingQualityScore,
    WorldBuildingValidationReport,
    WorldBuildingValidator,
    WorldBuildingPackage,
)

# Procedural Character Production, Rigging, Skinning & Animation Readiness System (UAF-81.29)
from .character_production import (
    CharacterType29,
    CharacterReadinessClass,
    ProductionBodyProportions,
    ProductionCharacterDefinition,
    CharacterProductionFabricationPlatform,
    CharacterProductionQualityScore,
    CharacterProductionValidationReport,
    CharacterProductionValidator,
    CharacterProductionPackage,
)

# Procedural Material, Texture, Surface & Decal Production System (UAF-81.30)
from .surface_material import (
    SurfaceType30,
    MaterialModel30,
    ColorSpace30,
    SurfaceMapItem,
    ProductionSurfaceDefinition,
    SurfaceMaterialProductionPlatform,
    SurfaceMaterialQualityScore,
    SurfaceMaterialValidationReport,
    SurfaceMaterialValidator,
    SurfaceMaterialPackage,
)

# Procedural Modular Asset & Architecture Production System (UAF-81.31)
from .modular_architecture import (
    ModuleType31,
    ArchitecturalKitType31,
    SocketType31,
    ArchitecturalModulePiece,
    ModularArchitectureKitDefinition,
    ModularArchitectureFabricationPlatform,
    ModularArchitectureQualityScore,
    ModularArchitectureValidationReport,
    ModularArchitectureValidator,
    ModularArchitecturePackage,
)

# Procedural World, Map, Terrain & Biome Generation System (UAF-81.32)
from .world_biome import (
    WorldType32,
    BiomeType32,
    WorldBounds32,
    BiomeDefinition32,
    BiomeWorldDefinition,
    WorldBiomeFabricationPlatform,
    WorldBiomeQualityScore,
    WorldBiomeValidationReport,
    WorldBiomeValidator,
    WorldBiomePackage,
)

# Procedural Character, Creature, Clothing, Skinning & Rigging System (UAF-81.33)
from .character_creature_rig import (
    CharacterType33,
    CharacterGenerationStrategy33,
    CharacterBodyProportions33,
    CharacterCreatureRigDefinition,
    CharacterCreatureRigFabricationPlatform,
    CharacterCreatureRigQualityScore,
    CharacterCreatureRigValidationReport,
    CharacterCreatureRigValidator,
    CharacterCreatureRigPackage,
)

# Procedural Material, Texture, UV, Decal & Surface Authoring System (UAF-81.34)
from .surface_decal import (
    MaterialFamily34,
    WearType34,
    DamageType34,
    SurfaceDecalItem,
    SurfaceAuthoringSpecification,
    SurfaceDecalFabricationPlatform,
    SurfaceDecalQualityScore,
    SurfaceDecalValidationReport,
    SurfaceDecalValidator,
    SurfaceDecalPackage,
)

# Procedural Environment, Modular Building, Blockout & World Assembly System (UAF-81.35)
from .building_assembly import (
    WorldType35,
    GridMode35,
    ModularKitComponent35,
    RoomType35,
    RoomDefinition35,
    BuildingAssemblySpecification,
    BuildingAssemblyFabricationPlatform,
    BuildingAssemblyQualityScore,
    BuildingAssemblyValidationReport,
    BuildingAssemblyValidator,
    BuildingAssemblyPackage,
)

# Procedural Terrain, Biome, Vegetation, Landscape & Outdoor World System (UAF-81.36)
from .terrain_biome import (
    BiomeType36,
    VegetationCategory36,
    SlopeClassification36,
    TerrainBounds36,
    TerrainBiomeSpecification,
    TerrainBiomeFabricationPlatform,
    TerrainBiomeQualityScore,
    TerrainBiomeValidationReport,
    TerrainBiomeValidator,
    TerrainBiomePackage,
)

# Professional Character Rigging, Skinning, Clothing, Hair, Facial & Animation-Ready Character System (UAF-81.37)
from .character_pipeline import (
    CharacterArchetype37,
    RigType37,
    ControlType37,
    CharacterProportions37,
    CharacterProductionSpecification,
    CharacterPipelineFabricationPlatform,
    CharacterPipelineQualityScore,
    CharacterPipelineValidationReport,
    CharacterPipelineValidator,
    CharacterPipelinePackage,
)

# Professional Texture, Material, Surface, Decal & Look-Development System (UAF-81.38)
from .surface_lookdev import (
    MaterialType38,
    ColorSpace38,
    NormalProfile38,
    PBRSurfaceProperties38,
    SurfaceLookdevSpecification,
    SurfaceLookdevFabricationPlatform,
    SurfaceLookdevQualityScore,
    SurfaceLookdevValidationReport,
    SurfaceLookdevValidator,
    SurfaceLookdevPackage,
)

# Procedural Modular Asset, Blockout, Kitbash, Architecture & Building System (UAF-81.39)
from .modular_kitbash import (
    ModuleType39,
    PivotType39,
    SnapMode39,
    KitStyle39,
    ModuleDimensions39,
    ModularKitbashSpecification,
    ModularKitbashFabricationPlatform,
    ModularKitbashQualityScore,
    ModularKitbashValidationReport,
    ModularKitbashValidator,
    ModularKitbashPackage,
)

# Procedural World, Map, Terrain, Biome, Road Network & Unreal World-Build System (UAF-81.40)
from .world_build import (
    WorldScaleProfile40,
    RegionType40,
    TerrainSlopeClass40,
    WorldDimensions40,
    WorldBuildSpecification,
    WorldBuildFabricationPlatform,
    WorldBuildQualityScore,
    WorldBuildValidationReport,
    WorldBuildValidator,
    WorldBuildPackage,
)

# Playable Level, Mission Flow, Encounter, AI Space & Gameplay Orchestration System (UAF-81.41)
from .level_mission import (
    MissionNodeType41,
    ObjectiveType41,
    GameplayState41,
    CheckpointType41,
    TriggerType41,
    MissionFlowMetrics41,
    PlayableLevelSpecification,
    LevelMissionFabricationPlatform,
    LevelMissionQualityScore,
    LevelMissionValidationReport,
    LevelMissionValidator,
    LevelMissionPackage,
)

# Character Rigging, Skinning, Animation, Retargeting & Unreal Character Assembly System (UAF-81.42)
from .character_assembly import (
    CharacterClassification42,
    SkeletonProfile42,
    ControlRigType42,
    RetargetProfile42,
    SkeletalDimensions42,
    CharacterAssemblySpecification,
    CharacterAssemblyFabricationPlatform,
    CharacterAssemblyQualityScore,
    CharacterAssemblyValidationReport,
    CharacterAssemblyValidator,
    CharacterAssemblyPackage,
)

# Material, Texture, UV, PBR, Procedural Surface & Unreal Material Authoring System (UAF-81.43)
from .pbr_surface import (
    MaterialCategory43,
    UVStrategy43,
    TexelDensityProfile43,
    PBRProperties43,
    PBRSurfaceSpecification,
    PBRSurfaceFabricationPlatform,
    PBRSurfaceQualityScore,
    PBRSurfaceValidationReport,
    PBRSurfaceValidator,
    PBRSurfacePackage,
)

# Environment, Modular Kit, Terrain, World Building & Unreal Map Authoring System (UAF-81.44)
from .map_authoring import (
    GridMode44,
    ModularCategory44,
    ConnectorType44,
    WorldTheme44,
    MapDimensions44,
    MapAuthoringSpecification,
    MapAuthoringFabricationPlatform,
    MapAuthoringQualityScore,
    MapAuthoringValidationReport,
    MapAuthoringValidator,
    MapAuthoringPackage,
)

# Character & Creature Production 2.0 (UAF-81.45)
from .character_prod_v2 import (
    CharacterArchetype45,
    ProportionProfile45,
    SymmetryMode45,
    PlatformProfile45,
    AnatomicalDimensions45,
    CharacterProdV2Specification,
    CharacterProdV2FabricationPlatform,
    CharacterProdV2QualityScore,
    CharacterProdV2ValidationReport,
    CharacterProdV2Validator,
    CharacterProdV2Package,
)

# Material, Texture, Surface Authoring & Procedural Look-Development System (UAF-81.46)
from .lookdev_surface import (
    MaterialFamily46,
    LookdevQualityTier46,
    SurfacePBRProperties46,
    LookdevSurfaceSpecification,
    LookdevSurfaceFabricationPlatform,
    LookdevSurfaceQualityScore,
    LookdevSurfaceValidationReport,
    LookdevSurfaceValidator,
    LookdevSurfacePackage,
)

# Modular Geometry, Building Blocks & Procedural Environment Assembly System (UAF-81.47)
from .modular_environment import (
    ModuleCategory47,
    SnapType47,
    EnvironmentStyle47,
    EnvironmentDimensions47,
    ModularEnvironmentSpecification,
    ModularEnvironmentFabricationPlatform,
    ModularEnvironmentQualityScore,
    ModularEnvironmentValidationReport,
    ModularEnvironmentValidator,
    ModularEnvironmentPackage,
)

# Terrain, World, Biome & Procedural Map Generation System (UAF-81.48)
from .terrain_world import (
    BiomeType48,
    TerrainGenMethod48,
    ErosionType48,
    TerrainDimensions48,
    TerrainWorldSpecification,
    TerrainWorldFabricationPlatform,
    TerrainWorldQualityScore,
    TerrainWorldValidationReport,
    TerrainWorldValidator,
    TerrainWorldPackage,
)

# Character & Creature Production System (UAF-81.49)
from .character_creature_system import (
    CharacterType49,
    SpeciesType49,
    BodyRepresentation49,
    BodyDimensions49,
    CharacterCreatureSpecification,
    CharacterCreatureFabricationPlatform,
    CharacterCreatureQualityScore,
    CharacterCreatureValidationReport,
    CharacterCreatureValidator,
    CharacterCreaturePackage,
)

# Environment, Architecture & Modular World Assembly System (UAF-81.50)
from .modular_assembly_system import (
    EnvironmentType50,
    ModularPieceType50,
    AssemblyDimensions50,
    ModularAssemblySpecification,
    ModularAssemblyFabricationPlatform,
    ModularAssemblyQualityScore,
    ModularAssemblyValidationReport,
    ModularAssemblyValidator,
    ModularAssemblyPackage,
)

# World Terrain, Biome, Vegetation & Natural Ecosystem System (UAF-81.51)
from .natural_ecosystem import (
    NaturalBiomeType51,
    TerrainType51,
    ErosionModel51,
    NaturalTerrainDimensions51,
    NaturalEcosystemSpecification,
    NaturalEcosystemFabricationPlatform,
    NaturalEcosystemQualityScore,
    NaturalEcosystemValidationReport,
    NaturalEcosystemValidator,
    NaturalEcosystemPackage,
)

# Universal Material, Texture & Surface Authoring System (UAF-81.52)
from .universal_surface import (
    SurfaceType52,
    PBRChannelType52,
    TextureResolution52,
    PBRSurfaceProperties52,
    UniversalSurfaceSpecification,
    UniversalSurfaceFabricationPlatform,
    UniversalSurfaceQualityScore,
    UniversalSurfaceValidationReport,
    UniversalSurfaceValidator,
    UniversalSurfacePackage,
)

# Universal Geometry, Mesh Processing & Procedural Modeling System (UAF-81.53)
from .universal_geometry import (
    MeshCategory53,
    TopologyType53,
    MeshDimensions53,
    UniversalMeshSpecification,
    UniversalGeometryFabricationPlatform,
    UniversalGeometryQualityScore,
    UniversalGeometryValidationReport,
    UniversalGeometryValidator,
    UniversalGeometryPackage,
)

# Universal Character, Creature, Rigging & Deformation System (UAF-81.54)
from .universal_character import (
    CharacterSpecies,
    CharacterArchetype,
    BodyShape,
    ProportionNormalization,
    AnatomicalRegionType,
    SymmetryType,
    SeamType,
    FootVariant,
    ClothingType,
    ClothingFit,
    ArmorComponentType,
    AccessoryType,
    AccessorySocket,
    HairType,
    IKType,
    ConstraintType,
    SkinningMethod,
    WeightStrategy,
    MorphType,
    FacialExpressionPreset,
    ValidationSeverity,
    ValidationCategory,
    BodyProportions,
    CustomAnatomicalRegion,
    AttachmentPoint,
    BodyComponent,
    HeadDefinition,
    EyeDefinition,
    EarDefinition,
    NoseDefinition,
    TeethDefinition,
    MouthDefinition,
    HandDefinition,
    FootDefinition,
    CreatureComponentDefinition,
    ClothingDefinition,
    ArmorDefinition,
    AccessoryDefinition,
    HairDefinition,
    BoneDefinition,
    RestPose,
    SkeletonDefinition,
    IKChain,
    ConstraintDefinition,
    RigDefinition,
    VertexWeight,
    SkinningDefinition,
    JointDeformationScore,
    CorrectiveShapeDefinition,
    DeformationProfile,
    MorphTarget,
    FacialRigDefinition,
    MorphTargetSystem,
    RetargetProfile,
    PoseDefinition,
    RagdollBody,
    RagdollConstraint,
    RagdollDefinition,
    CharacterCollisionDefinition,
    CharacterLODChain,
    CharacterNanitePolicy,
    CharacterDefinition,
    CharacterAssetGraph,
    CharacterSnapshot,
    CharacterDiff,
    UniversalCharacterFabricator,
    CharacterQualityScore,
    CharacterValidationReport,
    CharacterValidator,
    ProductionReadyCharacter,
    UniversalCharacterPackage,
)

# Universal Animation, Motion, Retargeting & Character Runtime System (UAF-81.55)
from .universal_animation import (
    AnimationType55,
    ChannelType55,
    CurveInterpolation55,
    MarkerType55,
    ResamplingMode55,
    BlendType55,
    LayerType55,
    LocomotionMode55,
    RootMotionMode55,
    CompressionMethod55,
    Keyframe55,
    AnimationTrack,
    AnimationCurve,
    AnimationMarker,
    AnimationEvent,
    AnimationClip,
    AnimationDefinition,
    RetargetProfile55,
    PoseLibrary55,
    BlendSpace55,
    MontageSection55,
    AnimationMontage55,
    StateTransition55,
    AnimationStateMachine55,
    MotionWarpingProfile55,
    FacialAnimationTrack55,
    AnimationCompressionProfile55,
    AnimationLODProfile55,
    RuntimeProfile55,
    AnimationDiff55,
    UniversalAnimationFabricator,
    AnimationQualityScore,
    AnimationValidationReport,
    UniversalAnimationValidator,
    ProductionReadyAnimatedCharacter,
    UniversalAnimationPackage,
)

# Universal World, Environment, Terrain, Vegetation & Procedural Scene System (UAF-81.56)
from .universal_world import (
    WorldDimensionType,
    WorldBounds,
    WorldCoordinateSystem,
    WorldCell,
    WorldRegion,
    SceneNodeType,
    WorldTransform,
    SceneNode,
    WorldSceneGraph,
    BiomeType,
    BiomeDefinition,
    BiomeMaskChannel,
    BiomeMask,
    TerrainRepresentation,
    TerrainGeneratorType,
    NoiseType,
    NoiseDefinition,
    TerrainLayer,
    TerrainOperator,
    TerrainModifierType,
    TerrainStamp,
    TerrainSplatChannel,
    TerrainSplatDefinition,
    SlopeField,
    TerrainCollisionMode,
    TerrainCollisionProfile,
    ErosionType,
    ErosionProfile,
    TerrainDefinition,
    WaterType,
    WaterBody,
    RiverDefinition,
    FlowField,
    ShorelineDefinition,
    WaterDefinition,
    VegetationCategory,
    VegetationSpecies,
    ScatterDistributionType,
    VegetationScatterProfile,
    FoliageLayer,
    FoliageLODType,
    FoliageDefinition,
    VegetationDefinition,
    RockType,
    RockOrientation,
    RockDefinition,
    PropCategory,
    PropPlacementMode,
    ExclusionVolumeType,
    ExclusionVolume,
    PropDefinition,
    ScatterConstraintType,
    ScatterInstance,
    BuildingType,
    BuildingDefinition,
    RoadType,
    RoadCutFillMode,
    RoadDefinition,
    BridgeDefinition,
    PathType,
    PathNode,
    PathNetwork,
    NavigationSource,
    NavigationFlag,
    NavigationDefinition,
    CollisionLayer,
    CollisionComplexity,
    WorldCollisionProfile,
    StreamingState,
    LevelStreamingMode,
    WorldPartitionCell,
    WorldPartitionProfile,
    HLODLevel,
    HLODGroupingMode,
    WorldHLODProfile,
    ImpostorDefinition,
    LightingProfile,
    TimeOfDayProfile,
    WeatherType,
    WeatherProfile,
    EnvironmentProfile,
    WorldAudioZoneType,
    WorldAudioProfile,
    WorldVFXProfile,
    WorldAnchorType,
    WorldAnchor,
    SpawnProfile,
    LandmarkType,
    LandmarkDefinition,
    WorldQueryType,
    WorldQuery,
    WorldSnapshot,
    WorldDiffCategory,
    WorldDiff,
    WorldCacheKey,
    WorldCache,
    MemoryBudget,
    InstanceBudget,
    TriangleBudget,
    StreamingBudget,
    WorldPerformanceReport,
    WorldDiagnosticReport,
    ExportTarget,
    WorldDefinition,
    UniversalWorldFabricator,
    UniversalWorldValidator,
    WorldValidationReport,
    ProductionReadyWorld,
)

# Universal AI, Navigation, NPC, Crowd, Behavior & Simulation System (UAF-81.57)
from .universal_ai import (
    AgentType,
    AgentLifecycleState,
    AgentState,
    AIRandomStream,
    AgentProfile,
    SenseType,
    PerceptionFilter,
    PerceptionEvent,
    HearingProfile,
    AISoundEvent,
    MemoryType,
    MemoryRecord,
    AIMemory,
    TargetLockMode,
    TargetScore,
    StateDefinition,
    StateTransition,
    FSMDefinition,
    BTNodeType,
    BTNodeStatus,
    BTAbortMode,
    BehaviorNode,
    BehaviorTree,
    UtilityCurveType,
    UtilityConsideration,
    UtilityAction,
    WorldFact,
    GOAPAction,
    GOAPGoal,
    ActionPlan,
    AIActionType,
    AIActionState,
    AIAction,
    AIMovementMode,
    AIMovementProfile,
    PathfindingAlgorithm,
    PathStatus,
    PathResult,
    DynamicObstacle,
    CrowdGroupType,
    CrowdAgent,
    FormationType,
    FormationMember,
    FormationDefinition,
    FactionType,
    Relationship,
    FactionDefinition,
    AICommunicationType,
    AICommunicationMessage,
    GroupRole,
    SquadDefinition,
    AICombatState,
    CombatRangeType,
    CoverPoint,
    AIInteractionType,
    InteractableDefinition,
    NeedType,
    NeedsProfile,
    ScheduleEntry,
    DailySchedule,
    AIEventType,
    AIEventPriority,
    AIEvent,
    AISaveState,
    SimulationReplay,
    AISimulationLOD,
    AbstractAgentState,
    AIPerformanceBudget,
    AIPerformanceReport,
    AIDiagnosticReport,
    AIQueryType,
    AIQuery,
    TerritoryDefinition,
    AIAgent,
    SimulationSnapshot,
    SimulationDefinition,
    UniversalAIFabricator,
    UniversalAIValidator,
    AIValidationReport,
    ProductionReadySimulation,
)

# Universal Gameplay, Quest, Mission, Dialogue, Inventory, Economy & Progression System (UAF-81.58)
from .universal_gameplay import (
    EntityType,
    GameplayTag,
    GameplayCommandType,
    CommandFailureCode,
    GameplayCommand,
    CommandResult,
    InteractionConditionType,
    InteractionCondition,
    InteractionActionType,
    InteractionAction,
    InteractionNode,
    InteractionGraph,
    QuestState,
    ObjectiveType,
    ObjectiveState,
    QuestObjective,
    QuestPrerequisite,
    RewardDefinition,
    QuestDefinition,
    MissionState,
    MissionCheckpoint,
    MissionPhase,
    MissionDefinition,
    DialogueChoice,
    DialogueNode,
    DialogueGraph,
    DialogueHistoryRecord,
    ItemRarity,
    ItemCategory,
    EquipmentSlot,
    StatType,
    StatModifier,
    ItemDefinition,
    ItemInstance,
    InventorySlot,
    Inventory,
    EquipmentLoadout,
    RecipeIngredient,
    CraftingRecipe,
    LootEntry,
    LootTable,
    SkillNode,
    SkillTree,
    AbilityCost,
    AbilityDefinition,
    ProgressionProfile,
    EffectType,
    StatusEffectInstance,
    TriggerType,
    GameplayTrigger,
    CurrencyType,
    Wallet,
    MerchantDefinition,
    TransactionType,
    TransactionRecord,
    FactionReputationTier,
    FactionReputation,
    WorldFlag,
    WorldUnlock,
    GameplayEntity,
    GameplayDiagnosticReport,
    GameplaySaveState,
    GameplayState,
    UniversalGameplayFabricator,
    UniversalGameplayValidator,
    GameplayValidationReport,
    ProductionReadyGameplay,
    UniversalGameplayPackager,
)























































__version__ = "1.0.0"

__all__ = [
    "ProjectContext",
    "ExecutionContext",
    "ResourceBudget",
    "UAFPathResolver",
    "PathSecurityValidator",
    "PathSecurityViolation",
    "AssetType",
    "AssetIdentity",
    "AssetSpecification",
    "CanonicalHasher",
    "Operation",
    "OperationType",
    "OperationStatus",
    "OperationStateMachine",
    "OperationResult",
    "InvalidStateTransitionError",
    "Artifact",
    "ArtifactLocation",
    "ArtifactManifest",
    "StorageBackend",
    "Diagnostic",
    "DiagnosticSeverity",
    "OperationMetrics",
    "UAFError",
    "SpecificationError",
    "ConfigurationError",
    "CapabilityError",
    "GenerationError",
    "ValidationError",
    "ArtifactError",
    "PersistenceError",
    "PackagingError",
    "PermissionError",
    "ResourceError",
    "ExternalProcessError",
    "RecoveryError",
    "UAFEvent",
    "ProductionStarted",
    "ProductionCompleted",
    "OperationStarted",
    "OperationCompleted",
    "OperationFailed",
    "ArtifactCreated",
    "ArtifactValidated",
    "ArtifactPublished",
    "CheckpointCreated",
    "CheckpointRestored",
    "UAFConfig",
    "ConfigResolver",
    "deep_merge",
    "Checkpoint",
    "CheckpointValidator",
    "CheckpointValidationResult",
    "BaseRegistry",
    "ContractValidator",
    "ValidationReport",
    "CapabilityDescription",
    "CapabilityRegistry",
    "MockGenerator",
    "ComplexityLevel",
    "SemanticAsset",
    "CharacterSemanticModel",
    "ANATOMICAL_REGIONS",
    "MaterialSemanticModel",
    "MaterialLayer",
    "TextureSetSemanticModel",
    "TextureMapSpecification",
    "ModularKitSemanticModel",
    "ModularModule",
    "ConnectionSocket",
    "EnvironmentSemanticModel",
    "WorldSemanticModel",
    "LevelSemanticModel",
    "AssetArchetype",
    "ArchetypeRegistry",
    "ParameterType",
    "ParameterProvenance",
    "ParameterMetadata",
    "UnitNormalizer",
    "ConstraintCategory",
    "ConstraintType",
    "AssetConstraint",
    "ConstraintResolver",
    "ResolutionTraceEntry",
    "ConflictReport",
    "DependencyGraph",
    "CyclicDependencyError",
    "StyleProfile",
    "QualityProfile",
    "TargetProfile",
    "BlueprintNode",
    "AssetBlueprint",
    "ResolvedAssetSpecification",
    "CapabilityGapReport",
    "ResolutionPipeline",
    "SpecificationMigrator",
    "CapabilityType",
    "CapabilityContract",
    "ComprehensiveCapability",
    "StrategyCategory",
    "DeterminismMode",
    "GenerationStrategy",
    "StrategyRegistry",
    "ExecutionBackend",
    "ImplementationDescription",
    "ImplementationRegistry",
    "StrategyScore",
    "CandidateEvaluation",
    "StrategyDecisionTrace",
    "StrategyEvaluator",
    "GenerationPlanNode",
    "GenerationPlan",
    "GenerationPlanner",
    "PlanningResult",
    "Replanner",
    "ReplanRequest",
    "ReplanningResult",
    "MultiResLevel",
    "DetailRepresentation",
    "DetailPolicy",
    "Transform3D",
    "AABB",
    "BoundingSphere",
    "MeshData",
    "GeometryComponent",
    "ModifierType",
    "ProceduralModifier",
    "ModifierStack",
    "LandmarkSystem",
    "STANDARD_LANDMARKS",
    "AnatomyProfile",
    "AttachmentSocket",
    "ClothingLayerSystem",
    "LayerClearanceReport",
    "LAYER_HIERARCHY",
    "TopologyProcessor",
    "TopologyReport",
    "UVGenerator",
    "UVReport",
    "LODGenerator",
    "LODLevel",
    "LODChain",
    "CollisionGenerator",
    "CollisionShape",
    "CollisionType",
    "GeometryValidator",
    "GeometryValidationReport",
    "ComponentizedCharacter",
    "AssetBuildRecord",
    "GeometryGenerator",
    "GeometryGeneratorRegistry",
    "ProceduralPrimitiveGenerator",
    "ComponentizedHeroGenerator",
    "PBRChannel",
    "ColorSpace",
    "ShaderModel",
    "ChannelPacking",
    "TextureDefinition",
    "TextureSource",
    "MaskType",
    "MaskSource",
    "BlendMode",
    "SurfaceMask",
    "MaterialLayer",
    "MaterialDefinition",
    "MaterialInstance",
    "SemanticSurfaceRole",
    "SurfaceDefinition",
    "MaterialFamily",
    "MaterialFamilyRegistry",
    "BakeType",
    "BakePlan",
    "BakeResult",
    "BakeEngine",
    "SurfaceValidator",
    "SurfaceValidationReport",
    "SurfaceDependencyTracker",
    "SurfaceSynthesizer",
    "UnrealSurfacePackage",
    "BoneRole",
    "BoneDefinition",
    "BindPoseType",
    "SkeletonArchetype",
    "CharacterSkeletonDefinition",
    "SkeletonBuilder",
    "IKType",
    "IKConstraint",
    "RigLayer",
    "RigDefinition",
    "WeightMethod",
    "VertexWeights",
    "SkinningDefinition",
    "WeightNormalizer",
    "WeightGenerator",
    "DeformationZone",
    "DeformationTestPose",
    "CorrectiveBlendshape",
    "DeformationScore",
    "DeformationEvaluator",
    "FacialRigDefinition",
    "STANDARD_FACIAL_BLENDSHAPES",
    "PhysicsBody",
    "PhysicsConstraint",
    "PhysicsAssetDefinition",
    "RetargetProfile",
    "UE5_MANNEQUIN_BONE_MAP",
    "UnrealCharacterPackage",
    "RigValidator",
    "RigValidationReport",
    "WorldGrid",
    "WorldSpecification",
    "ConnectorType",
    "ConnectorDefinition",
    "ModuleCategory",
    "ModuleDefinition",
    "ModularKitDefinition",
    "AssemblyNode",
    "AssemblyGraph",
    "RoomType",
    "RoomDefinition",
    "BuildingDefinition",
    "CoverType",
    "CoverDefinition",
    "SpawnPoint",
    "ObjectiveDefinition",
    "NavigationMeshMetadata",
    "DataLayer",
    "WorldPartitionCell",
    "HLODMetadata",
    "WorldQualityScore",
    "WorldValidationReport",
    "WorldValidator",
    "WorldPackage",
    "PhysicalClass",
    "TexelDensityProfile",
    "TextureSet",
    "SurfacePackage",
    "UVChannel",
    "UVStrategy",
    "UVOverlapPolicy",
    "UVDefinition",
    "TrimRegion",
    "TrimSheetDefinition",
    "TextureAtlasDefinition",
    "UDIMDefinition",
    "ProceduralPatternType",
    "ProceduralTextureSynthesizer",
    "SurfaceQualityScore",
    "QualityTier",
    "SurfaceQualityReport",
    "ComprehensiveSurfaceValidator",
    "PivotType",
    "OriginPolicy",
    "PivotDefinition",
    "SocketType",
    "RuntimeSocketDefinition",
    "NanitePolicy",
    "LODLevel",
    "LODChain",
    "AssetLifecycleState",
    "AssetAssemblyGraph",
    "RuntimeAssetQualityScore",
    "RuntimeAssetQualityReport",
    "RuntimeAssetValidator",
    "TransactionalAssetBuilder",
    "RuntimeAssetPackage",
    "CharacterClassification",
    "RigProfile",
    "Keyframe",
    "AnimationTrack",
    "AnimationEventType",
    "AnimationEvent",
    "AnimationClip",
    "AnimState",
    "AnimTransition",
    "AnimStateMachine",
    "MontageDefinition",
    "AnimationBlueprintContract",
    "AnimationLODLevel",
    "AnimationLODProfile",
    "CharacterBuildState",
    "AnimatedCharacterQualityScore",
    "AnimatedCharacterQualityReport",
    "AnimatedCharacterValidator",
    "AnimatedCharacterPackage",
    "ProportionProfileType",
    "ParametricAnatomy",
    "ProportionProfile",
    "FormLevel",
    "BodyComponent",
    "SemanticBodyGraph",
    "GarmentLayer",
    "GarmentDefinition",
    "TopologyStrategyType",
    "FabricationQuality",
    "ProceduralCharacterFabricator",
    "FabricationQualityScore",
    "FabricationValidationReport",
    "FabricationValidator",
    "FabricatedCharacterPackage",
    "MaterialFamilyType",
    "MaterialLayerBlendMode",
    "SurfaceRegion",
    "MaterialCompositionLayer",
    "MaterialRegionGraph",
    "SurfaceAuthoringEngine",
    "SurfaceAuthoringQualityScore",
    "SurfaceAuthoringValidationReport",
    "SurfaceAuthoringValidator",
    "AuthoredSurfacePackage",
    "SnapCategory",
    "SnapPoint",
    "GridProfile",
    "ModularPiece",
    "ModularGrammarRule",
    "ModularGrammar",
    "RoomType",
    "RoomNode",
    "BuildingFacilityGraph",
    "ProceduralEnvironmentFabricator",
    "EnvironmentQualityScore",
    "EnvironmentValidationReport",
    "EnvironmentValidator",
    "EnvironmentPackage",
    "TerrainMode",
    "ErosionType",
    "TerritoryModel",
    "LandmarkType",
    "NaturalLandmark",
    "BiomeType",
    "BiomeProfile",
    "ProceduralWorldSurfaceFabricator",
    "WorldSurfaceQualityScore",
    "WorldSurfaceValidationReport",
    "WorldSurfaceValidator",
    "WorldSurfacePackage",
    "CharacterClassification",
    "CharacterQualityTier",
    "CharacterStyle",
    "CharacterProfile",
    "DeformationProfile",
    "FaceProfile",
    "CharacterLayer",
    "CharacterFabricationPlatform",
    "CharacterQualityScore",
    "CharacterValidationReport",
    "CharacterSuiteValidator",
    "CharacterSuitePackage",
    "MaterialClassification",
    "MaterialDomain",
    "SurfaceWearType",
    "SurfaceProfile",
    "MaterialParameterType",
    "MaterialGraphContract",
    "SurfaceFabricationEngine",
    "SurfaceFabricationQualityScore",
    "SurfaceFabricationValidationReport",
    "SurfaceFabricationValidator",
    "SurfaceFabricationPackage",
    "WorldBounds",
    "WorldDefinition",
    "WaterBodyType",
    "WaterBody",
    "RoadNetwork",
    "DistrictType",
    "WorldDistrict",
    "GameplayZone",
    "WorldFabricationPlatform",
    "WorldQualityScore",
    "WorldValidationReport",
    "WorldValidator",
    "WorldFabricationPackage",
    "BoneRole",
    "BoneNode",
    "SkeletonHierarchy",
    "IKSolverType",
    "IKChain",
    "SkinningMethod",
    "SkinningWeightData",
    "CharacterAnimationFabricator",
    "CharacterAnimationQualityScore",
    "CharacterAnimationValidationReport",
    "CharacterAnimationValidator",
    "CharacterAnimationPackage",
    "SurfaceWeatheringState",
    "MaterialPBRProfile",
    "SurfaceDefinition",
    "TexturePackingType",
    "TextureChannelDefinition",
    "SurfaceProductionFabricator",
    "SurfaceProductionQualityScore",
    "SurfaceProductionValidationReport",
    "SurfaceProductionValidator",
    "SurfaceProductionPackage",
    "EnvironmentType",
    "ModularKitProfile",
    "EnvironmentDefinition",
    "RoomPurpose",
    "EnvironmentRoom",
    "SpatialConnection",
    "SpatialLayoutGraph",
    "ModularWorldFabricationPlatform",
    "ModularWorldQualityScore",
    "ModularWorldValidationReport",
    "ModularWorldValidator",
    "ModularWorldPackage",
    "GameModeType",
    "ScenarioLevelState",
    "PlayableScenarioDefinition",
    "GameplayNodeType",
    "GameplayNode",
    "GameplayEdge",
    "GameplayGraph",
    "ObjectiveType",
    "ScenarioObjective",
    "EncounterType",
    "ScenarioEncounter",
    "GameplayScenarioFabricator",
    "GameplayQualityScore",
    "GameplayValidationReport",
    "GameplayScenarioValidator",
    "PlayableScenarioPackage",
    "CharacterSpecies",
    "AnatomicalLandmarks",
    "CharacterDefinition21",
    "BodyPartType",
    "EquipmentLayerType",
    "ModularEquipmentLayer",
    "CharacterCreatureFabricationPlatform",
    "CharacterCreatureQualityScore",
    "CharacterCreatureValidationReport",
    "CharacterCreatureValidator",
    "CharacterCreaturePackage",
    "PhysicalMaterialClass",
    "SurfaceLayerType",
    "SurfaceDetailDefinition",
    "SurfaceDetailChannel",
    "SurfaceDetailFabricationPlatform",
    "SurfaceDetailQualityScore",
    "SurfaceDetailValidationReport",
    "SurfaceDetailValidator",
    "SurfaceDetailPackage",
    "BoneRoleType",
    "RigBoneNode",
    "StandardSkeletonHierarchy",
    "CharacterRigDefinition",
    "MotionClipType",
    "MotionClip",
    "AnimationMotionFabricationPlatform",
    "AnimationMotionQualityScore",
    "AnimationMotionValidationReport",
    "AnimationMotionValidator",
    "AnimationMotionPackage",
    "BiomeType24",
    "WorldBoundaryBounds",
    "WorldGridCell",
    "WorldDefinition24",
    "ArchitecturalZoneType",
    "ArchitecturalRoomNode",
    "ArchitecturalWorldGraph",
    "WorldArchitectureFabricationPlatform",
    "WorldArchitectureQualityScore",
    "WorldArchitectureValidationReport",
    "WorldArchitectureValidator",
    "WorldArchitecturePackage",
    "LightType25",
    "LightMobility",
    "LightRole",
    "LightSourceDefinition",
    "SkyAtmosphereProfile",
    "VFXEffectType",
    "VFXEffectDefinition",
    "PresentationDefinition25",
    "LightingVFXFabricationPlatform",
    "LightingVFXQualityScore",
    "LightingVFXValidationReport",
    "LightingVFXValidator",
    "LightingVFXPackage",
    "CharacterArchetype26",
    "CharacterProportions",
    "LayeredClothingItem",
    "OrganicCharacterDefinition",
    "CharacterOrganicFabricationPlatform",
    "CharacterOrganicQualityScore",
    "CharacterOrganicValidationReport",
    "CharacterOrganicValidator",
    "CharacterOrganicPackage",
    "SurfaceClass27",
    "UVStrategyType",
    "ColorSpace27",
    "TextureMapDefinition",
    "SurfaceDefinition27",
    "SurfacePipelineFabricationPlatform",
    "SurfacePipelineQualityScore",
    "SurfacePipelineValidationReport",
    "SurfacePipelineValidator",
    "SurfacePipelinePackage",
    "WorldType28",
    "ModularCategory",
    "SocketType28",
    "ModularBlockDefinition",
    "PlayableWorldDefinition",
    "BlockoutZoneNode",
    "BlockoutWorldGraph",
    "WorldBuildingFabricationPlatform",
    "WorldBuildingQualityScore",
    "WorldBuildingValidationReport",
    "WorldBuildingValidator",
    "WorldBuildingPackage",
    "CharacterType29",
    "CharacterReadinessClass",
    "ProductionBodyProportions",
    "ProductionCharacterDefinition",
    "CharacterProductionFabricationPlatform",
    "CharacterProductionQualityScore",
    "CharacterProductionValidationReport",
    "CharacterProductionValidator",
    "CharacterProductionPackage",
    "SurfaceType30",
    "MaterialModel30",
    "ColorSpace30",
    "SurfaceMapItem",
    "ProductionSurfaceDefinition",
    "SurfaceMaterialProductionPlatform",
    "SurfaceMaterialQualityScore",
    "SurfaceMaterialValidationReport",
    "SurfaceMaterialValidator",
    "SurfaceMaterialPackage",
    "ModuleType31",
    "ArchitecturalKitType31",
    "SocketType31",
    "ArchitecturalModulePiece",
    "ModularArchitectureKitDefinition",
    "ModularArchitectureFabricationPlatform",
    "ModularArchitectureQualityScore",
    "ModularArchitectureValidationReport",
    "ModularArchitectureValidator",
    "ModularArchitecturePackage",
    "WorldType32",
    "BiomeType32",
    "WorldBounds32",
    "BiomeDefinition32",
    "BiomeWorldDefinition",
    "WorldBiomeFabricationPlatform",
    "WorldBiomeQualityScore",
    "WorldBiomeValidationReport",
    "WorldBiomeValidator",
    "WorldBiomePackage",
    "CharacterType33",
    "CharacterGenerationStrategy33",
    "CharacterBodyProportions33",
    "CharacterCreatureRigDefinition",
    "CharacterCreatureRigFabricationPlatform",
    "CharacterCreatureRigQualityScore",
    "CharacterCreatureRigValidationReport",
    "CharacterCreatureRigValidator",
    "CharacterCreatureRigPackage",
    "MaterialFamily34",
    "WearType34",
    "DamageType34",
    "SurfaceDecalItem",
    "SurfaceAuthoringSpecification",
    "SurfaceDecalFabricationPlatform",
    "SurfaceDecalQualityScore",
    "SurfaceDecalValidationReport",
    "SurfaceDecalValidator",
    "SurfaceDecalPackage",
    "WorldType35",
    "GridMode35",
    "ModularKitComponent35",
    "RoomType35",
    "RoomDefinition35",
    "BuildingAssemblySpecification",
    "BuildingAssemblyFabricationPlatform",
    "BuildingAssemblyQualityScore",
    "BuildingAssemblyValidationReport",
    "BuildingAssemblyValidator",
    "BuildingAssemblyPackage",
    "BiomeType36",
    "VegetationCategory36",
    "SlopeClassification36",
    "TerrainBounds36",
    "TerrainBiomeSpecification",
    "TerrainBiomeFabricationPlatform",
    "TerrainBiomeQualityScore",
    "TerrainBiomeValidationReport",
    "TerrainBiomeValidator",
    "TerrainBiomePackage",
    "CharacterArchetype37",
    "RigType37",
    "ControlType37",
    "CharacterProportions37",
    "CharacterProductionSpecification",
    "CharacterPipelineFabricationPlatform",
    "CharacterPipelineQualityScore",
    "CharacterPipelineValidationReport",
    "CharacterPipelineValidator",
    "CharacterPipelinePackage",
    "MaterialType38",
    "ColorSpace38",
    "NormalProfile38",
    "PBRSurfaceProperties38",
    "SurfaceLookdevSpecification",
    "SurfaceLookdevFabricationPlatform",
    "SurfaceLookdevQualityScore",
    "SurfaceLookdevValidationReport",
    "SurfaceLookdevValidator",
    "SurfaceLookdevPackage",
    "ModuleType39",
    "PivotType39",
    "SnapMode39",
    "KitStyle39",
    "ModuleDimensions39",
    "ModularKitbashSpecification",
    "ModularKitbashFabricationPlatform",
    "ModularKitbashQualityScore",
    "ModularKitbashValidationReport",
    "ModularKitbashValidator",
    "ModularKitbashPackage",
    "WorldScaleProfile40",
    "RegionType40",
    "TerrainSlopeClass40",
    "WorldDimensions40",
    "WorldBuildSpecification",
    "WorldBuildFabricationPlatform",
    "WorldBuildQualityScore",
    "WorldBuildValidationReport",
    "WorldBuildValidator",
    "WorldBuildPackage",
    "MissionNodeType41",
    "ObjectiveType41",
    "GameplayState41",
    "CheckpointType41",
    "TriggerType41",
    "MissionFlowMetrics41",
    "PlayableLevelSpecification",
    "LevelMissionFabricationPlatform",
    "LevelMissionQualityScore",
    "LevelMissionValidationReport",
    "LevelMissionValidator",
    "LevelMissionPackage",
    "CharacterClassification42",
    "SkeletonProfile42",
    "ControlRigType42",
    "RetargetProfile42",
    "SkeletalDimensions42",
    "CharacterAssemblySpecification",
    "CharacterAssemblyFabricationPlatform",
    "CharacterAssemblyQualityScore",
    "CharacterAssemblyValidationReport",
    "CharacterAssemblyValidator",
    "CharacterAssemblyPackage",
    "MaterialCategory43",
    "UVStrategy43",
    "TexelDensityProfile43",
    "PBRProperties43",
    "PBRSurfaceSpecification",
    "PBRSurfaceFabricationPlatform",
    "PBRSurfaceQualityScore",
    "PBRSurfaceValidationReport",
    "PBRSurfaceValidator",
    "PBRSurfacePackage",
    "GridMode44",
    "ModularCategory44",
    "ConnectorType44",
    "WorldTheme44",
    "MapDimensions44",
    "MapAuthoringSpecification",
    "MapAuthoringFabricationPlatform",
    "MapAuthoringQualityScore",
    "MapAuthoringValidationReport",
    "MapAuthoringValidator",
    "MapAuthoringPackage",
    "CharacterArchetype45",
    "ProportionProfile45",
    "SymmetryMode45",
    "PlatformProfile45",
    "AnatomicalDimensions45",
    "CharacterProdV2Specification",
    "CharacterProdV2FabricationPlatform",
    "CharacterProdV2QualityScore",
    "CharacterProdV2ValidationReport",
    "CharacterProdV2Validator",
    "CharacterProdV2Package",
    "MaterialFamily46",
    "LookdevQualityTier46",
    "SurfacePBRProperties46",
    "LookdevSurfaceSpecification",
    "LookdevSurfaceFabricationPlatform",
    "LookdevSurfaceQualityScore",
    "LookdevSurfaceValidationReport",
    "LookdevSurfaceValidator",
    "LookdevSurfacePackage",
    "ModuleCategory47",
    "SnapType47",
    "EnvironmentStyle47",
    "EnvironmentDimensions47",
    "ModularEnvironmentSpecification",
    "ModularEnvironmentFabricationPlatform",
    "ModularEnvironmentQualityScore",
    "ModularEnvironmentValidationReport",
    "ModularEnvironmentValidator",
    "ModularEnvironmentPackage",
    "BiomeType48",
    "TerrainGenMethod48",
    "ErosionType48",
    "TerrainDimensions48",
    "TerrainWorldSpecification",
    "TerrainWorldFabricationPlatform",
    "TerrainWorldQualityScore",
    "TerrainWorldValidationReport",
    "TerrainWorldValidator",
    "TerrainWorldPackage",
    "CharacterType49",
    "SpeciesType49",
    "BodyRepresentation49",
    "BodyDimensions49",
    "CharacterCreatureSpecification",
    "CharacterCreatureFabricationPlatform",
    "CharacterCreatureQualityScore",
    "CharacterCreatureValidationReport",
    "CharacterCreatureValidator",
    "CharacterCreaturePackage",
    "EnvironmentType50",
    "ModularPieceType50",
    "AssemblyDimensions50",
    "ModularAssemblySpecification",
    "ModularAssemblyFabricationPlatform",
    "ModularAssemblyQualityScore",
    "ModularAssemblyValidationReport",
    "ModularAssemblyValidator",
    "ModularAssemblyPackage",
    "NaturalBiomeType51",
    "TerrainType51",
    "ErosionModel51",
    "NaturalTerrainDimensions51",
    "NaturalEcosystemSpecification",
    "NaturalEcosystemFabricationPlatform",
    "NaturalEcosystemQualityScore",
    "NaturalEcosystemValidationReport",
    "NaturalEcosystemValidator",
    "NaturalEcosystemPackage",
    "SurfaceType52",
    "PBRChannelType52",
    "TextureResolution52",
    "PBRSurfaceProperties52",
    "UniversalSurfaceSpecification",
    "UniversalSurfaceFabricationPlatform",
    "UniversalSurfaceQualityScore",
    "UniversalSurfaceValidationReport",
    "UniversalSurfaceValidator",
    "UniversalSurfacePackage",
    "MeshCategory53",
    "TopologyType53",
    "MeshDimensions53",
    "UniversalMeshSpecification",
    "UniversalGeometryFabricationPlatform",
    "UniversalGeometryQualityScore",
    "UniversalGeometryValidationReport",
    "UniversalGeometryValidator",
    "UniversalGeometryPackage",
    "CharacterSpecies",
    "CharacterArchetype",
    "BodyShape",
    "ProportionNormalization",
    "AnatomicalRegionType",
    "SymmetryType",
    "SeamType",
    "FootVariant",
    "ClothingType",
    "ClothingFit",
    "ArmorComponentType",
    "AccessoryType",
    "AccessorySocket",
    "HairType",
    "IKType",
    "ConstraintType",
    "SkinningMethod",
    "WeightStrategy",
    "MorphType",
    "FacialExpressionPreset",
    "ValidationSeverity",
    "ValidationCategory",
    "BodyProportions",
    "CustomAnatomicalRegion",
    "AttachmentPoint",
    "BodyComponent",
    "HeadDefinition",
    "EyeDefinition",
    "EarDefinition",
    "NoseDefinition",
    "TeethDefinition",
    "MouthDefinition",
    "HandDefinition",
    "FootDefinition",
    "CreatureComponentDefinition",
    "ClothingDefinition",
    "ArmorDefinition",
    "AccessoryDefinition",
    "HairDefinition",
    "BoneDefinition",
    "RestPose",
    "SkeletonDefinition",
    "IKChain",
    "ConstraintDefinition",
    "RigDefinition",
    "VertexWeight",
    "SkinningDefinition",
    "JointDeformationScore",
    "CorrectiveShapeDefinition",
    "DeformationProfile",
    "MorphTarget",
    "FacialRigDefinition",
    "MorphTargetSystem",
    "RetargetProfile",
    "PoseDefinition",
    "RagdollBody",
    "RagdollConstraint",
    "RagdollDefinition",
    "CharacterCollisionDefinition",
    "CharacterLODChain",
    "CharacterNanitePolicy",
    "CharacterDefinition",
    "CharacterAssetGraph",
    "CharacterSnapshot",
    "CharacterDiff",
    "UniversalCharacterFabricator",
    "CharacterQualityScore",
    "CharacterValidationReport",
    "CharacterValidator",
    "ProductionReadyCharacter",
    "UniversalCharacterPackage",
    "AnimationType55",
    "ChannelType55",
    "CurveInterpolation55",
    "MarkerType55",
    "ResamplingMode55",
    "BlendType55",
    "LayerType55",
    "LocomotionMode55",
    "RootMotionMode55",
    "CompressionMethod55",
    "Keyframe55",
    "AnimationTrack",
    "AnimationCurve",
    "AnimationMarker",
    "AnimationEvent",
    "AnimationClip",
    "AnimationDefinition",
    "RetargetProfile55",
    "PoseLibrary55",
    "BlendSpace55",
    "MontageSection55",
    "AnimationMontage55",
    "StateTransition55",
    "AnimationStateMachine55",
    "MotionWarpingProfile55",
    "FacialAnimationTrack55",
    "AnimationCompressionProfile55",
    "AnimationLODProfile55",
    "RuntimeProfile55",
    "AnimationDiff55",
    "UniversalAnimationFabricator",
    "AnimationQualityScore",
    "AnimationValidationReport",
    "UniversalAnimationValidator",
    "ProductionReadyAnimatedCharacter",
    "UniversalAnimationPackage",
    "WorldDimensionType",
    "WorldBounds",
    "WorldCoordinateSystem",
    "WorldCell",
    "WorldRegion",
    "SceneNodeType",
    "WorldTransform",
    "SceneNode",
    "WorldSceneGraph",
    "BiomeType",
    "BiomeDefinition",
    "BiomeMaskChannel",
    "BiomeMask",
    "TerrainRepresentation",
    "TerrainGeneratorType",
    "NoiseType",
    "NoiseDefinition",
    "TerrainLayer",
    "TerrainOperator",
    "TerrainModifierType",
    "TerrainStamp",
    "TerrainSplatChannel",
    "TerrainSplatDefinition",
    "SlopeField",
    "TerrainCollisionMode",
    "TerrainCollisionProfile",
    "ErosionType",
    "ErosionProfile",
    "TerrainDefinition",
    "WaterType",
    "WaterBody",
    "RiverDefinition",
    "FlowField",
    "ShorelineDefinition",
    "WaterDefinition",
    "VegetationCategory",
    "VegetationSpecies",
    "ScatterDistributionType",
    "VegetationScatterProfile",
    "FoliageLayer",
    "FoliageLODType",
    "FoliageDefinition",
    "VegetationDefinition",
    "RockType",
    "RockOrientation",
    "RockDefinition",
    "PropCategory",
    "PropPlacementMode",
    "ExclusionVolumeType",
    "ExclusionVolume",
    "PropDefinition",
    "ScatterConstraintType",
    "ScatterInstance",
    "BuildingType",
    "BuildingDefinition",
    "RoadType",
    "RoadCutFillMode",
    "RoadDefinition",
    "BridgeDefinition",
    "PathType",
    "PathNode",
    "PathNetwork",
    "NavigationSource",
    "NavigationFlag",
    "NavigationDefinition",
    "CollisionLayer",
    "CollisionComplexity",
    "WorldCollisionProfile",
    "StreamingState",
    "LevelStreamingMode",
    "WorldPartitionCell",
    "WorldPartitionProfile",
    "HLODLevel",
    "HLODGroupingMode",
    "WorldHLODProfile",
    "ImpostorDefinition",
    "LightingProfile",
    "TimeOfDayProfile",
    "WeatherType",
    "WeatherProfile",
    "EnvironmentProfile",
    "WorldAudioZoneType",
    "WorldAudioProfile",
    "WorldVFXProfile",
    "WorldAnchorType",
    "WorldAnchor",
    "SpawnProfile",
    "LandmarkType",
    "LandmarkDefinition",
    "WorldQueryType",
    "WorldQuery",
    "WorldSnapshot",
    "WorldDiffCategory",
    "WorldDiff",
    "WorldCacheKey",
    "WorldCache",
    "MemoryBudget",
    "InstanceBudget",
    "TriangleBudget",
    "StreamingBudget",
    "WorldPerformanceReport",
    "WorldDiagnosticReport",
    "ExportTarget",
    "WorldDefinition",
    "UniversalWorldFabricator",
    "UniversalWorldValidator",
    "WorldValidationReport",
    "ProductionReadyWorld",
    "AgentType",
    "AgentLifecycleState",
    "AgentState",
    "AIRandomStream",
    "AgentProfile",
    "SenseType",
    "PerceptionFilter",
    "PerceptionEvent",
    "HearingProfile",
    "AISoundEvent",
    "MemoryType",
    "MemoryRecord",
    "AIMemory",
    "TargetLockMode",
    "TargetScore",
    "StateDefinition",
    "StateTransition",
    "FSMDefinition",
    "BTNodeType",
    "BTNodeStatus",
    "BTAbortMode",
    "BehaviorNode",
    "BehaviorTree",
    "UtilityCurveType",
    "UtilityConsideration",
    "UtilityAction",
    "WorldFact",
    "GOAPAction",
    "GOAPGoal",
    "ActionPlan",
    "AIActionType",
    "AIActionState",
    "AIAction",
    "AIMovementMode",
    "AIMovementProfile",
    "PathfindingAlgorithm",
    "PathStatus",
    "PathResult",
    "DynamicObstacle",
    "CrowdGroupType",
    "CrowdAgent",
    "FormationType",
    "FormationMember",
    "FormationDefinition",
    "FactionType",
    "Relationship",
    "FactionDefinition",
    "AICommunicationType",
    "AICommunicationMessage",
    "GroupRole",
    "SquadDefinition",
    "AICombatState",
    "CombatRangeType",
    "CoverPoint",
    "AIInteractionType",
    "InteractableDefinition",
    "NeedType",
    "NeedsProfile",
    "ScheduleEntry",
    "DailySchedule",
    "AIEventType",
    "AIEventPriority",
    "AIEvent",
    "AISaveState",
    "SimulationReplay",
    "AISimulationLOD",
    "AbstractAgentState",
    "AIPerformanceBudget",
    "AIPerformanceReport",
    "AIDiagnosticReport",
    "AIQueryType",
    "AIQuery",
    "TerritoryDefinition",
    "AIAgent",
    "SimulationSnapshot",
    "SimulationDefinition",
    "UniversalAIFabricator",
    "UniversalAIValidator",
    "AIValidationReport",
    "ProductionReadySimulation",
    "EntityType",
    "GameplayTag",
    "GameplayCommandType",
    "CommandFailureCode",
    "GameplayCommand",
    "CommandResult",
    "InteractionConditionType",
    "InteractionCondition",
    "InteractionActionType",
    "InteractionAction",
    "InteractionNode",
    "InteractionGraph",
    "QuestState",
    "ObjectiveType",
    "ObjectiveState",
    "QuestObjective",
    "QuestPrerequisite",
    "RewardDefinition",
    "QuestDefinition",
    "MissionState",
    "MissionCheckpoint",
    "MissionPhase",
    "MissionDefinition",
    "DialogueChoice",
    "DialogueNode",
    "DialogueGraph",
    "DialogueHistoryRecord",
    "ItemRarity",
    "ItemCategory",
    "EquipmentSlot",
    "StatType",
    "StatModifier",
    "ItemDefinition",
    "ItemInstance",
    "InventorySlot",
    "Inventory",
    "EquipmentLoadout",
    "RecipeIngredient",
    "CraftingRecipe",
    "LootEntry",
    "LootTable",
    "SkillNode",
    "SkillTree",
    "AbilityCost",
    "AbilityDefinition",
    "ProgressionProfile",
    "EffectType",
    "StatusEffectInstance",
    "TriggerType",
    "GameplayTrigger",
    "CurrencyType",
    "Wallet",
    "MerchantDefinition",
    "TransactionType",
    "TransactionRecord",
    "FactionReputationTier",
    "FactionReputation",
    "WorldFlag",
    "WorldUnlock",
    "GameplayEntity",
    "GameplayDiagnosticReport",
    "GameplaySaveState",
    "GameplayState",
    "UniversalGameplayFabricator",
    "UniversalGameplayValidator",
    "GameplayValidationReport",
    "ProductionReadyGameplay",
    "UniversalGameplayPackager",
]























































