from enum import Enum

class PackageType(str, Enum):
    UNREAL_ASSET_PACKAGE = "UNREAL_ASSET_PACKAGE"
    AOE_ARCHIVE = "AOE_ARCHIVE"
    DEBUG_PACKAGE = "DEBUG_PACKAGE"
    VALIDATION_PACKAGE = "VALIDATION_PACKAGE"
    DELIVERY_PACKAGE = "DELIVERY_PACKAGE"

class PackageStatus(str, Enum):
    CREATED = "CREATED"
    ANALYZING = "ANALYZING"
    RESOLVING_DEPENDENCIES = "RESOLVING_DEPENDENCIES"
    ASSEMBLING = "ASSEMBLING"
    VALIDATING = "VALIDATING"
    SEALED = "SEALED"
    READY_FOR_DELIVERY = "READY_FOR_DELIVERY"
    DELIVERING = "DELIVERING"
    DELIVERED = "DELIVERED"
    DELIVERY_VERIFIED = "DELIVERY_VERIFIED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    ROLLED_BACK = "ROLLED_BACK"

class DeliveryTargetType(str, Enum):
    LOCAL_DIRECTORY = "LOCAL_DIRECTORY"
    PROJECT_DIRECTORY = "PROJECT_DIRECTORY"
    ARCHIVE = "ARCHIVE"
    REMOTE_STORAGE = "REMOTE_STORAGE"
    CI_ARTIFACT = "CI_ARTIFACT"

class DependencyState(str, Enum):
    RESOLVED = "RESOLVED"
    MISSING = "MISSING"
    INVALID = "INVALID"
    DUPLICATE = "DUPLICATE"
    CONFLICT = "CONFLICT"
    OPTIONAL = "OPTIONAL"

class OverwritePolicy(str, Enum):
    REJECT = "REJECT"
    OVERWRITE_IF_SAME = "OVERWRITE_IF_SAME"
    OVERWRITE = "OVERWRITE"
    VERSION = "VERSION"

class PackagingSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
