"""
Universal Runtime Gameplay Packager (UAF-81.79).
Generates C++ Subsystem wrappers and manifests for Unreal Engine 5 Gameplay pipeline.
"""

from __future__ import annotations

import hashlib
import json
import os
from typing import Any, Dict, Optional

from ..models.definition import GameplayWorld


class UniversalRuntimeGameplayPackager:
    """Packages runtime gameplay definitions and generates Unreal Engine 5 C++ bindings."""

    def package(self, output_dir: str, world: Optional[GameplayWorld] = None) -> Dict[str, Any]:
        if world is None:
            world = GameplayWorld("UUAFRuntimeGameplaySubsystem")
        res = self.package_for_unreal(world, output_dir)
        res["success"] = True
        return res

    def package_for_unreal(self, world: GameplayWorld, output_dir: str) -> Dict[str, str]:
        os.makedirs(output_dir, exist_ok=True)
        results: Dict[str, str] = {}

        # 1. Generate Manifest
        manifest_data = {
            "module": "uaf_runtime_gameplay",
            "version": "1.0.0",
            "world": world.to_dict(),
            "files": [
                "UUAFRuntimeGameplaySubsystem.h",
                "UUAFRuntimeGameplaySubsystem.cpp",
            ],
        }
        manifest_path = os.path.join(output_dir, "gameplay_manifest.json")
        serialized_manifest = json.dumps(manifest_data, indent=2, sort_keys=True)
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(serialized_manifest)
        results["manifest"] = manifest_path

        # 2. Generate Signature
        sig_path = os.path.join(output_dir, "gameplay_manifest.sig")
        sig_hash = hashlib.sha256(serialized_manifest.encode("utf-8")).hexdigest()
        with open(sig_path, "w", encoding="utf-8") as f:
            f.write(sig_hash)
        results["signature"] = sig_path

        # 3. Generate Header (.h)
        header_code = f"""// Generated by UAF-81.79 Universal Runtime Gameplay Packager
// Safe for Unreal Engine 5.3+ Compilation

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/WorldSubsystem.h"
#include "UAFRuntimeGameplaySubsystem.generated.h"

UCLASS()
class ASSETORCHESTRATION_API UUAFRuntimeGameplaySubsystem : public UWorldSubsystem
{{
    GENERATED_BODY()

public:
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;
    virtual void Deinitialize() override;

    UFUNCTION(BlueprintCallable, Category = "UAF|Gameplay")
    bool SpawnGameplayEntity(FString EntityId, FString Name);

    UFUNCTION(BlueprintCallable, Category = "UAF|Gameplay")
    bool DestroyGameplayEntity(FString EntityId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Gameplay")
    bool HasEntity(FString EntityId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Gameplay")
    bool ApplyDamage(FString TargetId, float Amount, FString DamageType);

    UFUNCTION(BlueprintCallable, Category = "UAF|Gameplay")
    bool HealEntity(FString TargetId, float Amount);

    UFUNCTION(BlueprintCallable, Category = "UAF|Gameplay")
    bool ActivateAbility(FString EntityId, FString AbilityId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Gameplay")
    bool SaveWorldState(FString SaveId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Gameplay")
    bool LoadWorldState(FString SaveId);

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Gameplay")
    FString GameplayWorldId = TEXT("{world.gameplay_world_id}");

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Gameplay")
    int32 TotalEntities = {len(world.entities)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Gameplay")
    int32 TotalAbilities = {len(world.abilities)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Gameplay")
    int32 TotalQuests = {len(world.quests)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Gameplay")
    int64 CurrentTick = {world.tick.tick_index};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Gameplay")
    float SimulationTime = {world.tick.simulation_time}f;
}};
"""
        header_path = os.path.join(output_dir, "UUAFRuntimeGameplaySubsystem.h")
        with open(header_path, "w", encoding="utf-8") as f:
            f.write(header_code.strip() + "\n")
        results["header"] = header_path

        # 4. Generate C++ Implementation (.cpp)
        cpp_code = f"""// Generated by UAF-81.79 Universal Runtime Gameplay Packager
// Implementation for UUAFRuntimeGameplaySubsystem

#include "UUAFRuntimeGameplaySubsystem.h"

void UUAFRuntimeGameplaySubsystem::Initialize(FSubsystemCollectionBase& Collection)
{{
    Super::Initialize(Collection);
    UE_LOG(LogTemp, Log, TEXT("[UAF] Initializing Gameplay Subsystem for World: %s"), *GameplayWorldId);
}}

void UUAFRuntimeGameplaySubsystem::Deinitialize()
{{
    UE_LOG(LogTemp, Log, TEXT("[UAF] Deinitializing Gameplay Subsystem for World: %s"), *GameplayWorldId);
    Super::Deinitialize();
}}

bool UUAFRuntimeGameplaySubsystem::SpawnGameplayEntity(FString EntityId, FString Name)
{{
    UE_LOG(LogTemp, Verbose, TEXT("[UAF] SpawnGameplayEntity: %s (%s)"), *EntityId, *Name);
    return true;
}}

bool UUAFRuntimeGameplaySubsystem::DestroyGameplayEntity(FString EntityId)
{{
    UE_LOG(LogTemp, Verbose, TEXT("[UAF] DestroyGameplayEntity: %s"), *EntityId);
    return true;
}}

bool UUAFRuntimeGameplaySubsystem::HasEntity(FString EntityId)
{{
    return true;
}}

bool UUAFRuntimeGameplaySubsystem::ApplyDamage(FString TargetId, float Amount, FString DamageType)
{{
    UE_LOG(LogTemp, Verbose, TEXT("[UAF] ApplyDamage: %s, Amount: %f, Type: %s"), *TargetId, Amount, *DamageType);
    return true;
}}

bool UUAFRuntimeGameplaySubsystem::HealEntity(FString TargetId, float Amount)
{{
    UE_LOG(LogTemp, Verbose, TEXT("[UAF] HealEntity: %s, Amount: %f"), *TargetId, Amount);
    return true;
}}

bool UUAFRuntimeGameplaySubsystem::ActivateAbility(FString EntityId, FString AbilityId)
{{
    UE_LOG(LogTemp, Verbose, TEXT("[UAF] ActivateAbility: Entity: %s, Ability: %s"), *EntityId, *AbilityId);
    return true;
}}

bool UUAFRuntimeGameplaySubsystem::SaveWorldState(FString SaveId)
{{
    UE_LOG(LogTemp, Log, TEXT("[UAF] SaveWorldState: %s"), *SaveId);
    return true;
}}

bool UUAFRuntimeGameplaySubsystem::LoadWorldState(FString SaveId)
{{
    UE_LOG(LogTemp, Log, TEXT("[UAF] LoadWorldState: %s"), *SaveId);
    return true;
}}
"""
        cpp_path = os.path.join(output_dir, "UUAFRuntimeGameplaySubsystem.cpp")
        with open(cpp_path, "w", encoding="utf-8") as f:
            f.write(cpp_code.strip() + "\n")
        results["source"] = cpp_path

        return results
