from enum import Enum

class GuardrailSeverity(Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class SkeletalDiscrepancyType(Enum):
    MISSING_BONE = "MISSING_BONE"
    MISMATCHED_PARENT = "MISMATCHED_PARENT"
    ROOT_MISMATCH = "ROOT_MISMATCH"
    CYCLIC_HIERARCHY = "CYCLIC_HIERARCHY"
    TRANSFORM_DRIFT = "TRANSFORM_DRIFT"

class SpatialViolationType(Enum):
    GROUND_PENETRATION = "GROUND_PENETRATION"
    GROUND_FLOATING = "GROUND_FLOATING"
    ENTITY_OVERLAP = "ENTITY_OVERLAP"
    BOUNDS_COLLISION = "BOUNDS_COLLISION"

class CoplanarConflictType(Enum):
    IDENTICAL_PLANE_OVERLAP = "IDENTICAL_PLANE_OVERLAP"
    COINCIDENT_INTERNAL_FACE = "COINCIDENT_INTERNAL_FACE"
    NEAR_COPLANAR_Z_FIGHTING = "NEAR_COPLANAR_Z_FIGHTING"
    TILE_BOUNDS_INTERSECTION = "TILE_BOUNDS_INTERSECTION"

class RemediationStrategy(Enum):
    AUTO_SYNTHESIZE = "AUTO_SYNTHESIZE"
    AUTO_ALIGN_DATUM = "AUTO_ALIGN_DATUM"
    REPULSION_DISPERSION = "REPULSION_DISPERSION"
    MICRO_LAYERING_OFFSET = "MICRO_LAYERING_OFFSET"
    COINCIDENT_FACE_CULL = "COINCIDENT_FACE_CULL"
    MODULAR_GRID_SNAP = "MODULAR_GRID_SNAP"
