"""
Universal Runtime UI Packager (UAF-81.78).
Generates C++ Subsystem wrappers and manifests for Unreal Engine 5 UI pipeline.
"""

from __future__ import annotations

import hashlib
import json
import os
from typing import Any, Dict, Optional

from ..models.definition import UIWorld


class UniversalRuntimeUIPackager:
    """Packages runtime UI definitions and generates Unreal Engine 5 C++ bindings."""

    def package(self, output_dir: str, world: Optional[UIWorld] = None) -> Dict[str, Any]:
        if world is None:
            world = UIWorld("UUAFRuntimeUISubsystem")
        res = self.package_for_unreal(world, output_dir)
        res["success"] = True
        return res

    def package_for_unreal(self, world: UIWorld, output_dir: str) -> Dict[str, str]:
        os.makedirs(output_dir, exist_ok=True)
        results: Dict[str, str] = {}

        # 1. Generate Manifest
        manifest_data = {
            "module": "uaf_runtime_ui",
            "version": "1.0.0",
            "world": world.to_dict(),
            "files": [
                "UUAFRuntimeUISubsystem.h",
                "UUAFRuntimeUISubsystem.cpp",
            ],
        }
        manifest_path = os.path.join(output_dir, "ui_manifest.json")
        serialized_manifest = json.dumps(manifest_data, indent=2, sort_keys=True)
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(serialized_manifest)
        results["manifest"] = manifest_path

        # 2. Generate Signature
        sig_path = os.path.join(output_dir, "ui_manifest.sig")
        sig_hash = hashlib.sha256(serialized_manifest.encode("utf-8")).hexdigest()
        with open(sig_path, "w", encoding="utf-8") as f:
            f.write(sig_hash)
        results["signature"] = sig_path

        # 3. Generate Header (.h)
        header_code = f"""// Generated by UAF-81.78 Universal Runtime UI Packager
// Safe for Unreal Engine 5.3+ Compilation

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/WorldSubsystem.h"
#include "UAFRuntimeUISubsystem.generated.h"

UCLASS()
class ASSETORCHESTRATION_API UUAFRuntimeUISubsystem : public UWorldSubsystem
{{
    GENERATED_BODY()

public:
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;
    virtual void Deinitialize() override;

    UFUNCTION(BlueprintCallable, Category = "UAF|UI")
    bool SetFocusNode(FString NodeId);

    UFUNCTION(BlueprintCallable, Category = "UAF|UI")
    FString GetFocusedNode();

    UFUNCTION(BlueprintCallable, Category = "UAF|UI")
    void SetScrollOffset(FString NodeId, float OffsetX, float OffsetY);

    UFUNCTION(BlueprintCallable, Category = "UAF|UI")
    void SetActiveTheme(FString ThemeId);

    UFUNCTION(BlueprintCallable, Category = "UAF|UI")
    void SetActiveLocale(FString Locale);

    UFUNCTION(BlueprintCallable, Category = "UAF|UI")
    FString TranslateKey(FString Key);

    UPROPERTY(BlueprintReadOnly, Category = "UAF|UI")
    FString UIWorldId = TEXT("{world.ui_world_id}");

    UPROPERTY(BlueprintReadOnly, Category = "UAF|UI")
    int32 TotalNodes = {len(world.nodes)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|UI")
    int32 TotalRoots = {len(world.root_ids)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|UI")
    int32 TotalThemes = {len(world.themes)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|UI")
    int32 TotalStyles = {len(world.styles)};
}};
"""
        header_path = os.path.join(output_dir, "UUAFRuntimeUISubsystem.h")
        with open(header_path, "w", encoding="utf-8") as f:
            f.write(header_code)
        results["header"] = header_path

        # 4. Generate Source (.cpp)
        cpp_code = f"""// Generated by UAF-81.78 Universal Runtime UI Packager

#include "UUAFRuntimeUISubsystem.h"

void UUAFRuntimeUISubsystem::Initialize(FSubsystemCollectionBase& Collection)
{{
    Super::Initialize(Collection);
    UE_LOG(LogTemp, Log, TEXT("UUAFRuntimeUISubsystem initialized for UIWorld: %s"), *UIWorldId);
}}

void UUAFRuntimeUISubsystem::Deinitialize()
{{
    UE_LOG(LogTemp, Log, TEXT("UUAFRuntimeUISubsystem deinitialized for UIWorld: %s"), *UIWorldId);
    Super::Deinitialize();
}}

bool UUAFRuntimeUISubsystem::SetFocusNode(FString NodeId)
{{
    // Focus node assignment in runtime UI
    return true;
}}

FString UUAFRuntimeUISubsystem::GetFocusedNode()
{{
    return TEXT("{world.focused_node_id or ''}");
}}

void UUAFRuntimeUISubsystem::SetScrollOffset(FString NodeId, float OffsetX, float OffsetY)
{{
    // Set scroll offset on container
}}

void UUAFRuntimeUISubsystem::SetActiveTheme(FString ThemeId)
{{
    // Switch active theme
}}

void UUAFRuntimeUISubsystem::SetActiveLocale(FString Locale)
{{
    // Switch active locale
}}

FString UUAFRuntimeUISubsystem::TranslateKey(FString Key)
{{
    // Lookup localized string
    return Key;
}}
"""
        cpp_path = os.path.join(output_dir, "UUAFRuntimeUISubsystem.cpp")
        with open(cpp_path, "w", encoding="utf-8") as f:
            f.write(cpp_code)
        results["source"] = cpp_path

        return results
