from enum import Enum

class CommandType(str, Enum):
    # High-level Asset Commands
    CREATE_ASSET = "CREATE_ASSET"
    UPDATE_ASSET = "UPDATE_ASSET"
    REGENERATE_ASSET = "REGENERATE_ASSET"
    REGENERATE_COMPONENT = "REGENERATE_COMPONENT"
    VALIDATE_ASSET = "VALIDATE_ASSET"
    PREVIEW_ASSET = "PREVIEW_ASSET"
    DELETE_ASSET = "DELETE_ASSET"
    
    # Low-level Blender Mesh & Object Commands
    CREATE_OBJECT = "CREATE_OBJECT"
    UPDATE_OBJECT = "UPDATE_OBJECT"
    DELETE_OBJECT = "DELETE_OBJECT"
    CREATE_MESH = "CREATE_MESH"
    UPDATE_MESH = "UPDATE_MESH"
    CREATE_MATERIAL = "CREATE_MATERIAL"
    ASSIGN_MATERIAL = "ASSIGN_MATERIAL"
    UPDATE_TRANSFORM = "UPDATE_TRANSFORM"
    SET_VISIBILITY = "SET_VISIBILITY"
    RENDER = "RENDER"
    INSPECT = "INSPECT"
    VALIDATE = "VALIDATE"
    
    # Forbidden Denylist Commands
    DELETE_ALL_OBJECTS = "DELETE_ALL_OBJECTS"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class GatewayState(str, Enum):
    IDLE = "IDLE"
    PLANNING = "PLANNING"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    ROLLING_BACK = "ROLLING_BACK"
    EMERGENCY_STOPPED = "EMERGENCY_STOPPED"

class ExecutionStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED_VALIDATION = "FAILED_VALIDATION"
    FAILED_EXECUTION = "FAILED_EXECUTION"
    FAILED_VERIFICATION = "FAILED_VERIFICATION"
    ROLLED_BACK = "ROLLED_BACK"
    UNKNOWN_OUTCOME = "UNKNOWN_OUTCOME"
    BLOCKED = "BLOCKED"

class DriftType(str, Enum):
    OBJECT_MISSING = "OBJECT_MISSING"
    OBJECT_EXTRA = "OBJECT_EXTRA"
    TRANSFORM_CHANGED = "TRANSFORM_CHANGED"
    MATERIAL_CHANGED = "MATERIAL_CHANGED"
    EXTERNAL_EDIT = "EXTERNAL_EDIT"

class ReconciliationMode(str, Enum):
    ACCEPT_EXTERNAL = "ACCEPT_EXTERNAL"
    RESTORE_EXPECTED = "RESTORE_EXPECTED"
    MERGE = "MERGE"
    REGENERATE = "REGENERATE"

class GatewayErrorType(str, Enum):
    COMMAND_DENIED = "COMMAND_DENIED"
    CAPABILITY_UNSUPPORTED = "CAPABILITY_UNSUPPORTED"
    STATE_CONFLICT = "STATE_CONFLICT"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    LOOP_DETECTED = "LOOP_DETECTED"
    TIMEOUT = "TIMEOUT"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
