"""
Universal Processing System (UAF-81.71).
"""

from uaf.universal_processing.models import (
    ResourceType,
    TextureFormat,
    ColorSpace,
    ResizeFilter,
    MipFilter,
    IndexFormat,
    DecimationStrategy,
    AudioFormat,
    ShaderStage,
    ShaderTarget,
    PlatformVariant,
    QualityLevel,
    ProcessingStatus,
    normalize_processing_path,
    ProcessingProfile,
    TextureProcessingProfile,
    MeshProcessingProfile,
    AudioProcessingProfile,
    MaterialProcessingProfile,
    ShaderProcessingProfile,
    DerivedResource,
    LODLevel,
    LODChain,
    ShaderReflectionData,
    ShaderVariant,
    OptimizationPass,
    BuildArtifact,
    BuildManifest,
    ProcessingTelemetry,
    ProcessingStateSnapshot,
    ProcessingDiagnosticBundle,
)
from uaf.universal_processing.engine import UniversalProcessingFabricator
from uaf.universal_processing.validation import UniversalProcessingValidator
from uaf.universal_processing.package import UniversalProcessingPackager

__all__ = [
    "ResourceType",
    "TextureFormat",
    "ColorSpace",
    "ResizeFilter",
    "MipFilter",
    "IndexFormat",
    "DecimationStrategy",
    "AudioFormat",
    "ShaderStage",
    "ShaderTarget",
    "PlatformVariant",
    "QualityLevel",
    "ProcessingStatus",
    "normalize_processing_path",
    "ProcessingProfile",
    "TextureProcessingProfile",
    "MeshProcessingProfile",
    "AudioProcessingProfile",
    "MaterialProcessingProfile",
    "ShaderProcessingProfile",
    "DerivedResource",
    "LODLevel",
    "LODChain",
    "ShaderReflectionData",
    "ShaderVariant",
    "OptimizationPass",
    "BuildArtifact",
    "BuildManifest",
    "ProcessingTelemetry",
    "ProcessingStateSnapshot",
    "ProcessingDiagnosticBundle",
    "UniversalProcessingFabricator",
    "UniversalProcessingValidator",
    "UniversalProcessingPackager",
]
