from enum import Enum

class AgentState(str, Enum):
    UNINITIALIZED = "UNINITIALIZED"
    IDLE = "IDLE"
    ASSIGNED = "ASSIGNED"
    EXECUTING = "EXECUTING"
    WAITING_RESOURCE = "WAITING_RESOURCE"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SHUTDOWN = "SHUTDOWN"

class AgentPermission(str, Enum):
    READ_PROJECT = "READ_PROJECT"
    READ_ASSET = "READ_ASSET"
    WRITE_ASSET = "WRITE_ASSET"
    CREATE_ASSET = "CREATE_ASSET"
    MODIFY_ASSET = "MODIFY_ASSET"
    DELETE_ASSET = "DELETE_ASSET"
    EXECUTE_BLENDER = "EXECUTE_BLENDER"
    EXPORT_ASSET = "EXPORT_ASSET"
    PACKAGE_ASSET = "PACKAGE_ASSET"
    RUN_VALIDATION = "RUN_VALIDATION"

class TaskStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"

class TaskPriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"
    BACKGROUND = "BACKGROUND"

class FailureAction(str, Enum):
    RETRY = "RETRY"
    FAIL = "FAIL"
    SKIP = "SKIP"
    ABORT_ORCHESTRATION = "ABORT_ORCHESTRATION"
    ROLLBACK = "ROLLBACK"
    REPLAN = "REPLAN"
