"""
Strategy category and determinism enumerations.
UAF-81.2 Sections 17, 57, 58, 59.
"""

from enum import Enum


class StrategyCategory(str, Enum):
    PROCEDURAL = "PROCEDURAL"
    PARAMETRIC = "PARAMETRIC"
    MODULAR = "MODULAR"
    KITBASH = "KITBASH"
    REFERENCE_DRIVEN = "REFERENCE_DRIVEN"
    SCAN_DRIVEN = "SCAN_DRIVEN"
    SIMULATION = "SIMULATION"
    TEXTURE_DRIVEN = "TEXTURE_DRIVEN"
    HYBRID = "HYBRID"
    EXTERNAL_GENERATOR = "EXTERNAL_GENERATOR"
    MANUAL_ASSISTED = "MANUAL_ASSISTED"


class DeterminismMode(str, Enum):
    DETERMINISTIC = "DETERMINISTIC"
    SEEDED_DETERMINISTIC = "SEEDED_DETERMINISTIC"
    NON_DETERMINISTIC = "NON_DETERMINISTIC"
