from enum import Enum

class TaskSource(str, Enum):
    USER = "USER"
    ANTIGRAVITY = "ANTIGRAVITY"
    CRITIC = "CRITIC"
    VALIDATOR = "VALIDATOR"
    SYSTEM = "SYSTEM"
    EXTERNAL = "EXTERNAL"

class TaskAction(str, Enum):
    CREATE = "CREATE"
    MODIFY = "MODIFY"
    DELETE = "DELETE"
    MOVE = "MOVE"
    DUPLICATE = "DUPLICATE"
    REPLACE = "REPLACE"
    REGENERATE = "REGENERATE"
    CONFIGURE = "CONFIGURE"
    VALIDATE = "VALIDATE"
    REPAIR = "REPAIR"
    INSPECT = "INSPECT"
    EXPORT = "EXPORT"
    IMPORT = "IMPORT"

class SemanticOperation(str, Enum):
    AGE_ASSET = "AGE_ASSET"
    CHANGE_STYLE = "CHANGE_STYLE"
    CHANGE_PROPORTIONS = "CHANGE_PROPORTIONS"
    CHANGE_DIMENSIONS = "CHANGE_DIMENSIONS"
    ADD_COMPONENT = "ADD_COMPONENT"
    REMOVE_COMPONENT = "REMOVE_COMPONENT"
    CHANGE_MATERIAL = "CHANGE_MATERIAL"
    CHANGE_LAYOUT = "CHANGE_LAYOUT"
    REBUILD_COMPONENT = "REBUILD_COMPONENT"
    REGENERATE_ASSET = "REGENERATE_ASSET"
    FIX_GEOMETRY = "FIX_GEOMETRY"
    FIX_COLLISION = "FIX_COLLISION"
    OPTIMIZE_ASSET = "OPTIMIZE_ASSET"
    DELETE_ASSET = "DELETE_ASSET"
    MULTI_TARGET = "MULTI_TARGET"

class TaskScope(str, Enum):
    PROPERTY = "PROPERTY"
    COMPONENT = "COMPONENT"
    ASSET = "ASSET"
    LEVEL = "LEVEL"
    PROJECT = "PROJECT"

class TaskPriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"
    BACKGROUND = "BACKGROUND"

class TaskRiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class TaskStatusEnum(str, Enum):
    RECEIVED = "RECEIVED"
    COMPILING = "COMPILING"
    COMPILED = "COMPILED"
    AMBIGUOUS = "AMBIGUOUS"
    INVALID = "INVALID"
    WAITING_APPROVAL = "WAITING_APPROVAL"
    PLANNED = "PLANNED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class AmbiguityType(str, Enum):
    NONE = "NONE"
    AMBIGUOUS_TARGET = "AMBIGUOUS_TARGET"
    AMBIGUOUS_VALUE = "AMBIGUOUS_VALUE"
    AMBIGUOUS_UNIT = "AMBIGUOUS_UNIT"
    AMBIGUOUS_SCOPE = "AMBIGUOUS_SCOPE"
    AMBIGUOUS_OPERATION = "AMBIGUOUS_OPERATION"
    AMBIGUOUS_REFERENCE = "AMBIGUOUS_REFERENCE"

class TaskPermissionType(str, Enum):
    READ_WORLD = "READ_WORLD"
    MODIFY_ASSET = "MODIFY_ASSET"
    DELETE_ASSET = "DELETE_ASSET"
    EXECUTE_BLENDER = "EXECUTE_BLENDER"
    EXPORT_ASSET = "EXPORT_ASSET"

class ConstraintTypeEnum(str, Enum):
    LOCK = "LOCK"
    LIMIT = "LIMIT"
    REQUIRE = "REQUIRE"
    FORBID = "FORBID"
    PRESERVE = "PRESERVE"
