from enum import Enum

class AssetState(str, Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    PRODUCTION = "PRODUCTION"
    PRODUCTION_LOCKED = "PRODUCTION_LOCKED"
    QUARANTINED = "QUARANTINED"
    DEPRECATED = "DEPRECATED"

class ReuseDecisionType(str, Enum):
    EXACT_REUSE = "EXACT_REUSE"
    PARAMETRIC_VARIANT = "PARAMETRIC_VARIANT"
    MODIFY_EXISTING = "MODIFY_EXISTING"
    DUPLICATE_AND_MODIFY = "DUPLICATE_AND_MODIFY"
    TEMPLATE_REUSE = "TEMPLATE_REUSE"
    COMPOSE = "COMPOSE"
    GENERATE_NEW = "GENERATE_NEW"
