from enum import Enum

class CausalCategory(str, Enum):
    GEOMETRY_PARAMETER = "GEOMETRY_PARAMETER"
    TOPOLOGY = "TOPOLOGY"
    TRANSFORM = "TRANSFORM"
    PROPORTION = "PROPORTION"
    DIMENSION = "DIMENSION"
    MATERIAL = "MATERIAL"
    TEXTURE = "TEXTURE"
    UV = "UV"
    LIGHTING = "LIGHTING"
    CAMERA = "CAMERA"
    COMPOSITION = "COMPOSITION"
    SEMANTIC_STRUCTURE = "SEMANTIC_STRUCTURE"
    GENERATION_STRATEGY = "GENERATION_STRATEGY"
    ASSET_CONFIGURATION = "ASSET_CONFIGURATION"
    PIPELINE_CONFIGURATION = "PIPELINE_CONFIGURATION"
    UNKNOWN = "UNKNOWN"

class CriticPriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    UNKNOWN = "UNKNOWN"

class IterationRecommendation(str, Enum):
    CONTINUE = "CONTINUE"
    CORRECT = "CORRECT"
    REGENERATE = "REGENERATE"
    REVIEW = "REVIEW"
    STOP = "STOP"

class EvidenceType(str, Enum):
    VISUAL_EVIDENCE = "VISUAL_EVIDENCE"
    GEOMETRIC_EVIDENCE = "GEOMETRIC_EVIDENCE"
    TOPOLOGICAL_EVIDENCE = "TOPOLOGICAL_EVIDENCE"
    PARAMETER_EVIDENCE = "PARAMETER_EVIDENCE"
    SEMANTIC_EVIDENCE = "SEMANTIC_EVIDENCE"
    HISTORICAL_EVIDENCE = "HISTORICAL_EVIDENCE"
    PIPELINE_EVIDENCE = "PIPELINE_EVIDENCE"

class ActionAutonomyLevel(str, Enum):
    AUTONOMOUSLY_ACTIONABLE = "AUTONOMOUSLY_ACTIONABLE"
    REQUIRES_ADDITIONAL_EVIDENCE = "REQUIRES_ADDITIONAL_EVIDENCE"
    REQUIRES_HUMAN_REVIEW = "REQUIRES_HUMAN_REVIEW"
    BLOCKED = "BLOCKED"

class ConflictSeverity(str, Enum):
    MINOR = "MINOR"
    MODERATE = "MODERATE"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"
