"""
Universal Runtime Gameplay World Module (UAF-81.79).
Public API exports for Entity Component System, Character Controllers,
Camera Controllers, Interaction System, Triggers, Quests, Abilities,
Inventory, Combat State, Status Effects, Gameplay Tags, Rules, Timers,
Spawn/Despawn, Save/Load, Replay, Determinism, and UE5 Subsystem Packager.
"""

from .models.definition import (
    copy_dict_deterministic,
    GameplayWorldState,
    EntityLifecycleState,
    MovementState,
    CameraMode,
    InteractionState,
    TriggerState,
    TriggerEventType,
    QuestState,
    ObjectiveState,
    AbilityState,
    StatusStackingPolicy,
    TimerType,
    GameplayCommandType,
    GameplayEventType,
    DamageType,
    GameplayTagContainer,
    CharacterControllerComponent,
    CameraControllerComponent,
    InteractableComponent,
    TriggerComponent,
    HealthComponent,
    DamageRequest,
    DamageResult,
    InventorySlot,
    InventoryComponent,
    StatusEffect,
    AbilityDefinition,
    QuestObjective,
    QuestDefinition,
    GameplayRule,
    GameplayTimer,
    GameplayCommand,
    GameplayEvent,
    SpawnRequest,
    DespawnRequest,
    SaveState,
    GameplaySnapshot,
    GameplayTick,
    GameplayWorldSettings,
    Entity,
    GameplayWorld,
)

from .engine.universal_runtime_gameplay_fabricator import (
    UniversalRuntimeGameplayFabricator,
)

from .validation.universal_runtime_gameplay_validator import (
    GameplayValidationIssue,
    UniversalRuntimeGameplayValidator,
)

from .package.universal_runtime_gameplay_packager import (
    UniversalRuntimeGameplayPackager,
)

__all__ = [
    "copy_dict_deterministic",
    "GameplayWorldState",
    "EntityLifecycleState",
    "MovementState",
    "CameraMode",
    "InteractionState",
    "TriggerState",
    "TriggerEventType",
    "QuestState",
    "ObjectiveState",
    "AbilityState",
    "StatusStackingPolicy",
    "TimerType",
    "GameplayCommandType",
    "GameplayEventType",
    "DamageType",
    "GameplayTagContainer",
    "CharacterControllerComponent",
    "CameraControllerComponent",
    "InteractableComponent",
    "TriggerComponent",
    "HealthComponent",
    "DamageRequest",
    "DamageResult",
    "InventorySlot",
    "InventoryComponent",
    "StatusEffect",
    "AbilityDefinition",
    "QuestObjective",
    "QuestDefinition",
    "GameplayRule",
    "GameplayTimer",
    "GameplayCommand",
    "GameplayEvent",
    "SpawnRequest",
    "DespawnRequest",
    "SaveState",
    "GameplaySnapshot",
    "GameplayTick",
    "GameplayWorldSettings",
    "Entity",
    "GameplayWorld",
    "UniversalRuntimeGameplayFabricator",
    "GameplayValidationIssue",
    "UniversalRuntimeGameplayValidator",
    "UniversalRuntimeGameplayPackager",
]
