from enum import Enum

class GraphNodeType(str, Enum):
    ASSET = "ASSET"
    COMPONENT = "COMPONENT"
    GEOMETRY = "GEOMETRY"
    MATERIAL = "MATERIAL"
    TEXTURE = "TEXTURE"
    COLLISION = "COLLISION"
    SOCKET = "SOCKET"
    ANCHOR = "ANCHOR"
    LOD = "LOD"
    VARIANT = "VARIANT"
    MODIFIER = "MODIFIER"
    METADATA = "METADATA"

class GraphRelationType(str, Enum):
    CONTAINS = "CONTAINS"
    PART_OF = "PART_OF"
    ATTACHED_TO = "ATTACHED_TO"
    PARENT_OF = "PARENT_OF"
    CHILD_OF = "CHILD_OF"
    ABOVE = "ABOVE"
    BELOW = "BELOW"
    INSIDE = "INSIDE"
    OUTSIDE = "OUTSIDE"
    CENTERED_ON = "CENTERED_ON"
    ALIGNED_WITH = "ALIGNED_WITH"
    DEPENDS_ON = "DEPENDS_ON"
    GENERATED_FROM = "GENERATED_FROM"
    MODIFIED_FROM = "MODIFIED_FROM"
    USES = "USES"
    CONSTRAINED_BY = "CONSTRAINED_BY"
    REPRESENTS = "REPRESENTS"

class ReconciliationState(str, Enum):
    SYNCHRONIZED = "SYNCHRONIZED"
    BLENDER_AHEAD = "BLENDER_AHEAD"
    TWIN_AHEAD = "TWIN_AHEAD"
    CONFLICT = "CONFLICT"
    ORPHANED = "ORPHANED"
    MISSING = "MISSING"

class ComponentLifecycleState(str, Enum):
    ACTIVE = "ACTIVE"
    MODIFIED = "MODIFIED"
    REPLACED = "REPLACED"
    DELETED = "DELETED"
    ORPHANED = "ORPHANED"
    APPROVED = "APPROVED"
    LOCKED = "LOCKED"

class AssetLifecycleState(str, Enum):
    CREATED = "CREATED"
    GENERATING = "GENERATING"
    GENERATED = "GENERATED"
    VALIDATING = "VALIDATING"
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"

class ImpactLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class DiffType(str, Enum):
    COMPONENT_TRANSFORM_CHANGED = "COMPONENT_TRANSFORM_CHANGED"
    COMPONENT_ADDED = "COMPONENT_ADDED"
    COMPONENT_REMOVED = "COMPONENT_REMOVED"
    MATERIAL_CHANGED = "MATERIAL_CHANGED"
    METADATA_CHANGED = "METADATA_CHANGED"
