"""
UAF-81.76: Universal Runtime Audio World System.
Provides audio world lifecycle, sources, listeners, clips, streaming, buses,
mixing, effect chains, 3D spatialization, attenuation, and Doppler effect.
"""

from .models.definition import (
    AudioWorldState,
    AudioDeviceState,
    AudioSourceState,
    AudioSourceType,
    AudioDistanceModel,
    VoiceStealingPolicy,
    VoiceState,
    LoopMode,
    AudioCommandType,
    AudioEventType,
    AudioEffectType,
    AudioClip,
    AudioStream,
    AudioDevice,
    AudioEffect,
    AudioBus,
    AudioVoice,
    AudioSource,
    AudioListener,
    AudioCommand,
    AudioEvent,
    AudioSnapshot,
    AudioReplayCommand,
    AudioReplay,
    AudioMixer,
    AudioWorldSettings,
    AudioWorld,
)
from .engine.universal_runtime_audio_fabricator import (
    UniversalRuntimeAudioFabricator,
    _vec3_dist,
    _vec3_dot,
    _vec3_cross,
    _vec3_norm,
)
from .validation.universal_runtime_audio_validator import (
    AudioValidationIssue,
    UniversalRuntimeAudioValidator,
)
from .package.universal_runtime_audio_packager import UniversalRuntimeAudioPackager

__all__ = [
    "AudioWorldState",
    "AudioDeviceState",
    "AudioSourceState",
    "AudioSourceType",
    "AudioDistanceModel",
    "VoiceStealingPolicy",
    "VoiceState",
    "LoopMode",
    "AudioCommandType",
    "AudioEventType",
    "AudioEffectType",
    "AudioClip",
    "AudioStream",
    "AudioDevice",
    "AudioEffect",
    "AudioBus",
    "AudioVoice",
    "AudioSource",
    "AudioListener",
    "AudioCommand",
    "AudioEvent",
    "AudioSnapshot",
    "AudioReplayCommand",
    "AudioReplay",
    "AudioMixer",
    "AudioWorldSettings",
    "AudioWorld",
    "UniversalRuntimeAudioFabricator",
    "_vec3_dist",
    "_vec3_dot",
    "_vec3_cross",
    "_vec3_norm",
    "AudioValidationIssue",
    "UniversalRuntimeAudioValidator",
    "UniversalRuntimeAudioPackager",
]
