from enum import Enum

class LoopState(str, Enum):
    CREATED = "CREATED"
    INITIALIZING = "INITIALIZING"
    GENERATING = "GENERATING"
    EVALUATING = "EVALUATING"
    CRITIQUING = "CRITIQUING"
    CORRECTING = "CORRECTING"
    COMPARING = "COMPARING"
    CONTINUING = "CONTINUING"
    CONVERGED = "CONVERGED"
    STAGNATED = "STAGNATED"
    REGRESSED = "REGRESSED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMEOUT = "TIMEOUT"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    COMPLETED = "COMPLETED"

class DecisionOutcome(str, Enum):
    CONTINUE = "CONTINUE"
    CONVERGED = "CONVERGED"
    STAGNATED = "STAGNATED"
    REGRESSED = "REGRESSED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    CANCELLED = "CANCELLED"

class StopReason(str, Enum):
    CONVERGENCE_REACHED = "CONVERGENCE_REACHED"
    STAGNATION_DETECTED = "STAGNATION_DETECTED"
    OSCILLATION_DETECTED = "OSCILLATION_DETECTED"
    CYCLE_DETECTED = "CYCLE_DETECTED"
    MAX_ITERATIONS_REACHED = "MAX_ITERATIONS_REACHED"
    TIMEOUT_REACHED = "TIMEOUT_REACHED"
    CRITICAL_FAILURE = "CRITICAL_FAILURE"
    USER_CANCELLED = "USER_CANCELLED"

class LoopEventType(str, Enum):
    LOOP_STARTED = "LOOP_STARTED"
    ITERATION_STARTED = "ITERATION_STARTED"
    EVALUATION_COMPLETED = "EVALUATION_COMPLETED"
    CRITIC_COMPLETED = "CRITIC_COMPLETED"
    CORRECTION_COMPLETED = "CORRECTION_COMPLETED"
    ITERATION_ACCEPTED = "ITERATION_ACCEPTED"
    ITERATION_REJECTED = "ITERATION_REJECTED"
    ROLLBACK_COMPLETED = "ROLLBACK_COMPLETED"
    LOOP_COMPLETED = "LOOP_COMPLETED"

class RegressionPolicyType(str, Enum):
    STRICT_NO_REGRESSION = "STRICT_NO_REGRESSION"
    ALLOW_TEMPORARY = "ALLOW_TEMPORARY"
    ROLLBACK_ON_CRITICAL = "ROLLBACK_ON_CRITICAL"
