"""
Universal Runtime Audio Packager (UAF-81.76).
Generates C++ Subsystem wrappers and manifests for Unreal Engine 5 audio pipeline.
"""

from __future__ import annotations
import hashlib
import json
import os
from typing import Any, Dict, Optional

from ..models.definition import AudioWorld


class UniversalRuntimeAudioPackager:
    """Packages runtime audio definitions and generates Unreal Engine 5 C++ bindings."""

    def package(self, output_dir: str, world: Optional[AudioWorld] = None) -> Dict[str, Any]:
        if world is None:
            world = AudioWorld("UUAFRuntimeAudioSubsystem")
        res = self.package_for_unreal(world, output_dir)
        res["success"] = True
        return res

    def package_for_unreal(self, world: AudioWorld, output_dir: str) -> Dict[str, str]:
        os.makedirs(output_dir, exist_ok=True)
        results: Dict[str, str] = {}

        # 1. Generate Manifest
        manifest_data = {
            "module": "uaf_runtime_audio",
            "version": "1.0.0",
            "world": world.to_dict(),
            "files": [
                "UUAFRuntimeAudioSubsystem.h",
                "UUAFRuntimeAudioSubsystem.cpp",
            ],
        }
        manifest_path = os.path.join(output_dir, "audio_manifest.json")
        serialized_manifest = json.dumps(manifest_data, indent=2, sort_keys=True)
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(serialized_manifest)
        results["manifest"] = manifest_path

        # 2. Generate Signature
        sig_path = os.path.join(output_dir, "audio_manifest.sig")
        sig_hash = hashlib.sha256(serialized_manifest.encode("utf-8")).hexdigest()
        with open(sig_path, "w", encoding="utf-8") as f:
            f.write(sig_hash)
        results["signature"] = sig_path

        # 3. Generate Header (.h)
        header_code = f"""// Generated by UAF-81.76 Universal Runtime Audio Packager
// Safe for Unreal Engine 5.3+ Compilation

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/WorldSubsystem.h"
#include "UAFRuntimeAudioSubsystem.generated.h"

UCLASS()
class ASSETORCHESTRATION_API UUAFRuntimeAudioSubsystem : public UWorldSubsystem
{{
    GENERATED_BODY()

public:
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;
    virtual void Deinitialize() override;

    UFUNCTION(BlueprintCallable, Category = "UAF|Audio")
    void PlayAudioSource(FString SourceId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Audio")
    void StopAudioSource(FString SourceId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Audio")
    void SetBusVolume(FString BusId, float Volume);

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Audio")
    FString AudioWorldId = TEXT("{world.audio_world_id}");

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Audio")
    int32 TotalSources = {len(world.sources)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Audio")
    int32 TotalBuses = {len(world.mixer.buses)};
}};
"""
        header_path = os.path.join(output_dir, "UUAFRuntimeAudioSubsystem.h")
        with open(header_path, "w", encoding="utf-8") as f:
            f.write(header_code)
        results["header"] = header_path

        # 4. Generate Source (.cpp)
        cpp_code = f"""// Generated by UAF-81.76 Universal Runtime Audio Packager

#include "UUAFRuntimeAudioSubsystem.h"

void UUAFRuntimeAudioSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{{
    Super::Initialize(Collection);
    UE_LOG(LogTemp, Log, TEXT("UUAFRuntimeAudioSubsystem initialized for AudioWorld: %s"), *AudioWorldId);
}}

void UUAFRuntimeAudioSubsystem::Deinitialize()
{{
    UE_LOG(LogTemp, Log, TEXT("UUAFRuntimeAudioSubsystem deinitialized for AudioWorld: %s"), *AudioWorldId);
    Super::Deinitialize();
}}

void UUAFRuntimeAudioSubsystem::PlayAudioSource(FString SourceId)
{{
    // Execute Voice Allocation and Spatialization
}}

void UUAFRuntimeAudioSubsystem::StopAudioSource(FString SourceId)
{{
    // Stop and Release Voice
}}

void UUAFRuntimeAudioSubsystem::SetBusVolume(FString BusId, float Volume)
{{
    // Update Bus Hierarchy Volume
}}
"""
        cpp_path = os.path.join(output_dir, "UUAFRuntimeAudioSubsystem.cpp")
        with open(cpp_path, "w", encoding="utf-8") as f:
            f.write(cpp_code)
        results["source"] = cpp_path

        return results
