from enum import Enum

class PatternState(str, Enum):
    CANDIDATE = "CANDIDATE"
    VALIDATED = "VALIDATED"
    KNOWN_GOOD = "KNOWN_GOOD"
    DEPRECATED = "DEPRECATED"
    INVALIDATED = "INVALIDATED"

class MemorySource(str, Enum):
    USER = "USER"
    AI = "AI"
    BUILDER = "BUILDER"
    VALIDATOR = "VALIDATOR"
    REFERENCE = "REFERENCE"
    SUCCESSFUL_BUILD = "SUCCESSFUL_BUILD"
    FAILURE_ANALYSIS = "FAILURE_ANALYSIS"
    MANUAL_OVERRIDE = "MANUAL_OVERRIDE"

class ProblemSignature(str, Enum):
    ROOF_TOO_LOW = "ROOF_TOO_LOW"
    ROOF_TOO_HIGH = "ROOF_TOO_HIGH"
    WINDOWS_TOO_SMALL = "WINDOWS_TOO_SMALL"
    WINDOWS_TOO_LARGE = "WINDOWS_TOO_LARGE"
    BODY_TOO_WIDE = "BODY_TOO_WIDE"
    BODY_TOO_NARROW = "BODY_TOO_NARROW"
    SILHOUETTE_MISMATCH = "SILHOUETTE_MISMATCH"
    STYLE_MISMATCH = "STYLE_MISMATCH"

class TrustLevel(str, Enum):
    UNTRUSTED = "UNTRUSTED"
    REVIEWED = "REVIEWED"
    VALIDATED = "VALIDATED"
    SYSTEM_APPROVED = "SYSTEM_APPROVED"

class PatternScope(str, Enum):
    LOCAL = "LOCAL"
    FAMILY = "FAMILY"
    CATEGORY = "CATEGORY"
    GLOBAL = "GLOBAL"
