"""
UAF-81.100: Unreal Engine 5 Weather & Atmosphere Exporter.
Exports complete weather system manifests (JSON), diurnal curve keyframes (JSON),
and automated Python scripts for direct in-editor actor instantiation in UE5.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List

from uaf.weather_atmosphere.core.contracts import (
    DiurnalKeyframe,
    WeatherSystemManifest,
)


class UE5WeatherExporter:
    """
    Serializes atmospheric configurations and generates automated Python scripts
    for Unreal Engine 5 Editor setup.
    """

    def __init__(self) -> None:
        pass

    def export_manifest(self, manifest: WeatherSystemManifest, output_dir: Path) -> Path:
        """Exports the complete weather system manifest as a structured JSON document."""
        output_dir.mkdir(parents=True, exist_ok=True)
        manifest_path = output_dir / "weather_system_manifest.json"
        with open(manifest_path, "w", encoding="utf-8") as f:
            json.dump(manifest.model_dump(), f, indent=2)
        return manifest_path

    def export_diurnal_curve_tracks(self, track: List[DiurnalKeyframe], output_dir: Path) -> Path:
        """
        Exports diurnal curve tracks formatted as float channels
        compatible with Unreal Engine CurveFloat and Sequencer Float Tracks.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        curve_file = output_dir / "diurnal_curve_tracks.json"

        channels = {
            "sun_elevation_deg": [{"time": kf.hour, "value": kf.sun_elevation_deg} for kf in track],
            "sun_azimuth_deg": [{"time": kf.hour, "value": kf.sun_azimuth_deg} for kf in track],
            "sun_lux": [{"time": kf.hour, "value": kf.sun_lux} for kf in track],
            "sun_kelvin": [{"time": kf.hour, "value": kf.sun_kelvin} for kf in track],
            "moon_elevation_deg": [{"time": kf.hour, "value": kf.moon_elevation_deg} for kf in track],
            "moon_azimuth_deg": [{"time": kf.hour, "value": kf.moon_azimuth_deg} for kf in track],
            "moon_lux": [{"time": kf.hour, "value": kf.moon_lux} for kf in track],
            "fog_density": [{"time": kf.hour, "value": kf.fog_density} for kf in track],
            "ev100": [{"time": kf.hour, "value": kf.ev100} for kf in track],
        }

        with open(curve_file, "w", encoding="utf-8") as f:
            json.dump({"total_keyframes": len(track), "channels": channels}, f, indent=2)

        return curve_file

    def generate_ue5_python_script(self, manifest: WeatherSystemManifest, output_dir: Path) -> Path:
        """
        Generates an automated Unreal Engine 5 Python script that configures
        SkyAtmosphere, DirectionalLights, SkyLight, ExponentialHeightFog, and VolumetricClouds.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        script_path = output_dir / "import_weather_presets.py"

        profile = manifest.atmosphere_profile
        sky = profile.sky_atmosphere
        fog = profile.height_fog
        cloud = profile.volumetric_clouds
        mpc = manifest.mpc_spec

        sun_intensity = mpc.scalar_parameters.get("Weather_SunLux", 80000.0)
        sun_color_tuple = mpc.vector_parameters.get("Weather_SunColor", (1.0, 1.0, 1.0, 6000.0))
        sun_kelvin = sun_color_tuple[3]
        moon_intensity = mpc.scalar_parameters.get("Weather_MoonLux", 0.25)

        script_code = (
            f"# Generated by AOE UAF-81.100 Weather & Atmosphere Pipeline\n"
            f"# Target Engine: Unreal Engine {manifest.ue5_version}\n"
            f"# Biome Profile: {profile.name} ({profile.biome.value})\n\n"
            f"import unreal\n\n"
            f"def configure_weather_system():\n"
            f"    unreal.log('Configuring UAF Volumetric Weather & Atmosphere: {profile.name}')\n"
            f"    editor_subsystem = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)\n"
            f"    world = editor_subsystem.get_current_level()\n\n"
            f"    # 1. Sky Atmosphere Component Setup\n"
            f"    sky_actors = editor_subsystem.get_all_level_actors_of_class(unreal.SkyAtmosphere)\n"
            f"    sky_actor = sky_actors[0] if sky_actors else editor_subsystem.spawn_actor_from_class(unreal.SkyAtmosphere, unreal.Vector(0, 0, 0))\n"
            f"    sky_comp = sky_actor.sky_atmosphere_component\n"
            f"    if sky_comp:\n"
            f"        sky_comp.set_editor_property('rayleigh_scattering', unreal.LinearColor({sky.rayleigh_scattering.r}, {sky.rayleigh_scattering.g}, {sky.rayleigh_scattering.b}))\n"
            f"        sky_comp.set_editor_property('rayleigh_exponential_distribution', {sky.rayleigh_scale_height_km})\n"
            f"        sky_comp.set_editor_property('mie_scattering_scale', {sky.mie_scattering})\n"
            f"        sky_comp.set_editor_property('mie_absorption_scale', {sky.mie_absorption})\n"
            f"        sky_comp.set_editor_property('mie_anisotropy', {sky.mie_anisotropy_g})\n"
            f"        sky_comp.set_editor_property('multi_scattering_factor', {sky.multi_scattering_factor})\n"
            f"        sky_comp.set_editor_property('other_absorption', unreal.LinearColor({sky.absorption_coefficient.r}, {sky.absorption_coefficient.g}, {sky.absorption_coefficient.b}))\n"
            f"        unreal.log('Configured SkyAtmosphere component.')\n\n"
            f"    # 2. Directional Light (Sun)\n"
            f"    sun_actors = [a for a in editor_subsystem.get_all_level_actors_of_class(unreal.DirectionalLight) if 'Sun' in a.get_actor_label()]\n"
            f"    sun_actor = sun_actors[0] if sun_actors else editor_subsystem.spawn_actor_from_class(unreal.DirectionalLight, unreal.Vector(0, 0, 500))\n"
            f"    sun_actor.set_actor_label('DirectionalLight_Sun')\n"
            f"    sun_comp = sun_actor.light_component\n"
            f"    if sun_comp:\n"
            f"        sun_comp.set_editor_property('intensity', {sun_intensity})\n"
            f"        sun_comp.set_editor_property('use_temperature', True)\n"
            f"        sun_comp.set_editor_property('temperature', {sun_kelvin})\n"
            f"        sun_comp.set_editor_property('atmosphere_sun_light', True)\n"
            f"        sun_comp.set_editor_property('atmosphere_sun_light_index', 0)\n"
            f"        unreal.log('Configured Sun DirectionalLight component.')\n\n"
            f"    # 3. Directional Light (Moon)\n"
            f"    moon_actors = [a for a in editor_subsystem.get_all_level_actors_of_class(unreal.DirectionalLight) if 'Moon' in a.get_actor_label()]\n"
            f"    moon_actor = moon_actors[0] if moon_actors else editor_subsystem.spawn_actor_from_class(unreal.DirectionalLight, unreal.Vector(0, 0, 450))\n"
            f"    moon_actor.set_actor_label('DirectionalLight_Moon')\n"
            f"    moon_comp = moon_actor.light_component\n"
            f"    if moon_comp:\n"
            f"        moon_comp.set_editor_property('intensity', {moon_intensity})\n"
            f"        moon_comp.set_editor_property('light_color', unreal.Color(165, 190, 230))\n"
            f"        moon_comp.set_editor_property('atmosphere_sun_light', True)\n"
            f"        moon_comp.set_editor_property('atmosphere_sun_light_index', 1)\n"
            f"        unreal.log('Configured Moon DirectionalLight component.')\n\n"
            f"    # 4. Exponential Height Fog Component\n"
            f"    fog_actors = editor_subsystem.get_all_level_actors_of_class(unreal.ExponentialHeightFog)\n"
            f"    fog_actor = fog_actors[0] if fog_actors else editor_subsystem.spawn_actor_from_class(unreal.ExponentialHeightFog, unreal.Vector(0, 0, 0))\n"
            f"    fog_comp = fog_actor.component\n"
            f"    if fog_comp:\n"
            f"        fog_comp.set_editor_property('fog_density', {fog.fog_density})\n"
            f"        fog_comp.set_editor_property('fog_height_falloff', {fog.fog_height_falloff})\n"
            f"        fog_comp.set_editor_property('fog_inscattering_color', unreal.LinearColor({fog.fog_inscattering_color.r}, {fog.fog_inscattering_color.g}, {fog.fog_inscattering_color.b}))\n"
            f"        fog_comp.set_editor_property('volumetric_fog', {str(fog.volumetric_fog_enabled)})\n"
            f"        fog_comp.set_editor_property('volumetric_fog_scattering_distribution', {fog.volumetric_fog_scattering_distribution})\n"
            f"        fog_comp.set_editor_property('volumetric_fog_extinction_scale', {fog.volumetric_fog_extinction_scale})\n"
            f"        fog_comp.set_editor_property('volumetric_fog_distance', {fog.volumetric_fog_distance_cm})\n"
            f"        unreal.log('Configured ExponentialHeightFog component.')\n\n"
            f"    # 5. Volumetric Cloud Component\n"
            f"    cloud_actors = editor_subsystem.get_all_level_actors_of_class(unreal.VolumetricCloud)\n"
            f"    cloud_actor = cloud_actors[0] if cloud_actors else editor_subsystem.spawn_actor_from_class(unreal.VolumetricCloud, unreal.Vector(0, 0, 0))\n"
            f"    cloud_comp = cloud_actor.volumetric_cloud_component\n"
            f"    if cloud_comp:\n"
            f"        cloud_comp.set_editor_property('layer_bottom_altitude', {cloud.layer_bottom_altitude_km})\n"
            f"        cloud_comp.set_editor_property('layer_height', {cloud.layer_height_km})\n"
            f"        cloud_comp.set_editor_property('tracing_max_distance', {cloud.tracing_max_distance_km})\n"
            f"        unreal.log('Configured VolumetricCloud component.')\n\n"
            f"    unreal.log('UAF Weather preset successfully applied to level.')\n\n"
            f"if __name__ == '__main__':\n"
            f"    configure_weather_system()\n"
        )

        with open(script_path, "w", encoding="utf-8") as f:
            f.write(script_code)

        return script_path

    def export_all(self, manifest: WeatherSystemManifest, output_dir: Path) -> Dict[str, Path]:
        """Convenience method exporting manifest, curve tracks, and UE5 automation script."""
        manifest_p = self.export_manifest(manifest, output_dir)
        curve_p = self.export_diurnal_curve_tracks(manifest.diurnal_track, output_dir)
        script_p = self.generate_ue5_python_script(manifest, output_dir)

        return {
            "manifest": manifest_p,
            "curves": curve_p,
            "script": script_p,
        }
