from enum import Enum

class RequirementType(str, Enum):
    STRUCTURAL = "STRUCTURAL"
    GEOMETRIC = "GEOMETRIC"
    MATERIAL = "MATERIAL"
    VISUAL = "VISUAL"
    FUNCTIONAL = "FUNCTIONAL"
    TECHNICAL = "TECHNICAL"
    STYLE = "STYLE"
    GAMEPLAY = "GAMEPLAY"
    PERFORMANCE = "PERFORMANCE"

class RequirementPriority(str, Enum):
    HARD = "HARD"
    IMPORTANT = "IMPORTANT"
    SOFT = "SOFT"

class RequirementSource(str, Enum):
    USER_EXPLICIT = "USER_EXPLICIT"
    USER_IMPLIED = "USER_IMPLIED"
    PROJECT_RULE = "PROJECT_RULE"
    REFERENCE_INFERRED = "REFERENCE_INFERRED"
    SYSTEM_DEFAULT = "SYSTEM_DEFAULT"

class AmbiguitySeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    BLOCKING = "BLOCKING"

class AmbiguityCategory(str, Enum):
    SEMANTIC = "SEMANTIC"
    GEOMETRIC = "GEOMETRIC"
    VISUAL = "VISUAL"
    FUNCTIONAL = "FUNCTIONAL"
    TECHNICAL = "TECHNICAL"
    REFERENCE = "REFERENCE"
    SCALE = "SCALE"
    STYLE = "STYLE"

class ReferenceScopeType(str, Enum):
    COPY_STRUCTURE = "COPY_STRUCTURE"
    COPY_STYLE = "COPY_STYLE"
    COPY_PROPORTIONS = "COPY_PROPORTIONS"
    COPY_MATERIALS = "COPY_MATERIALS"
    COPY_COMPOSITION = "COPY_COMPOSITION"
    INSPIRE_ONLY = "INSPIRE_ONLY"

class TaskCriticality(str, Enum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"
    BEST_EFFORT = "BEST_EFFORT"

class MilestoneType(str, Enum):
    FOUNDATION_READY = "FOUNDATION_READY"
    STRUCTURE_READY = "STRUCTURE_READY"
    ROOF_READY = "ROOF_READY"
    COMPONENTS_READY = "COMPONENTS_READY"
    MATERIALS_READY = "MATERIALS_READY"
    ASSET_READY = "ASSET_READY"

class PreflightStatus(str, Enum):
    READY = "READY"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    BLOCKING_CONFLICT = "BLOCKING_CONFLICT"
    UNSUPPORTED = "UNSUPPORTED"
