from enum import Enum

class RuntimeTaskStatus(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    PLANNING = "PLANNING"
    WAITING = "WAITING"
    READY = "READY"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    CORRECTING = "CORRECTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    RECOVERING = "RECOVERING"

class RuntimeTaskType(str, Enum):
    CREATE_ASSET = "CREATE_ASSET"
    MODIFY_ASSET = "MODIFY_ASSET"
    VALIDATE_ASSET = "VALIDATE_ASSET"
    ANALYZE_REFERENCE = "ANALYZE_REFERENCE"
    COMPARE_ASSET = "COMPARE_ASSET"
    CORRECT_ASSET = "CORRECT_ASSET"
    EXPORT_ASSET = "EXPORT_ASSET"
    IMPORT_ASSET = "IMPORT_ASSET"
    BUILD_COMPONENT = "BUILD_COMPONENT"
    REBUILD_COMPONENT = "REBUILD_COMPONENT"
    REVIEW_ASSET = "REVIEW_ASSET"
    DELETE_ASSET = "DELETE_ASSET"

class RuntimePriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"
    BACKGROUND = "BACKGROUND"

class RuntimeLockType(str, Enum):
    READ = "READ"
    WRITE = "WRITE"
    EXCLUSIVE = "EXCLUSIVE"

class AgentState(str, Enum):
    IDLE = "IDLE"
    BUSY = "BUSY"
    OFFLINE = "OFFLINE"
    ERROR = "ERROR"
    PAUSED = "PAUSED"

class ExecutionState(str, Enum):
    CREATED = "CREATED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMEOUT = "TIMEOUT"

class RuntimeEventType(str, Enum):
    TASK_CREATED = "TASK_CREATED"
    TASK_QUEUED = "TASK_QUEUED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_BLOCKED = "TASK_BLOCKED"
    STATE_CHANGED = "STATE_CHANGED"
    LOCK_ACQUIRED = "LOCK_ACQUIRED"
    LOCK_RELEASED = "LOCK_RELEASED"
    MCP_ERROR = "MCP_ERROR"
    TIMEOUT = "TIMEOUT"
    CHECKPOINT_CREATED = "CHECKPOINT_CREATED"
    ROLLBACK_COMPLETED = "ROLLBACK_COMPLETED"

class ConcurrencyMode(str, Enum):
    PARALLEL = "PARALLEL"
    SERIAL = "SERIAL"
    EXCLUSIVE = "EXCLUSIVE"
