from enum import Enum

class OperationStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    TIMEOUT = "TIMEOUT"
    ROLLED_BACK = "ROLLED_BACK"

class CapabilityCategory(str, Enum):
    SCENE = "SCENE"
    OBJECT = "OBJECT"
    GEOMETRY = "GEOMETRY"
    TRANSFORM = "TRANSFORM"
    MODIFIER = "MODIFIER"
    MATERIAL = "MATERIAL"
    TEXTURE = "TEXTURE"
    UV = "UV"
    COLLECTION = "COLLECTION"
    CAMERA = "CAMERA"
    LIGHT = "LIGHT"
    RENDER = "RENDER"
    PHYSICS = "PHYSICS"
    COLLISION = "COLLISION"
    LOD = "LOD"
    INSPECTION = "INSPECTION"
    FILE = "FILE"
    EXPORT = "EXPORT"
    IMPORT = "IMPORT"
    METADATA = "METADATA"

class ErrorTaxonomy(str, Enum):
    CONNECTION_ERROR = "CONNECTION_ERROR"
    AUTH_ERROR = "AUTH_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    EXECUTION_ERROR = "EXECUTION_ERROR"
    BLENDER_ERROR = "BLENDER_ERROR"
    TIMEOUT = "TIMEOUT"
    RESOURCE_ERROR = "RESOURCE_ERROR"
    STATE_ERROR = "STATE_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

class ErrorSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class CircuitState(str, Enum):
    CLOSED = "CLOSED"
    OPEN = "OPEN"
    HALF_OPEN = "HALF_OPEN"

class LockScope(str, Enum):
    SCENE = "SCENE"
    ASSET = "ASSET"
    OBJECT = "OBJECT"
    COLLECTION = "COLLECTION"
    MATERIAL = "MATERIAL"

class PermissionLevel(str, Enum):
    READ_ONLY = "READ_ONLY"
    SAFE_WRITE = "SAFE_WRITE"
    DESTRUCTIVE_WRITE = "DESTRUCTIVE_WRITE"
    ADMIN = "ADMIN"
