from enum import Enum

class FailureSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
    FATAL = "FATAL"

    @classmethod
    def from_context(cls, error_text: str, is_blocking: bool = False, is_critical_dimension: bool = False) -> "FailureSeverity":
        txt = error_text.upper()
        if "FATAL" in txt or "CORRUPTED" in txt:
            return cls.FATAL
        if is_blocking or is_critical_dimension or "CRITICAL" in txt or "CRASH" in txt:
            return cls.CRITICAL
        if "ERROR" in txt or "FAIL" in txt or "DENIED" in txt:
            return cls.ERROR
        if "WARNING" in txt or "DEPRECATED" in txt:
            return cls.WARNING
        return cls.INFO

class FailureStatus(str, Enum):
    DETECTED = "DETECTED"
    ANALYZING = "ANALYZING"
    DIAGNOSED = "DIAGNOSED"
    CORRECTION_PLANNED = "CORRECTION_PLANNED"
    CORRECTING = "CORRECTING"
    VERIFYING = "VERIFYING"
    RESOLVED = "RESOLVED"
    PARTIALLY_RESOLVED = "PARTIALLY_RESOLVED"
    UNRESOLVED = "UNRESOLVED"
    ESCALATED = "ESCALATED"

class FailureType(str, Enum):
    SPECIFICATION_ERROR = "SPECIFICATION_ERROR"
    INPUT_ERROR = "INPUT_ERROR"
    REFERENCE_ERROR = "REFERENCE_ERROR"

    STRATEGY_ERROR = "STRATEGY_ERROR"

    GEOMETRY_ERROR = "GEOMETRY_ERROR"
    TOPOLOGY_ERROR = "TOPOLOGY_ERROR"
    SCALE_ERROR = "SCALE_ERROR"
    TRANSFORM_ERROR = "TRANSFORM_ERROR"
    AXIS_ERROR = "AXIS_ERROR"

    MATERIAL_ERROR = "MATERIAL_ERROR"
    SHADER_ERROR = "SHADER_ERROR"
    UV_ERROR = "UV_ERROR"
    TEXTURE_ERROR = "TEXTURE_ERROR"

    LOD_ERROR = "LOD_ERROR"
    COLLISION_ERROR = "COLLISION_ERROR"

    BLENDER_EXECUTION_ERROR = "BLENDER_EXECUTION_ERROR"
    BLENDER_CRASH = "BLENDER_CRASH"
    BLENDER_TIMEOUT = "BLENDER_TIMEOUT"

    CAPABILITY_ERROR = "CAPABILITY_ERROR"
    TOOL_ERROR = "TOOL_ERROR"
    GOVERNANCE_ERROR = "GOVERNANCE_ERROR"
    PERMISSION_ERROR = "PERMISSION_ERROR"

    RESOURCE_ERROR = "RESOURCE_ERROR"
    LOCK_ERROR = "LOCK_ERROR"

    CHECKPOINT_ERROR = "CHECKPOINT_ERROR"
    PERSISTENCE_ERROR = "PERSISTENCE_ERROR"
    RECOVERY_ERROR = "RECOVERY_ERROR"

    EXPORT_ERROR = "EXPORT_ERROR"
    PACKAGING_ERROR = "PACKAGING_ERROR"

    UNREAL_READINESS_ERROR = "UNREAL_READINESS_ERROR"

    VALIDATION_ERROR = "VALIDATION_ERROR"
    BENCHMARK_ERROR = "BENCHMARK_ERROR"
    REGRESSION_ERROR = "REGRESSION_ERROR"

    DUPLICATION_ERROR = "DUPLICATION_ERROR"
    IDEMPOTENCY_ERROR = "IDEMPOTENCY_ERROR"

    TIMEOUT_ERROR = "TIMEOUT_ERROR"
    NETWORK_ERROR = "NETWORK_ERROR"

    UNKNOWN_ERROR = "UNKNOWN_ERROR"

class RecoveryActionType(str, Enum):
    RETRY = "RETRY"
    RESUME = "RESUME"
    ROLLBACK = "ROLLBACK"
    REGENERATE_COMPONENT = "REGENERATE_COMPONENT"
    REGENERATE_SUBTREE = "REGENERATE_SUBTREE"
    REGENERATE_ASSET = "REGENERATE_ASSET"
    REBUILD_MATERIAL = "REBUILD_MATERIAL"
    REBUILD_UV = "REBUILD_UV"
    REBUILD_LODS = "REBUILD_LODS"
    REBUILD_COLLISION = "REBUILD_COLLISION"
    REEXPORT = "REEXPORT"
    REPACKAGE = "REPACKAGE"
    ABORT = "ABORT"
    REQUEST_HUMAN = "REQUEST_HUMAN"
