from enum import Enum

class JobType(str, Enum):
    ASSET_GENERATION = "ASSET_GENERATION"
    ASSET_MODIFICATION = "ASSET_MODIFICATION"
    ASSET_VALIDATION = "ASSET_VALIDATION"
    ASSET_OPTIMIZATION = "ASSET_OPTIMIZATION"
    ENGINE_PREPARATION = "ENGINE_PREPARATION"
    PACKAGE_BUILD = "PACKAGE_BUILD"
    PACKAGE_DELIVERY = "PACKAGE_DELIVERY"
    FULL_PIPELINE = "FULL_PIPELINE"

class JobState(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    PAUSING = "PAUSING"
    PAUSED = "PAUSED"
    RESUMING = "RESUMING"
    RECOVERING = "RECOVERING"
    WAITING_FOR_RESOURCE = "WAITING_FOR_RESOURCE"
    WAITING_FOR_CAPABILITY = "WAITING_FOR_CAPABILITY"
    WAITING_FOR_RETRY = "WAITING_FOR_RETRY"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"
    COMPLETING = "COMPLETING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    ABANDONED = "ABANDONED"

class JobPriority(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    NORMAL = "NORMAL"
    LOW = "LOW"
    BACKGROUND = "BACKGROUND"

class BackoffStrategy(str, Enum):
    FIXED = "FIXED"
    LINEAR = "LINEAR"
    EXPONENTIAL = "EXPONENTIAL"
    EXPONENTIAL_WITH_JITTER = "EXPONENTIAL_WITH_JITTER"

class ErrorCategory(str, Enum):
    USER_ERROR = "USER_ERROR"
    ASSET_ERROR = "ASSET_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    CAPABILITY_ERROR = "CAPABILITY_ERROR"
    BLENDER_ERROR = "BLENDER_ERROR"
    ENGINE_ERROR = "ENGINE_ERROR"
    NETWORK_ERROR = "NETWORK_ERROR"
    RESOURCE_ERROR = "RESOURCE_ERROR"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

class RecoveryAction(str, Enum):
    RETRY = "RETRY"
    RESUME = "RESUME"
    ROLLBACK = "ROLLBACK"
    RESTART_PHASE = "RESTART_PHASE"
    RESTART_JOB = "RESTART_JOB"
    WAIT = "WAIT"
    CANCEL = "CANCEL"
    FAIL = "FAIL"
