"""
Universal Runtime Animation World System Module (UAF-81.80).
Authoritative public API exports for skeletal animation, morph targets,
blend trees, state machines, layers, IK solvers, constraints, root motion,
ragdoll transitions, animation events, retargeting, LOD, determinism,
snapshots, validation, and Unreal Engine 5 packaging.
"""

from .models.definition import (
    AnimConditionOperator,
    AnimEvent,
    AnimEventType,
    AnimationClip,
    AnimationConstraint,
    AnimationCurve,
    AnimationInstance,
    AnimationLayer,
    AnimationLODLevel,
    AnimationLODSettings,
    AnimationSnapshot,
    AnimState,
    AnimStateMachine,
    AnimationTick,
    AnimTransition,
    AnimTransitionCondition,
    AnimationWorld,
    AnimationWorldSettings,
    AnimationWorldState,
    BlendTree,
    BlendTreeNode,
    BlendTreeNodeType,
    BoneMask,
    BoneNode,
    ConstraintType,
    IKSolver,
    IKSolverType,
    InterpolationType,
    Keyframe,
    LayerBlendMode,
    Pose,
    RagdollProfile,
    RagdollState,
    RetargetBoneMapping,
    RetargetProfile,
    RootMotionDelta,
    RootMotionMode,
    SkeletonHierarchy,
    Transform3D,
    combine_transforms,
    copy_dict_deterministic,
    quat_multiply,
    quat_rotate_vec3,
    quat_slerp,
    vec3_add,
    vec3_dot,
    vec3_length,
    vec3_lerp,
    vec3_normalize,
    vec3_scale,
    vec3_sub,
)

from .engine.universal_runtime_animation_fabricator import (
    UniversalRuntimeAnimationFabricator,
)

from .validation.universal_runtime_animation_validator import (
    AnimationValidationIssue,
    UniversalRuntimeAnimationValidator,
)

from .package.universal_runtime_animation_packager import (
    UniversalRuntimeAnimationPackager,
)

__all__ = [
    "AnimConditionOperator",
    "AnimEvent",
    "AnimEventType",
    "AnimationClip",
    "AnimationConstraint",
    "AnimationCurve",
    "AnimationInstance",
    "AnimationLayer",
    "AnimationLODLevel",
    "AnimationLODSettings",
    "AnimationSnapshot",
    "AnimState",
    "AnimStateMachine",
    "AnimationTick",
    "AnimTransition",
    "AnimTransitionCondition",
    "AnimationWorld",
    "AnimationWorldSettings",
    "AnimationWorldState",
    "BlendTree",
    "BlendTreeNode",
    "BlendTreeNodeType",
    "BoneMask",
    "BoneNode",
    "ConstraintType",
    "IKSolver",
    "IKSolverType",
    "InterpolationType",
    "Keyframe",
    "LayerBlendMode",
    "Pose",
    "RagdollProfile",
    "RagdollState",
    "RetargetBoneMapping",
    "RetargetProfile",
    "RootMotionDelta",
    "RootMotionMode",
    "SkeletonHierarchy",
    "Transform3D",
    "combine_transforms",
    "copy_dict_deterministic",
    "quat_multiply",
    "quat_rotate_vec3",
    "quat_slerp",
    "vec3_add",
    "vec3_dot",
    "vec3_length",
    "vec3_lerp",
    "vec3_normalize",
    "vec3_scale",
    "vec3_sub",
    "UniversalRuntimeAnimationFabricator",
    "AnimationValidationIssue",
    "UniversalRuntimeAnimationValidator",
    "UniversalRuntimeAnimationPackager",
]
