from enum import Enum

class GenerationStrategyType(str, Enum):
    PRIMITIVE_COMPOSITION = "PRIMITIVE_COMPOSITION"
    SCRIPTED_MODELING = "SCRIPTED_MODELING"
    MODIFIER_MODELING = "MODIFIER_MODELING"
    GEOMETRY_NODES = "GEOMETRY_NODES"
    PROCEDURAL_GENERATION = "PROCEDURAL_GENERATION"
    EXISTING_ASSET_MODIFICATION = "EXISTING_ASSET_MODIFICATION"
    KITBASH = "KITBASH"
    COMPONENT_ASSEMBLY = "COMPONENT_ASSEMBLY"
    IMAGE_ASSISTED = "IMAGE_ASSISTED"
    MANUAL_AGENT_MODELING = "MANUAL_AGENT_MODELING"
    HYBRID = "HYBRID"

class AssetComplexityLevel(str, Enum):
    SIMPLE = "SIMPLE"
    MEDIUM = "MEDIUM"
    COMPLEX = "COMPLEX"
    HIGHLY_MODULAR = "HIGHLY_MODULAR"
    ORGANIC = "ORGANIC"

class FailureCategory(str, Enum):
    TOPOLOGY_ERROR = "TOPOLOGY_ERROR"
    STRUCTURAL_MISMATCH = "STRUCTURAL_MISMATCH"
    INFRASTRUCTURE_TIMEOUT = "INFRASTRUCTURE_TIMEOUT"
    CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION"

class StageType(str, Enum):
    BLOCKOUT = "BLOCKOUT"
    PRIMARY_GEOMETRY = "PRIMARY_GEOMETRY"
    SECONDARY_COMPONENTS = "SECONDARY_COMPONENTS"
    MATERIALS = "MATERIALS"
    TECHNICAL_SETUP = "TECHNICAL_SETUP"
    VALIDATION = "VALIDATION"
