from enum import Enum

class FailureStatus(str, Enum):
    DETECTED = "DETECTED"
    ANALYZING = "ANALYZING"
    DIAGNOSED = "DIAGNOSED"
    CORRECTION_PLANNED = "CORRECTION_PLANNED"
    CORRECTING = "CORRECTING"
    VERIFYING = "VERIFYING"
    RESOLVED = "RESOLVED"
    PARTIALLY_RESOLVED = "PARTIALLY_RESOLVED"
    UNRESOLVED = "UNRESOLVED"
    ESCALATED = "ESCALATED"

class FailureType(str, Enum):
    INPUT_INVALID = "INPUT_INVALID"
    SPECIFICATION_INVALID = "SPECIFICATION_INVALID"
    REFERENCE_INVALID = "REFERENCE_INVALID"

    GEOMETRY_ERROR = "GEOMETRY_ERROR"
    TOPOLOGY_ERROR = "TOPOLOGY_ERROR"
    TRANSFORM_ERROR = "TRANSFORM_ERROR"
    SCALE_ERROR = "SCALE_ERROR"
    AXIS_ERROR = "AXIS_ERROR"
    PIVOT_ERROR = "PIVOT_ERROR"

    MATERIAL_ERROR = "MATERIAL_ERROR"
    TEXTURE_ERROR = "TEXTURE_ERROR"
    UV_ERROR = "UV_ERROR"
    SHADER_ERROR = "SHADER_ERROR"

    LOD_ERROR = "LOD_ERROR"
    COLLISION_ERROR = "COLLISION_ERROR"
    NANITE_ERROR = "NANITE_ERROR"

    BLENDER_EXECUTION_ERROR = "BLENDER_EXECUTION_ERROR"
    BLENDER_CRASH = "BLENDER_CRASH"
    BLENDER_STATE_ERROR = "BLENDER_STATE_ERROR"

    EXPORT_ERROR = "EXPORT_ERROR"
    PACKAGING_ERROR = "PACKAGING_ERROR"
    UNREAL_READINESS_ERROR = "UNREAL_READINESS_ERROR"

    GOVERNANCE_DENIED = "GOVERNANCE_DENIED"
    RESOURCE_LOCK_ERROR = "RESOURCE_LOCK_ERROR"
    PERMISSION_ERROR = "PERMISSION_ERROR"

    CHECKPOINT_ERROR = "CHECKPOINT_ERROR"
    RECOVERY_ERROR = "RECOVERY_ERROR"

    EVALUATION_FAILURE = "EVALUATION_FAILURE"
    REGRESSION_FAILURE = "REGRESSION_FAILURE"
    GOLDEN_INTEGRITY_FAILURE = "GOLDEN_INTEGRITY_FAILURE"

    TIMEOUT = "TIMEOUT"
    RESOURCE_EXHAUSTION = "RESOURCE_EXHAUSTION"
    DEPENDENCY_FAILURE = "DEPENDENCY_FAILURE"
    UNKNOWN = "UNKNOWN"

class ResolutionStatus(str, Enum):
    RESOLVED = "RESOLVED"
    PARTIALLY_RESOLVED = "PARTIALLY_RESOLVED"
    UNRESOLVED = "UNRESOLVED"
    ESCALATED = "ESCALATED"
