from enum import Enum

class ToolCategory(str, Enum):
    DISCOVERY = "DISCOVERY"
    PLANNING = "PLANNING"
    ASSET = "ASSET"
    INSPECTION = "INSPECTION"
    VALIDATION = "VALIDATION"
    CORRECTION = "CORRECTION"
    EXECUTION = "EXECUTION"
    RECOVERY = "RECOVERY"
    EXPORT = "EXPORT"

class PermissionLevel(str, Enum):
    READ = "READ"
    PLAN = "PLAN"
    MODIFY = "MODIFY"
    DELETE = "DELETE"
    EXPORT = "EXPORT"
    ADMIN = "ADMIN"

class AgentOperationStatus(str, Enum):
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    WAITING = "WAITING"
    REQUIRES_APPROVAL = "REQUIRES_APPROVAL"
    REQUIRES_CLARIFICATION = "REQUIRES_CLARIFICATION"

class AgentDecision(str, Enum):
    ACCEPT = "ACCEPT"
    CORRECT = "CORRECT"
    REPLAN = "REPLAN"
    ASK = "ASK"
    STOP = "STOP"

class AgentAssetStatus(str, Enum):
    PLANNED = "PLANNED"
    GENERATING = "GENERATING"
    VALIDATING = "VALIDATING"
    VALID = "VALID"
    INVALID = "INVALID"
    DEGRADED = "DEGRADED"
    FAILED = "FAILED"
    LOCKED = "LOCKED"

class AgentComponentStatus(str, Enum):
    CLEAN = "CLEAN"
    DIRTY = "DIRTY"
    GENERATING = "GENERATING"
    VALID = "VALID"
    INVALID = "INVALID"
    FAILED = "FAILED"

class AgentErrorCode(str, Enum):
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    INVALID_SPECIFICATION = "INVALID_SPECIFICATION"
    UNSUPPORTED_ASSET = "UNSUPPORTED_ASSET"
    UNSUPPORTED_GENERATOR = "UNSUPPORTED_GENERATOR"
    CONSTRAINT_FAILED = "CONSTRAINT_FAILED"
    PLAN_INVALID = "PLAN_INVALID"
    PLAN_STALE = "PLAN_STALE"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    MCP_ERROR = "MCP_ERROR"
    BLENDER_ERROR = "BLENDER_ERROR"
    STATE_CONFLICT = "STATE_CONFLICT"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    NO_PROGRESS = "NO_PROGRESS"
    LOOP_DETECTED = "LOOP_DETECTED"
    TIMEOUT = "TIMEOUT"
    REQUIRES_APPROVAL = "REQUIRES_APPROVAL"
    REQUIRES_CLARIFICATION = "REQUIRES_CLARIFICATION"
