from enum import Enum

class EvaluationMode(str, Enum):
    FAST = "FAST"
    STANDARD = "STANDARD"
    DEEP = "DEEP"

class VisualDiagnosisType(str, Enum):
    TOO_WIDE = "TOO_WIDE"
    TOO_NARROW = "TOO_NARROW"
    TOO_TALL = "TOO_TALL"
    TOO_SHORT = "TOO_SHORT"
    ROOF_TOO_HIGH = "ROOF_TOO_HIGH"
    ROOF_TOO_FLAT = "ROOF_TOO_FLAT"
    WINDOW_TOO_SMALL = "WINDOW_TOO_SMALL"
    WINDOW_TOO_LARGE = "WINDOW_TOO_LARGE"
    COMPONENT_MISSING = "COMPONENT_MISSING"
    UNEXPECTED_COMPONENT = "UNEXPECTED_COMPONENT"
    SILHOUETTE_MISMATCH = "SILHOUETTE_MISMATCH"
    MATERIAL_MISMATCH = "MATERIAL_MISMATCH"
    STYLE_MISMATCH = "STYLE_MISMATCH"

class CriticDecisionType(str, Enum):
    ACCEPT = "ACCEPT"
    ACCEPT_WITH_WARNINGS = "ACCEPT_WITH_WARNINGS"
    CORRECT = "CORRECT"
    REPLAN = "REPLAN"
    BLOCK = "BLOCK"

class ReferenceRole(str, Enum):
    STRUCTURE = "STRUCTURE"
    SILHOUETTE = "SILHOUETTE"
    PROPORTION = "PROPORTION"
    MATERIAL = "MATERIAL"
    STYLE = "STYLE"
    COMPOSITION = "COMPOSITION"

class EvaluationStage(str, Enum):
    STRUCTURAL = "STRUCTURAL"
    SILHOUETTE = "SILHOUETTE"
    COMPONENTS = "COMPONENTS"
    MATERIALS = "MATERIALS"
    STYLE = "STYLE"

class ColorSpaceType(str, Enum):
    RGB = "RGB"
    LAB = "LAB"
    HSV = "HSV"
