from enum import Enum

class CorrectionStatus(str, Enum):
    PENDING = "PENDING"
    VALIDATING = "VALIDATING"
    READY = "READY"
    EXECUTING = "EXECUTING"
    VALIDATING_RESULT = "VALIDATING_RESULT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    ROLLED_BACK = "ROLLED_BACK"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"

class ActionAuthorization(str, Enum):
    SAFE = "SAFE"
    CONTROLLED = "CONTROLLED"
    RISKY = "RISKY"
    BLOCKED = "BLOCKED"

class RollbackStatus(str, Enum):
    NONE = "NONE"
    ROLLBACK_SUCCESS = "ROLLBACK_SUCCESS"
    ROLLBACK_MISMATCH = "ROLLBACK_MISMATCH"
    ROLLBACK_FAILED = "ROLLBACK_FAILED"

class CorrectionStrategyType(str, Enum):
    DIRECT = "DIRECT"
    GRADUAL = "GRADUAL"
    LOCAL = "LOCAL"
    GLOBAL = "GLOBAL"
    PARAMETER_SEARCH = "PARAMETER_SEARCH"

class RegressionSeverity(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class OperationType(str, Enum):
    PARAMETER_UPDATE = "PARAMETER_UPDATE"
    TRANSFORM_UPDATE = "TRANSFORM_UPDATE"
    COMPONENT_REPOSITION = "COMPONENT_REPOSITION"
    COMPONENT_RESIZE = "COMPONENT_RESIZE"
    MATERIAL_PARAMETER_UPDATE = "MATERIAL_PARAMETER_UPDATE"
    UV_PARAMETER_UPDATE = "UV_PARAMETER_UPDATE"
    LOD_PARAMETER_UPDATE = "LOD_PARAMETER_UPDATE"
    TOPOLOGY_OPERATION = "TOPOLOGY_OPERATION"
    LOCAL_REGENERATION = "LOCAL_REGENERATION"
    ASSET_REGENERATION = "ASSET_REGENERATION"
