from enum import Enum

class TargetPlatform(str, Enum):
    PC = "PC"
    CONSOLE = "CONSOLE"
    MOBILE = "MOBILE"
    VR = "VR"
    VR_HIGH_END = "VR_HIGH_END"
    CINEMATIC = "CINEMATIC"
    GENERIC_REALTIME = "GENERIC_REALTIME"

class TargetEngine(str, Enum):
    UNREAL_ENGINE = "UNREAL_ENGINE"
    GENERIC_REALTIME = "GENERIC_REALTIME"

class OptimizationObjective(str, Enum):
    QUALITY_FIRST = "QUALITY_FIRST"
    BALANCED = "BALANCED"
    PERFORMANCE_FIRST = "PERFORMANCE_FIRST"
    MEMORY_FIRST = "MEMORY_FIRST"
    MOBILE_FIRST = "MOBILE_FIRST"
    CINEMATIC_REALTIME = "CINEMATIC_REALTIME"

class NanitePolicy(str, Enum):
    NANITE_REQUIRED = "NANITE_REQUIRED"
    NANITE_PREFERRED = "NANITE_PREFERRED"
    NANITE_OPTIONAL = "NANITE_OPTIONAL"
    NANITE_DISABLED = "NANITE_DISABLED"

class CollisionPolicy(str, Enum):
    SIMPLE_ONLY = "SIMPLE_ONLY"
    COMPLEX_ALLOWED = "COMPLEX_ALLOWED"
    CUSTOM_UCX = "CUSTOM_UCX"
    CONVEX_HULL = "CONVEX_HULL"

class SessionStatus(str, Enum):
    CREATED = "CREATED"
    ANALYZING = "ANALYZING"
    GENERATING = "GENERATING"
    EVALUATING = "EVALUATING"
    SELECTING = "SELECTING"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class StrategyType(str, Enum):
    MESH_SIMPLIFICATION = "MESH_SIMPLIFICATION"
    VERTEX_OPTIMIZATION = "VERTEX_OPTIMIZATION"
    MATERIAL_OPTIMIZATION = "MATERIAL_OPTIMIZATION"
    TEXTURE_OPTIMIZATION = "TEXTURE_OPTIMIZATION"
    UV_OPTIMIZATION = "UV_OPTIMIZATION"
    LOD_GENERATION = "LOD_GENERATION"
    NANITE_PREPARATION = "NANITE_PREPARATION"
    COLLISION_OPTIMIZATION = "COLLISION_OPTIMIZATION"
    NORMAL_OPTIMIZATION = "NORMAL_OPTIMIZATION"
    MODIFIER_OPTIMIZATION = "MODIFIER_OPTIMIZATION"
    INSTANCE_OPTIMIZATION = "INSTANCE_OPTIMIZATION"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class BudgetStatus(str, Enum):
    UNDER_TARGET = "UNDER_TARGET"
    ON_TARGET = "ON_TARGET"
    OVER_TARGET = "OVER_TARGET"
    CRITICAL_OVERAGE = "CRITICAL_OVERAGE"
