from .api.engine import AssetOrchestrationEngine
from .planning.planner import ChangeBudget
from .planning.scope_manager import ScopeSpec
from .planning.constraint_engine import ConstraintEngine, NumericConstraint
from .intent.intent_types import NormalizedIntent, IntentType, ModifierType
from .intent.target_resolver import TargetResolver as LegacyTargetResolver
from .intent.confidence_system import ConfidenceSystem, ConfidenceAction, ConfidenceThresholds
from .intent.clarification_manager import ClarificationManager
from .specification.normalizer import UnitNormalizer
from .specification.asset_schema import (
    AssetSpecification, AssetCategory, PrimitiveType as LegacyPrimitiveType, SymmetryType,
    DimensionsSpec, ComponentSpec, StyleSpec as LegacyStyleSpec, BudgetSpec, AssetStatus as LegacyAssetStatus
)
from .geometry import (
    GeometryEngine, GeometryContext, IGeometryGenerator, GeneratedGeometry,
    PrimitiveGenerator, ProfileGenerator, GeometryGeneratorRegistry,
    GeometricComponent, ComponentRegistry, ComponentDependencies,
    DirtyTracker, DependencyAnalyzer, RebuildPlanner, ParameterSpec, ParameterType,
    GeometryValidator, DimensionValidator, TopologyValidator
)
from .visual import (
    VisualAPI, VisualFeedbackLoop, QualityGate, QualityStatus, QualityProfile,
    ThresholdManager, ReportGenerator, VisualReference, ReferenceType, ReferenceView,
    DifferenceDetector, DifferenceRecord, DifferenceType,
    CorrectionMapper, CorrectionProposal, SilhouetteComparator, DimensionComparator,
    RenderCapture, CameraNormalizer, ViewOrientation
)
from .appearance import (
    AppearanceAPI, AppearanceEngine, AppearanceContext, MaterialDefinition,
    PBRParameters, ShaderType, MaterialInstance, MaterialRegistry,
    TextureMetadata, TextureUsage, ColorSpace, TextureRegistry,
    ColorSpaceValidator, UVSet, UVMethod, UVProjection, UVValidator,
    MaterialAssignmentManager, AppearanceValidator, AppearanceDiff
)
from .game_ready import (
    GameReadyAPI, GameReadyEngine, GameReadyManifest, ApprovalValidator,
    NamingValidator, BudgetValidator, GameReadyLODProfile, LODLevelConfig,
    LODGenerator, GeneratedLODLevel, LODValidator, CollisionProfile,
    CollisionType, CollisionGenerator, CollisionHull, CollisionValidator,
    PivotManager, PivotType, ScaleManager, SocketManager,
    AssetMapper, UnrealAssetMapping, UnrealImportSettings
)
from .unreal import (
    UnrealAPI, UnrealEngine, UnrealAssetRegistry, UnrealAssetReference,
    UnrealActor, ActorRegistry, ActorTransform, SceneGraph, SceneSnapshot as UnrealSceneSnapshot,
    SpatialSolver, SpatialRelation, SceneDiff, PropertyChange, UnrealDependencyGraph
)
from .gameplay import (
    GameplayAPI, GameplayEngine, CapabilityType, CapabilityDefinition,
    CapabilityInstance, CapabilityRegistry, CapabilityResolver,
    InteractionSystem as LegacyInteractionSystem, InteractionDefinition as LegacyInteractionDefinition,
    GameplayCondition, GameplayAction, EventBus, GameplayEvent, StateMachine, WeaponData,
    ActorGameplayData, GameplayDiff
)
from .ai_planning import (
    AIPlanningAPI, AIRequest, RequestSource, AIRequestGateway, AdvancedIntentParser,
    PlanningIntentType, ParsedIntent, GapAnalyzer, GoalSpec, StateGap,
    TaskGraph, PlannedTask, TaskStatus, PlanOptimizer, DestructiveOperationGuard,
    RiskLevel as LegacyRiskLevel, PlanExecutor
)
from .visual_intelligence import (
    VisualIntelligenceAPI, VisualGoalSpec, ProportionAnalyzer, ComponentDetector,
    QualityScorer, VerificationReport, QualityWeights, VisualCorrectionPlanner
)
from .correction_execution import (
    CorrectionExecutionAPI, CorrectionPlan as LegacyCorrectionPlan, CorrectionOperation, OperationType,
    RegisteredComponent, OperationRegistry, RiskAnalyzer as LegacyRiskAnalyzer, OperationPermissionManager,
    ExecutionMode, SnapshotManager, AssetSnapshot, MutationTransaction,
    TransactionState, IBlenderProvider, MockBlenderProvider, DependencyResolver,
    MutationValidator, MutationExecutor
)
from .memory import (
    AssetMemoryAPI, FailureRecord, CorrectionRecord, StrategyRecord,
    FailureCategory, FailureTypeRegistry, SQLiteMemoryStore,
    SimilarityEngine, ConfidenceEngine, PatternDetector, MemoryRanker,
    GenerationAdvisor
)
from .autonomous_decision import (
    AutonomousDecisionAPI, DecisionState, DecisionStateEnum, GoalEvaluator,
    UtilityCalculator, ProgressEvaluator, ProgressClassification, BudgetController,
    CorrectionBudget, LoopController, StoppingController, ActionPlan,
    ActionPlanner, DecisionLogger, DecisionLogEntry, DecisionEngine
)
from .spec_compiler import (
    SpecificationCompilerAPI, AssetSpec, AttributeProvenance, DimensionValue,
    ComponentSpecEntry, ConstraintEntry, StyleSpecEntry, AssetOntology,
    UnitResolver, IntentExtractor, ConstraintExtractor, RelationExtractor,
    ConflictDetector, AmbiguityDetector, SpecificationPatcher, SpecificationDriftDetector,
    SpecificationCompiler
)
from .procedural_templates import (
    ProceduralTemplatesAPI, IAssetTemplate, SwordTemplate, TemplateRegistry,
    ConstructionPlan, ConstructionOperation, ConstructionDependencyGraph,
    ProceduralBuilder, PartialRebuilder, ParameterResolver, ParameterConstraintSolver
)
from .visual_critic import (
    VisualCriticAPI, EvaluationContext, CriticReport, CriticIssue, CriticStatus,
    IssueSeverity, AIVisualCritic, ParameterMappingEngine, ParameterPatchGenerator,
    ParameterPatch, VisualEvaluationEngine
)
from .asset_memory_system import (
    AssetMemorySystemAPI, AssetRecord, AssetVersionRecord, PatternRecord as LegacyPatternRecord,
    PatternEvidence, EvaluationRecord, FailureMemoryRecord as LegacyFailureRecord, AuditEvent,
    VersionManager, SQLiteAssetStore, KnowledgeExtractor, PatternPromoter,
    NegativeKnowledgeEngine, MemoryQueryEngine, ReuseStrategyDecision,
    PatternStatus, PatternScope as LegacyPatternScope, ReproductionStatus
)
from .asset_library import (
    AssetLibraryAPI, BuildIntent, ResolvedBuildSpec, VariantDefinition,
    PresetDefinition, ManifestHasher, SocketSystem, LibrarySearchEngine,
    ParameterHierarchySolver, LibraryConstraintEngine
)
from .scene_orchestration import (
    SceneOrchestrationAPI, SceneIntent, ScenePlan, SceneNode, SceneSummary,
    ProxyBounds, ProxyScene, LayoutSolver, CheckpointManager as LegacyCheckpointManager,
    BatchSceneBuilder, SceneReconciler, SceneStatus, BuildStage as LegacyBuildStage,
    NodeDirtyState, ReconciliationStatus
)
from .visual_evaluation_qa import (
    VisualEvaluationQAAPI, EvaluationDimension, EvaluationSeverity, RepairScope,
    EvaluationFailure, RepairCandidate, RepairPlan, EvaluationReport,
    ExpectedVisualProfile, ProfileRegistry, EvaluationProfile,
    MultiDimensionEvaluator, RepairPlanner, RegressionDetector,
    OscillationDetector, ClosedLoopOptimizer
)
from .intent_compiler import (
    IntentCompilerAPI, NaturalLanguageRequest, RequestContext, BuildSpecification,
    BuildAuthorization, Requirement, IntentConstraint, IntentTrace,
    SpecStatus, RequirementPriority, RequirementStatus,
    AmbiguitySeverity, ActionType, UnitNormalizer as IntentUnitNormalizer
)
from .tool_governance import (
    ToolGovernanceAPI, ToolRisk, PermissionType, ActionScope, ActionLifecycle,
    ToolDefinition, ActionProposal, ExecutionBudget, NormalizedToolResult,
    StateSnapshot, AgentPermissionProfile, PermissionManager, ActionValidator,
    DuplicateActionDetector, ExecutionLoopGuard, PostActionValidator,
    RollbackManager, AIToolGateway
)
from .asset_reuse_engine import (
    AssetReuseEngineAPI, AssetState, ReuseDecisionType, AssetMetadata,
    LibraryAssetRecord, AssetVariant, ReuseDecision, AssetSearchQuery,
    SearchResultCandidate, FingerprintMatcher, AssetRetrievalEngine,
    VariantManager, InstancingEngine, ReuseDecisionMaker
)
from .parametric_builder import (
    ParametricBuilderAPI, AssetType as ParametricAssetType, BuildStage, BuildState,
    ParameterDefinition, ParametricAssetDefinition, ParameterChange, BuildResult,
    ParameterDependencyGraph, ParameterFormulaEngine,
    ParameterConstraintSolver as ParametricConstraintSolver, ParameterTransactionManager,
    GeometryCache, PartialBuilder, MedievalHouseBuilder
)
from .visual_reference_matching import (
    VisualReferenceAPI, LandmarkFeature, ProportionFeature, GeometricDiscrepancy,
    ReferenceProfile, ErrorMap, FeatureExtractor, GeometricMatcher
)
from .autonomous_correction_loop import (
    AutonomousCorrectionLoopAPI, LoopStatus, CorrectionStep, CorrectionPlan,
    LoopIterationRecord, AutonomousLoopResult, CorrectionPlanner,
    FeedbackLoopController
)
from .learned_construction_patterns import (
    LearnedPatternsAPI, PatternState, MemorySource, ProblemSignature, TrustLevel,
    PatternScope, MemoryEntry, AssetMemoryRecord, BuildMemoryRecord,
    CorrectionMemoryRecord, PatternRecord, FailureMemoryRecord,
    ReferenceMemoryRecord, ProjectMemoryRecord, RootCauseEngine,
    PatternMatcher, PatternLifecycleManager, MemoryStore
)
from .composite_scene_system import (
    CompositeSceneAPI, SceneType, ConstraintPriority, SpatialRelationType,
    PlanningStage, SceneState as CompositeSceneState, LockState, CollisionSeverity,
    SocketDefinition, AssetInstance, SceneArea, SceneRegion, SceneBudget,
    SceneSpecification, SceneBuildPlan, SceneDiagnosticReport, SceneManifest,
    CompositionGraph, GraphNode, GraphEdge, SocketMatcher,
    SceneCollisionValidator, SpatialConstraintSolver as SceneSpatialSolver,
    HierarchicalPlanner, SceneOptimizer, SceneQualityGate, BlenderSceneAdapter
)
from .gameplay_aware_construction import (
    GameplayAwareAPI, ActorType, InteractionType, CollisionLayer, CollisionPurpose,
    SurfaceWalkability, TraversalType, GameplayTag, GameplaySeverity,
    ActorProfile, InteractionPoint, GameplayCollisionProfile, SpawnPoint,
    StairDefinition, DoorGameplayDefinition, GameplayContract,
    GameplayValidationReport, GameplaySpecification, GameplayScaleValidator,
    GameplayNavigationValidator, GameplayTraversalValidator,
    GameplayInteractionValidator, GameplaySpawnValidator, GameplayTestAgent,
    ParameterImpactGraph
)
from .build_orchestrator import (
    BuildOrchestratorAPI, AgentType, TaskState, LockType, RiskLevel,
    OrchestratorExecutionMode, MessageType, ScopeType, AgentDefinition, Task,
    Checkpoint, ChangeSet, OrchestrationCorrectionPlan, ExecutionReport,
    OrchestratorConfig, AgentRegistry, CorrectionAgent, TaskManager,
    AssetLockManager, CheckpointManager, ReworkDetector, AIOrchestrator
)
from .intent_specification_compiler import (
    IntentSpecificationAPI, ConstraintType, ValueType, UnitType,
    AISpecStatus, ApprovalState, AIRequirementStatus, AISpec, StyleSpec,
    VisualIntent, DoorSpec, WindowSpec, StairSpec, SpecBudget,
    RequirementEntry, AssumptionEntry, SpecDiffResult, ImpactAnalysisResult,
    SemanticDictionary, IntentCompiler, SpecificationValidator,
    SpecDiffEngine, SpecTaskCompiler
)
from .procedural_asset_system import (
    ProceduralAssetAPI, PrimitiveType, QualityLevel, ConstructionPass,
    RoofStyle, OpeningType, GeometryPrimitive, GraphNode as ProceduralGraphNode,
    AssetDNA, AssetConstructionGraph, GeometryReport, BuildManifest as ProceduralBuildManifest,
    FoundationBuilder, WallBuilder, DoorBuilder, WindowBuilder, RoofBuilder,
    StairBuilder, ProceduralAssetBuilder, BlenderGeometryAdapter
)
from .world_state_change_planning import (
    WorldStateAPI, WorldAssetStatus, WorldChangeType, WorldChangeScope,
    WorldConstraintType, ReconciliationState, ContextLevel, TransactionStatus,
    ComponentMetadata, WorldAssetState, ProjectState, WorldState,
    ChangeRequest, ChangePlan, DryRunResult, SceneSnapshot, TransactionRecord,
    WorldStateManager, WorldDependencyGraph, TargetResolver,
    ConstraintRegistry, ChangePlanner, ReconciliationEngine, TransactionManager
)
from .ai_task_compiler import (
    AITaskCompilerAPI, TaskSource, TaskAction, SemanticOperation, TaskScope,
    TaskPriority, TaskRiskLevel, TaskStatusEnum, AmbiguityType, TaskPermissionType,
    ConstraintTypeEnum, TargetSpec, IntentModel, TaskConstraint, TaskPreference,
    TaskEnvelope, TaskPreview, TaskDecomposition, ClarificationRequest, TaskResult,
    TaskUnitNormalizer, ToolFirewall, RiskAnalyzer, TaskDecomposer, TaskCompiler
)
from .amsl import (
    AMSLAPI, AMSLAssetType, AMSLAssetPurpose, DimensionMode, RelationshipType,
    StyleFamily, DetailLevel, MaterialCategory, DamageLevel, CollisionType,
    QualityLevel as AMSLQualityLevel, RebuildPolicy, ConstraintType as AMSLConstraintType,
    ConstraintPriority as AMSLConstraintPriority, ValidationCategory as AMSLValidationCategory,
    CoordinateSystem, DimensionValue as AMSLDimensionValue, DimensionsSpec as AMSLDimensionsSpec,
    StructureSpec as AMSLStructureSpec, ComponentSpec as AMSLComponentSpec,
    RelationshipSpec as AMSLRelationshipSpec, StyleSpec as AMSLStyleSpec,
    GeometrySpec as AMSLGeometrySpec, MaterialSpec as AMSLMaterialSpec,
    DamageSpec, CollisionSpec as AMSLCollisionSpec, GameplaySpec as AMSLGameplaySpec,
    ReferenceSpec as AMSLReferenceSpec, ConstraintSpec as AMSLConstraintSpec,
    GenerationSpec as AMSLGenerationSpec, ValidationSpec as AMSLValidationSpec,
    QualityProfileSpec, ProvenanceSpec, AssetSpecification as AMSLAssetSpecification,
    SpecificationDiff as AMSLSpecificationDiff, BuildRequirements,
    AMSLValidator, AMSLDiffEngine, SpecificationCompiler as AMSLSpecificationCompiler,
    SchemaRegistry as AMSLSchemaRegistry
)
from .visual_reference_similarity import (
    VisualSimilarityAPI, ReferenceType as SimilarityReferenceType,
    ReferencePriority as SimilarityReferencePriority, ReferenceCategory as SimilarityReferenceCategory,
    EvaluationStatus as SimilarityEvaluationStatus, DifferenceType as SimilarityDifferenceType,
    DifferenceSeverity as SimilarityDifferenceSeverity, CorrectionPriority as SimilarityCorrectionPriority,
    ViewDirection as SimilarityViewDirection, ReferenceProfile as SimilarityReferenceProfile,
    AssetObservation as SimilarityAssetObservation, DifferenceRecord as SimilarityDifferenceRecord,
    CorrectionRequest as SimilarityCorrectionRequest, SimilarityWeights,
    SimilarityReport as SimilarityReportV2, CandidateAsset as SimilarityCandidateAsset,
    ReferenceAnalyzer as SimilarityReferenceAnalyzer, AssetObserver as SimilarityAssetObserver,
    DifferenceDetector as SimilarityDifferenceDetector, SimilarityEngine as SimilarityEngineV2,
    CorrectionGenerator as SimilarityCorrectionGenerator, LoopDiagnostics as SimilarityLoopDiagnostics
)
from .ai_critic_self_correction import (
    AICriticAPI, CriticStatus, ModificationLevel as CriticModificationLevel,
    CorrectionOperationType as CriticCorrectionOperationType,
    RootCauseSeverity as CriticRootCauseSeverity, CriticRiskLevel,
    BudgetStatus as CriticBudgetStatus, StrategyResult as CriticStrategyResult,
    RootCause as CriticRootCause, PreservationContract as CriticPreservationContract,
    CorrectionOp as CriticCorrectionOp, CorrectionPlan as CriticCorrectionPlanV2,
    CriticDecision, CriticPolicy as CriticPolicyV2, CheckpointSnapshot as CriticCheckpointSnapshot,
    CandidateBranch as CriticCandidateBranch, DiagnosisEngine as CriticDiagnosisEngine,
    PriorityEngine as CriticPriorityEngine, CorrectionPlanner as CriticCorrectionPlannerV2,
    IterationController as CriticIterationController, RollbackController as CriticRollbackController,
    CriticMemory as CriticMemoryV2
)
from .orchestration_runtime import (
    OrchestrationAPI, RuntimeTaskStatus, RuntimeTaskType, RuntimePriority as RuntimeTaskPriority,
    RuntimeLockType, AgentState as RuntimeAgentState, ExecutionState as RuntimeExecutionState,
    RuntimeEventType, ConcurrencyMode as RuntimeConcurrencyMode, Task as RuntimeTask,
    EventEnvelope as RuntimeEventEnvelope, LockLease as RuntimeLockLease, AgentProfile as RuntimeAgentProfile,
    ExecutionUnit as RuntimeExecutionUnit, WorkflowStep as RuntimeWorkflowStep, Workflow as RuntimeWorkflow,
    AssetManifest as RuntimeAssetManifest, EventBus as RuntimeEventBus, TaskStateMachine as RuntimeTaskStateMachine,
    TaskManager as RuntimeTaskManager, TaskQueue as RuntimeTaskQueue, LockManager as RuntimeLockManager,
    AgentManager as RuntimeAgentManager, MCPAdapter as RuntimeMCPAdapter, ExecutionManager as RuntimeExecutionManager,
    WorkflowEngine as RuntimeWorkflowEngine
)
from .intent_compiler_task_graph import (
    IntentCompilerAPI as Phase39IntentCompilerAPI, RequirementType as IntentRequirementType,
    RequirementPriority as IntentRequirementPriority, RequirementSource as IntentRequirementSource,
    AmbiguitySeverity as IntentAmbiguitySeverity, AmbiguityCategory as IntentAmbiguityCategory,
    ReferenceScopeType as IntentReferenceScopeType, TaskCriticality as IntentTaskCriticality,
    MilestoneType as IntentMilestoneType, PreflightStatus as IntentPreflightStatus,
    UserRequest as IntentUserRequest, Requirement as IntentRequirement,
    ExclusionItem as IntentExclusionItem, AmbiguityItem as IntentAmbiguityItem,
    ClarificationRequest as IntentClarificationRequest, ReferenceTargetMask as IntentReferenceTargetMask,
    CompiledIntent, TaskGraphNode as IntentTaskGraphNode, TaskGraphDAG as IntentTaskGraphDAG,
    ExecutionPlanStep as IntentExecutionPlanStep, IntentDelta, IntentParser,
    TaskGraphBuilder as IntentTaskGraphBuilder, GraphValidator as IntentGraphValidator,
    PlanCompiler as IntentPlanCompiler, DriftDetector as IntentDriftDetector,
    IncrementalReplanner as IntentIncrementalReplanner
)
from .parametric_asset_engine import (
    ParametricAssetAPI, ParamType as ParametricParamType, UnitType as ParametricUnitType,
    RoofType as ParametricRoofType, ComponentState as ParametricComponentState,
    PivotType as ParametricPivotType, GenerationStrategy as ParametricGenerationStrategy,
    ParametricErrorType, ParamDefinition as ParametricParamDefinition,
    ResolvedParameters as ParametricResolvedParameters, GeneratedComponent as ParametricGeneratedComponent,
    AssetSnapshot as ParametricAssetSnapshot, AssetDefinition as ParametricAssetDefinition,
    ParameterResolver as ParametricParameterResolver, ConstraintSolver as ParametricConstraintSolver,
    WallGenerator as ParametricWallGenerator, RoofGenerator as ParametricRoofGenerator,
    WindowGenerator as ParametricWindowGenerator, DoorGenerator as ParametricDoorGenerator,
    FoundationGenerator as ParametricFoundationGenerator, GeneratorRegistry as ParametricGeneratorRegistry,
    DirtyTracker as ParametricDirtyTracker, ParametricAssetEngine
)
from .visual_reference_matching import (
    VisualReferenceMatcherAPI, EvaluationMode as MatchingEvaluationMode,
    VisualDiagnosisType, CriticDecisionType as MatchingCriticDecisionType,
    ReferenceRole as MatchingReferenceRole, EvaluationStage as MatchingEvaluationStage,
    ColorSpaceType, ReferenceImageSpec, SilhouetteMetrics as MatchingSilhouetteMetrics,
    ProportionMetrics as MatchingProportionMetrics, MaterialMetrics as MatchingMaterialMetrics,
    VisualDiagnosis as MatchingVisualDiagnosis, ParameterCorrection as MatchingParameterCorrection,
    ScoringWeights as MatchingScoringWeights, VisualScoreReport as MatchingVisualScoreReport,
    SilhouetteAnalyzer as MatchingSilhouetteAnalyzer, ProportionAnalyzer as MatchingProportionAnalyzer,
    MaterialAnalyzer as MatchingMaterialAnalyzer, DiagnosticEngine as MatchingDiagnosticEngine,
    ParameterCorrectionEngine as MatchingParameterCorrectionEngine, VisualReferenceMatcher
)
from .mcp_execution_gateway import (
    MCPGatewayAPI, CommandType as GatewayCommandType, RiskLevel as GatewayRiskLevel,
    GatewayState, ExecutionStatus as GatewayExecutionStatus, DriftType as GatewayDriftType,
    ReconciliationMode as GatewayReconciliationMode, GatewayErrorType, GatewayCommand,
    CommandPlan as GatewayCommandPlan, SceneStateSnapshot as GatewaySceneStateSnapshot,
    ObjectStateRecord as GatewayObjectStateRecord, TransactionRecord as GatewayTransactionRecord,
    VerificationResult as GatewayVerificationResult, ExecutionResult as GatewayExecutionResult,
    GatewayPolicy, CommandRegistry as GatewayCommandRegistry, CapabilityManager as GatewayCapabilityManager,
    SceneStateTracker as GatewaySceneStateTracker, LockController as GatewayLockController,
    TransactionManager as GatewayTransactionManager, ResultVerifier as GatewayResultVerifier,
    DependencyScheduler as GatewayDependencyScheduler, ExecutionLoopGuard as GatewayExecutionLoopGuard,
    MockMCPAdapter as GatewayMockMCPAdapter, AhujasidMCPAdapter as GatewayAhujasidMCPAdapter,
    ExecutionGateway
)
from .ai_orchestration_api import (
    AIOrchestratorAPI, ToolCategory as AgentToolCategory, PermissionLevel as AgentPermissionLevel,
    AgentOperationStatus, AgentDecision, AgentAssetStatus, AgentComponentStatus, AgentErrorCode,
    ToolDefinition as AgentToolDefinition, AgentToolResponse, AgentPlan, AgentAssetContext,
    AgentDiagnostic, AgentCorrectionItem, AgentTaskBudget, ToolRegistry as AgentToolRegistry,
    ContextFilter as AgentContextFilter, StructuredMemory as AgentStructuredMemory, AgentFacade
)
from .asset_knowledge_base import (
    AssetKnowledgeAPI, ArchetypeCategory as KnowledgeArchetypeCategory,
    ComponentNecessity as KnowledgeComponentNecessity, DependencyType as KnowledgeDependencyType,
    DesignRuleSeverity as KnowledgeDesignRuleSeverity, StyleEra as KnowledgeStyleEra,
    DefectPatternType as KnowledgeDefectPatternType, ValidationProfileType as KnowledgeValidationProfileType,
    QualityProfileType as KnowledgeQualityProfileType, AssetLifecycleState as KnowledgeAssetLifecycleState,
    KnowledgeStatus, ConflictPriority as KnowledgeConflictPriority,
    ComponentSlot as KnowledgeComponentSlot, ParameterDefinitionKB as KnowledgeParameterDefinitionKB,
    DesignRule as KnowledgeDesignRule, ArchetypeDefinition as KnowledgeArchetypeDefinition,
    DesignTemplate as KnowledgeDesignTemplate, GeneratorDefinitionKB as KnowledgeGeneratorDefinitionKB,
    FailureKnowledge as KnowledgeFailureKnowledge, CorrectionPattern as KnowledgeCorrectionPattern,
    ObservationRecord as KnowledgeObservationRecord, RuleValidationResult as KnowledgeRuleValidationResult,
    KnowledgeContextSummary as KnowledgeContextSummary, ArchetypeRegistry as KnowledgeArchetypeRegistry,
    DesignTemplateLibrary as KnowledgeDesignTemplateLibrary, DesignRuleEngine as KnowledgeDesignRuleEngine,
    CorrectionPatternEngine as KnowledgeCorrectionPatternEngine, GeneratorSelector as KnowledgeGeneratorSelector,
    ConflictResolver as KnowledgeConflictResolver, KnowledgeQueryEngine, KnowledgeContextBuilder,
    KnowledgeLearningPipeline
)
from .reference_understanding_visual_spec import (
    VisualSpecificationAPI, ReferenceType as SpecReferenceType,
    ReferenceRole as SpecReferenceRole, GeometricPrimitiveType as SpecGeometricPrimitiveType,
    SpatialRelationType as SpecSpatialRelationType, UncertaintyType as SpecUncertaintyType,
    SpecificationPriority as SpecSpecificationPriority, TargetProfileType as SpecTargetProfileType,
    DetailTreatmentType as SpecDetailTreatmentType, ReferenceItem as SpecReferenceItem,
    VisualLandmark as SpecVisualLandmark, ComponentDetectionRecord as SpecComponentDetectionRecord,
    ProportionConstraint as SpecProportionConstraint, UncertaintyItem as SpecUncertaintyItem,
    FeatureParameterAttribution as SpecFeatureParameterAttribution,
    VisualSpecification, StructuralSpecification, VisualTargetProfile,
    SpecificationCompiler as SpecSpecificationCompiler,
    ParameterInfluenceMapper as SpecParameterInfluenceMapper
)
from .adaptive_generation_correction import (
    AdaptiveGenerationAPI, SessionState as AdaptiveSessionState,
    CorrectionOp as AdaptiveCorrectionOp, ScopeLevel as AdaptiveScopeLevel,
    TerminationReason as AdaptiveTerminationReason, AdaptiveRiskLevel,
    ErrorCategory as AdaptiveErrorCategory, GenerationAttempt as AdaptiveGenerationAttempt,
    ErrorDiagnosis as AdaptiveErrorDiagnosis, CorrectionCandidate as AdaptiveCorrectionCandidate,
    CorrectionTransactionRecord as AdaptiveCorrectionTransactionRecord,
    LeaderboardEntry as AdaptiveLeaderboardEntry, SessionReport as AdaptiveSessionReport,
    ErrorAttributor as AdaptiveErrorAttributor, PartialRegenerator as AdaptivePartialRegenerator,
    CorrectionTransaction as AdaptiveCorrectionTransaction,
    AdaptiveGenerationEngine
)
from .cross_asset_dependency_world import (
    WorldDependencyAPI, NodeType as WorldNodeType, EdgeType as WorldEdgeType,
    DependencyStrength as WorldDependencyStrength, DirtyState as WorldDirtyState,
    ImpactLevel as WorldImpactLevel, ChangeCategory as WorldChangeCategory,
    WorldNode, WorldEdge, ImpactReport as WorldImpactReport,
    RegenerationPlan as WorldRegenerationPlan, WorldSnapshotRecord,
    WorldChangeProposal, WorldDependencyGraph, ImpactAnalyzer as WorldImpactAnalyzer,
    WorldRegenerationPlanner
)
from .production_pipeline_unreal import (
    ProductionPipelineAPI, AssetLifecycle as UnrealAssetLifecycle,
    PivotType as UnrealPivotType, CollisionStrategy as UnrealCollisionStrategy,
    NanitePolicy as UnrealNanitePolicy, ChangeClass as UnrealChangeClass,
    QualityGateStatus as UnrealQualityGateStatus, SourceOwnership as UnrealSourceOwnership,
    SocketDefinition as UnrealSocketDefinition, BlenderExportContract,
    CollisionContract as UnrealCollisionContract, LODContract as UnrealLODContract,
    ExportManifest as UnrealExportManifest, ProductionAsset as UnrealProductionAsset,
    QualityGateReport as UnrealQualityGateReport, PublicationRecord as UnrealPublicationRecord,
    NamingPathPolicy as UnrealNamingPathPolicy, ExportValidator as UnrealExportValidator,
    BuildCache as UnrealBuildCache, UnrealExecutionGateway
)
from .multi_agent_control_plane import (
    ControlPlaneAPI, TaskState as ControlTaskState,
    AgentRole as ControlAgentRole, ToolEffect as ControlToolEffect,
    LockType as ControlLockType, DecisionAction as ControlDecisionAction,
    ApprovalStatus as ControlApprovalStatus, Task as ControlTask,
    AgentDefinition as ControlAgentDefinition, ToolDefinition as ControlToolDefinition,
    AgentResult as ControlAgentResult, ResourceLock as ControlResourceLock,
    ExecutionTrace as ControlExecutionTrace, ControlPlan,
    AgentRegistry as ControlAgentRegistry, ToolGuard as ControlToolGuard,
    ResourceLockManager as ControlResourceLockManager, TaskScheduler as ControlTaskScheduler,
    ControlPlane
)
from .semantic_visual_critic import (
    SemanticVisualCriticAPI, DefectCategory as CriticDefectCategory,
    DefectSeverity as CriticDefectSeverity, CriticRecommendation,
    QualityProfile as CriticQualityProfile, CriticCameraView,
    RequirementType as CriticRequirementType, ExpectedState as CriticExpectedState,
    ActualState as CriticActualState, VisualDefect, CorrectionPlanItem,
    CriticResult, SilhouetteAnalyzer as CriticSilhouetteAnalyzer,
    StyleMaterialAnalyzer as CriticStyleMaterialAnalyzer,
    SemanticDetector as CriticSemanticDetector, SemanticComparator
)
from .prompt_compiler_intent_spec import (
    PromptCompilerAPI, IntentType as CompilerIntentType,
    AssetClassType as CompilerAssetClassType, ProvenanceType as CompilerProvenanceType,
    RequirementHardness as CompilerRequirementHardness, ConflictSeverity as CompilerConflictSeverity,
    CompilationStatus as CompilerCompilationStatus, ExtractedComponent as CompilerExtractedComponent,
    RequirementConflict as CompilerRequirementConflict, AmbiguityRecord as CompilerAmbiguityRecord,
    ClarificationRequest as CompilerClarificationRequest, CompiledSpecification,
    ConversationContext as CompilerConversationContext, CompilationResult as CompilerCompilationResult,
    SynonymRegistry as CompilerSynonymRegistry, UnitNormalizer as CompilerUnitNormalizer,
    IntentRequirementExtractor as CompilerIntentRequirementExtractor,
    SpecificationCompiler as CompilerSpecificationCompiler
)
from .generation_strategy_engine import (
    GenerationStrategyAPI, GenerationStrategyType,
    AssetComplexityLevel, FailureCategory as StrategyFailureCategory,
    StageType as GenerationStageType, GenerationStrategy, CandidateStrategy,
    GenerationStage, GenerationCheckpoint, GenerationPlan,
    StrategyDecisionRecord, AssetComplexityReport, ReuseAnalysisReport,
    GenerationStrategyRegistry, AssetComplexityAnalyzer,
    ReuseAnalyzer, StrategySelector
)
from .blender_capability_layer import (
    BlenderCapabilityAPI, OperationStatus as CapabilityOperationStatus,
    CapabilityCategory, ErrorTaxonomy as CapabilityErrorTaxonomy,
    ErrorSeverity as CapabilityErrorSeverity, CircuitState as CapabilityCircuitState,
    LockScope as CapabilityLockScope, PermissionLevel as CapabilityPermissionLevel,
    CapabilityContract, OperationRequest as CapabilityOperationRequest,
    OperationResponse as CapabilityOperationResponse,
    BlenderObjectState, BlenderSceneState, TransactionRecord as CapabilityTransactionRecord,
    HealthReport as CapabilityHealthReport, IBlenderAdapter, MockBlenderAdapter,
    AhujasidCommandTranslator, AhujasidResponseTranslator, AhujasidBlenderAdapter,
    CapabilityRegistry, CircuitBreaker as CapabilityCircuitBreaker,
    TransactionManager as CapabilityTransactionManager, StateReconciler as CapabilityStateReconciler
)
from .semantic_asset_graph_twin import (
    SemanticDigitalTwinAPI, GraphNodeType as TwinGraphNodeType,
    GraphRelationType as TwinGraphRelationType, ReconciliationState as TwinReconciliationState,
    ComponentLifecycleState as TwinComponentLifecycleState,
    AssetLifecycleState as TwinAssetLifecycleState, ImpactLevel as TwinImpactLevel,
    DiffType as TwinDiffType, AssetIdentity as TwinAssetIdentity,
    ComponentIdentity as TwinComponentIdentity, SemanticComponentNode as TwinSemanticComponentNode,
    SemanticRelationship as TwinSemanticRelationship, SemanticAnchor as TwinSemanticAnchor,
    SemanticSocket as TwinSemanticSocket, AssetSnapshot as TwinAssetSnapshot,
    SemanticDiff as TwinSemanticDiff, RegenerationBoundary as TwinRegenerationBoundary,
    SemanticAssetGraph, DigitalTwinReconciler, AssetImpactAnalyzer as TwinImpactAnalyzer,
    SemanticResolver as TwinSemanticResolver, AssetDiffEngine as TwinAssetDiffEngine
)
from .reference_analysis_visual_decomposition import (
    ReferenceAnalysisAPI, ReferenceModality, CameraPerspective as RefCameraPerspective,
    ExtractedMaterialType as RefMaterialType, StyleArchetype as RefStyleArchetype,
    ConfidenceTier as RefConfidenceTier, VisualFeatureImportance as RefFeatureImportance,
    ImageReferenceInput, SilhouetteExtraction as RefSilhouetteExtraction,
    ProportionEstimate as RefProportionEstimate, DecomposedPart as RefDecomposedPart,
    MaterialPalette as RefMaterialPalette, ColorPalette as RefColorPalette,
    CameraEstimation as RefCameraEstimation, VisualRequirementItem as RefRequirementItem,
    DecomposedReferenceReport, SilhouetteExtractor as RefSilhouetteExtractor,
    ProportionEstimator as RefProportionEstimator, PartDecomposer as RefPartDecomposer,
    MaterialColorAnalyzer as RefMaterialColorAnalyzer,
    CameraViewEstimator as RefCameraViewEstimator, ReferenceDecompositionEngine
)
from .visual_specification_compiler import (
    VisualSpecificationAPI, VisualCompilationInput, VisualAssetSpecification,
    RequirementClass as VasRequirementClass, ValidationMethod as VasValidationMethod,
    RequirementOrigin as VasRequirementOrigin, ContradictionSeverity as VasContradictionSeverity,
    AmbiguitySeverity as VasAmbiguitySeverity, InformationState as VasInformationState,
    EngineTarget as VasEngineTarget, TraceabilityRecord as VasTraceabilityRecord,
    InvariantSpec as VasInvariantSpec, VariableSpec as VasVariableSpec,
    ToleranceSpec as VasToleranceSpec, AcceptanceCriterion as VasAcceptanceCriterion,
    AmbiguityReport as VasAmbiguityReport, ContradictionReport as VasContradictionReport,
    UnrealRequirementsSpec as VasUnrealRequirementsSpec,
    ProductionBudgetSpec as VasProductionBudgetSpec, ValidationResult as VasValidationResult,
    VisualSpecificationCompiler
)
from .procedural_modeling_strategy import (
    ProceduralModelingStrategyAPI, AssetCategoryTag as MspAssetCategoryTag,
    ComponentConstructionMethod as MspConstructionMethod,
    BasePrimitiveType as MspBasePrimitiveType,
    GeometricOperationType as MspGeometricOpType, SymmetryType as MspSymmetryType,
    DetailLevel as MspDetailLevel, CollisionStrategyType as MspCollisionType,
    PivotStrategyType as MspPivotType, StrategyRiskLevel as MspRiskLevel,
    ReuseStrategyType as MspReuseType, ParametricSpec as MspParametricSpec,
    GeometricOperation as MspGeometricOperation, ModifierStrategySpec as MspModifierSpec,
    GeometryNodesStrategySpec as MspGeometryNodesSpec,
    ComponentStrategy as MspComponentStrategy, GlobalStrategySpec as MspGlobalStrategySpec,
    GeometryBudgetDistribution as MspBudgetDistribution, CostEstimate as MspCostEstimate,
    ModelingStrategyPlan, StrategyValidationResult as MspValidationResult,
    ProceduralModelingStrategyEngine
)
from .geometry_generation_engine import (
    GeometryGenerationAPI, GeneratedGeometryResult as F58GeneratedGeometryResult,
    GeometryObjectSpec as F58GeometryObjectSpec, ComponentGenerationResult as F58ComponentResult,
    TopologySummary as F58TopologySummary, GeometryValidationResult as F58ValidationResult,
    CompensationResult as F58CompensationResult, GenerationContext as F58GenerationContext,
    OperationState as F58OpState, TransactionState as F58TransactionState,
    MeshTopologyType as F58MeshTopologyType, ExportRole as F58ExportRole,
    GeometryGenerationEngine
)
from .material_surface_generation import (
    MaterialSurfaceAPI, SurfaceTypeTag as F59SurfaceType,
    ShaderModelType as F59ShaderModel, ColorSpaceType as F59ColorSpace,
    UVUnwrapMethod as F59UVMethod, BakeChannelType as F59BakeChannel,
    AttributeSemanticName as F59AttributeSemantic, InvalidationState as F59InvalidationState,
    SurfaceRegion as F59SurfaceRegion, MaterialDefinition as F59MaterialDef,
    ShaderGraphSpec as F59ShaderGraph, UVLayout as F59UVLayout,
    TexelDensityReport as F59TexelReport, BakePlan as F59BakePlan,
    GeneratedSurfaceResult as F59SurfaceResult, SurfaceValidationResult as F59ValidationResult,
    MaterialSurfaceGenerationEngine
)
from .presentation_matching import (
    PresentationMatchingAPI, ProjectionType as F60ProjectionType,
    CompositionAlignment as F60CompositionAlign, LightType as F60LightType,
    BackgroundType as F60BgType, ViewTransformType as F60ViewTransform,
    PresentationViewAngle as F60ViewAngle, CameraConfiguration as F60CameraConfig,
    FramingSpecification as F60FramingSpec, LightingConfiguration as F60LightingConfig,
    VisualPresentationContext as F60PresentationContext,
    PresentationValidationResult as F60ValidationResult,
    CameraLightingPresentationEngine
)
from .automated_visual_evaluation import (
    AutomatedVisualEvaluationAPI, EvaluationCategory as F61Category,
    DefectType as F61DefectType, DefectSeverity as F61Severity,
    DefectCauseCategory as F61CauseCategory, AcceptanceStatus as F61AcceptanceStatus,
    VisualDefect as F61Defect, CorrectionHint as F61CorrectionHint,
    CategoryEvaluation as F61CategoryEvaluation, EvaluationDelta as F61EvaluationDelta,
    VisualEvaluationResult as F61EvaluationResult, EvaluationValidationResult as F61ValidationResult,
    AutomatedVisualEvaluationEngine
)
from .geometric_validation_qa import (
    GeometricValidationAPI, GeometricDefectCategory as F62DefectCategory,
    DefectSeverity as F62Severity, ValidationStatus as F62ValidationStatus,
    ValidationProfileType as F62ProfileType, MeshInventory as F62MeshInventory,
    TopologyStatistics as F62TopologyStats, UnrealReadinessReport as F62UnrealReadiness,
    GeometricDefect as F62Defect, GeometricCorrectionHint as F62CorrectionHint,
    GeometricValidationResult as F62ValidationResult, QAValidationResult as F62QAValidationResult,
    GeometricValidationEngine
)
from .intelligent_critic_engine import (
    IntelligentCriticAPI, CausalCategory as F63CausalCategory,
    CriticPriority as F63Priority, RiskLevel as F63RiskLevel,
    IterationRecommendation as F63IterationRec, EvidenceItem as F63EvidenceItem,
    RootCause as F63RootCause, DefectCluster as F63DefectCluster,
    CriticDiagnosis as F63Diagnosis, ParameterRecommendation as F63ParamRec,
    CorrectionAction as F63CorrectionAction, CorrectionPlan as F63CorrectionPlan,
    IntelligentCriticResult as F63CriticResult, CriticValidationResult as F63ValidationResult,
    IntelligentCriticEngine
)
from .autonomous_correction_engine import (
    AutonomousCorrectionAPI, CorrectionStatus as F64CorrectionStatus,
    ActionAuthorization as F64ActionAuth, RollbackStatus as F64RollbackStatus,
    CorrectionStrategyType as F64StrategyType, RegressionSeverity as F64RegressionSeverity,
    OperationType as F64OperationType, ParameterChange as F64ParameterChange,
    AssetSnapshot as F64Snapshot, QualityDeltaReport as F64QualityDelta,
    CorrectionConfiguration as F64Configuration, CorrectionResult as F64CorrectionResult,
    CorrectionValidationResult as F64ValidationResult, AutonomousCorrectionEngine
)
from .iterative_generation_loop import (
    IterativeGenerationLoopAPI, LoopState as F65LoopState,
    DecisionOutcome as F65DecisionOutcome, StopReason as F65StopReason,
    IterationTargets as F65Targets, IterationContext as F65IterationContext,
    IterationRecord as F65Record, IterationLoopConfiguration as F65Configuration,
    IterativeGenerationRequest as F65Request, IterativeGenerationResult as F65LoopResult,
    LoopValidationResult as F65ValidationResult, IterativeGenerationLoopEngine
)
from .quality_scoring_acceptance import (
    QualityScoringAPI, AcceptanceStatus as F66AcceptanceStatus,
    QualityLevel as F66QualityLevel, MetricCategory as F66Category,
    ConstraintSeverity as F66Severity, QualityMetric as F66Metric,
    QualityConstraint as F66Constraint, QualityDefect as F66Defect,
    QualityProfile as F66Profile, QualityResult as F66QualityResult,
    QualityReport as F66Report, ScoringValidationResult as F66ValidationResult,
    QualityScoringService
)
from .asset_optimization_engine import (
    AssetOptimizationAPI, TargetPlatform as F67Platform, TargetEngine as F67Engine,
    OptimizationObjective as F67Objective, NanitePolicy as F67NanitePolicy,
    CollisionPolicy as F67CollisionPolicy, SessionStatus as F67SessionStatus,
    StrategyType as F67StrategyType, AssetCost as F67AssetCost,
    OptimizationProfile as F67OptimizationProfile, OptimizationOpportunity as F67Opportunity,
    OptimizationCandidate as F67Candidate, OptimizationSession as F67Session,
    OptimizedAssetResult as F67OptimizedResult, OptimizationValidationResult as F67ValidationResult,
    AssetOptimizationService
)
from .game_engine_readiness import (
    GameEngineReadinessAPI, ReadinessStatus as F68ReadinessStatus,
    EngineTarget as F68EngineTarget, ValidationSeverity as F68Severity,
    PivotMode as F68PivotMode, CoordinateSystem as F68CoordinateSystem,
    NaniteReadinessState as F68NaniteState, EngineProfile as F68EngineProfile,
    ExportProfile as F68ExportProfile, EngineValidationResult as F68ValidationResult,
    EngineReadinessScore as F68ReadinessScore, EngineReadinessManifest as F68Manifest,
    GameEngineReadyAsset as F68ReadyAsset, ReadinessValidationResult as F68ReadinessValidationResult,
    GameEngineReadinessService
)
from .asset_packaging_delivery import (
    AssetPackagingAPI, PackageType as F69PackageType, PackageStatus as F69PackageStatus,
    DeliveryTargetType as F69TargetType, DependencyState as F69DepState,
    PackageProfile as F69PackageProfile, DeliveryTarget as F69DeliveryTarget,
    PackageFileEntry as F69FileEntry, PackageDependency as F69Dependency,
    PackageManifest as F69Manifest, DeliveryReceipt as F69Receipt,
    DeliveredAssetPackage as F69DeliveredPackage, PackagingValidationResult as F69ValidationResult,
    AssetPackagingService
)
from .long_running_job_recovery import (
    LongRunningJobAPI, JobType as F70JobType, JobState as F70JobState,
    JobPriority as F70Priority, BackoffStrategy as F70Backoff,
    ErrorCategory as F70ErrorCategory, RecoveryAction as F70RecoveryAction,
    JobIdentity as F70JobIdentity, JobDefinition as F70JobDefinition,
    Job as F70Job, JobCheckpoint as F70Checkpoint, JobProgress as F70Progress,
    JobError as F70JobError, JobEvent as F70JobEvent, WorkerIdentity as F70WorkerIdentity,
    RecoverableJob as F70RecoverableJob, RecoveryReport as F70RecoveryReport,
    JobValidationResult as F70ValidationResult, LongRunningJobService
)

__all__ = [
    "AssetOrchestrationEngine",
    "GeometryEngine",
    "GeometryContext",
    "IGeometryGenerator",
    "GeneratedGeometry",
    "PrimitiveGenerator",
    "ProfileGenerator",
    "GeometryGeneratorRegistry",
    "GeometricComponent",
    "ComponentRegistry",
    "ComponentDependencies",
    "DirtyTracker",
    "DependencyAnalyzer",
    "RebuildPlanner",
    "ParameterSpec",
    "ParameterType",
    "GeometryValidator",
    "DimensionValidator",
    "TopologyValidator",
    "ChangeBudget",
    "ScopeSpec",
    "ConstraintEngine",
    "NumericConstraint",
    "NormalizedIntent",
    "IntentType",
    "ModifierType",
    "TargetResolver",
    "ConfidenceSystem",
    "ConfidenceAction",
    "ConfidenceThresholds",
    "ClarificationManager",
    "UnitNormalizer",
    "AssetSpecification",
    "AssetCategory",
    "SymmetryType",
    "DimensionsSpec",
    "ComponentSpec",
    "BudgetSpec",
    "VisualAPI",
    "VisualFeedbackLoop",
    "QualityGate",
    "QualityStatus",
    "QualityProfile",
    "ThresholdManager",
    "ReportGenerator",
    "VisualReference",
    "ReferenceType",
    "ReferenceView",
    "DifferenceDetector",
    "DifferenceRecord",
    "DifferenceType",
    "CorrectionMapper",
    "CorrectionProposal",
    "SilhouetteComparator",
    "DimensionComparator",
    "RenderCapture",
    "CameraNormalizer",
    "ViewOrientation",
    "AppearanceAPI",
    "AppearanceEngine",
    "AppearanceContext",
    "MaterialDefinition",
    "PBRParameters",
    "ShaderType",
    "MaterialInstance",
    "MaterialRegistry",
    "TextureMetadata",
    "TextureUsage",
    "ColorSpace",
    "TextureRegistry",
    "ColorSpaceValidator",
    "UVSet",
    "UVMethod",
    "UVProjection",
    "UVValidator",
    "MaterialAssignmentManager",
    "AppearanceValidator",
    "AppearanceDiff",
    "GameReadyAPI",
    "GameReadyEngine",
    "GameReadyManifest",
    "ApprovalValidator",
    "NamingValidator",
    "BudgetValidator",
    "GameReadyLODProfile",
    "LODLevelConfig",
    "LODGenerator",
    "GeneratedLODLevel",
    "LODValidator",
    "CollisionProfile",
    "CollisionType",
    "CollisionGenerator",
    "CollisionHull",
    "CollisionValidator",
    "PivotManager",
    "PivotType",
    "ScaleManager",
    "SocketManager",
    "AssetMapper",
    "UnrealAssetMapping",
    "UnrealImportSettings",
    "UnrealAPI",
    "UnrealEngine",
    "UnrealAssetRegistry",
    "UnrealAssetReference",
    "UnrealActor",
    "ActorRegistry",
    "ActorTransform",
    "SceneGraph",
    "SpatialSolver",
    "SpatialRelation",
    "SceneDiff",
    "PropertyChange",
    "UnrealDependencyGraph",
    "GameplayAPI",
    "GameplayEngine",
    "CapabilityType",
    "CapabilityDefinition",
    "CapabilityInstance",
    "CapabilityRegistry",
    "CapabilityResolver",
    "InteractionSystem",
    "InteractionDefinition",
    "GameplayCondition",
    "GameplayAction",
    "EventBus",
    "GameplayEvent",
    "StateMachine",
    "WeaponData",
    "ActorGameplayData",
    "GameplayDiff",
    "AIPlanningAPI",
    "AIRequest",
    "RequestSource",
    "AIRequestGateway",
    "AdvancedIntentParser",
    "PlanningIntentType",
    "ParsedIntent",
    "GapAnalyzer",
    "GoalSpec",
    "StateGap",
    "TaskGraph",
    "PlannedTask",
    "TaskStatus",
    "PlanOptimizer",
    "DestructiveOperationGuard",
    "PlanExecutor",
    "VisualIntelligenceAPI",
    "VisualGoalSpec",
    "ProportionAnalyzer",
    "ComponentDetector",
    "QualityScorer",
    "VerificationReport",
    "QualityWeights",
    "VisualCorrectionPlanner",
    "CorrectionExecutionAPI",
    "LegacyCorrectionPlan",
    "CorrectionOperation",
    "OperationType",
    "RegisteredComponent",
    "OperationRegistry",
    "RiskAnalyzer",
    "OperationPermissionManager",
    "SnapshotManager",
    "AssetSnapshot",
    "MutationTransaction",
    "TransactionState",
    "IBlenderProvider",
    "MockBlenderProvider",
    "DependencyResolver",
    "MutationValidator",
    "MutationExecutor",
    "AssetMemoryAPI",
    "FailureRecord",
    "CorrectionRecord",
    "StrategyRecord",
    "FailureCategory",
    "FailureTypeRegistry",
    "SQLiteMemoryStore",
    "SimilarityEngine",
    "ConfidenceEngine",
    "PatternDetector",
    "MemoryRanker",
    "GenerationAdvisor",
    "AutonomousDecisionAPI",
    "DecisionState",
    "DecisionStateEnum",
    "GoalEvaluator",
    "UtilityCalculator",
    "ProgressEvaluator",
    "ProgressClassification",
    "BudgetController",
    "CorrectionBudget",
    "LoopController",
    "StoppingController",
    "ActionPlan",
    "ActionPlanner",
    "DecisionLogger",
    "DecisionLogEntry",
    "DecisionEngine",
    "SpecificationCompilerAPI",
    "AttributeProvenance",
    "DimensionValue",
    "ComponentSpecEntry",
    "ConstraintEntry",
    "StyleSpecEntry",
    "AssetOntology",
    "UnitResolver",
    "IntentExtractor",
    "ConstraintExtractor",
    "RelationExtractor",
    "ConflictDetector",
    "AmbiguityDetector",
    "SpecificationPatcher",
    "SpecificationDriftDetector",
    "SpecificationCompiler",
    "ProceduralTemplatesAPI",
    "IAssetTemplate",
    "SwordTemplate",
    "TemplateRegistry",
    "ConstructionPlan",
    "ConstructionOperation",
    "ConstructionDependencyGraph",
    "ProceduralBuilder",
    "PartialRebuilder",
    "ParameterResolver",
    "ParameterConstraintSolver",
    "VisualCriticAPI",
    "EvaluationContext",
    "CriticReport",
    "CriticIssue",
    "CriticStatus",
    "IssueSeverity",
    "AIVisualCritic",
    "ParameterMappingEngine",
    "ParameterPatchGenerator",
    "ParameterPatch",
    "VisualEvaluationEngine",
    "AssetMemorySystemAPI",
    "AssetRecord",
    "AssetVersionRecord",
    "LegacyPatternRecord",
    "PatternEvidence",
    "EvaluationRecord",
    "LegacyFailureRecord",
    "AuditEvent",
    "VersionManager",
    "SQLiteAssetStore",
    "KnowledgeExtractor",
    "PatternPromoter",
    "NegativeKnowledgeEngine",
    "MemoryQueryEngine",
    "ReuseStrategyDecision",
    "PatternStatus",
    "LegacyPatternScope",
    "ReproductionStatus",
    "AssetLibraryAPI",
    "BuildIntent",
    "ResolvedBuildSpec",
    "VariantDefinition",
    "PresetDefinition",
    "ManifestHasher",
    "SocketSystem",
    "LibrarySearchEngine",
    "ParameterHierarchySolver",
    "LibraryConstraintEngine",
    "SceneOrchestrationAPI",
    "SceneIntent",
    "ScenePlan",
    "SceneNode",
    "SceneSummary",
    "ProxyBounds",
    "ProxyScene",
    "LayoutSolver",
    "BatchSceneBuilder",
    "SceneReconciler",
    "SceneStatus",
    "NodeDirtyState",
    "ReconciliationStatus",
    "VisualEvaluationQAAPI",
    "EvaluationDimension",
    "EvaluationSeverity",
    "RepairScope",
    "EvaluationFailure",
    "RepairCandidate",
    "RepairPlan",
    "EvaluationReport",
    "ExpectedVisualProfile",
    "ProfileRegistry",
    "EvaluationProfile",
    "MultiDimensionEvaluator",
    "RepairPlanner",
    "RegressionDetector",
    "OscillationDetector",
    "ClosedLoopOptimizer",
    "IntentCompilerAPI",
    "NaturalLanguageRequest",
    "RequestContext",
    "BuildSpecification",
    "BuildAuthorization",
    "Requirement",
    "IntentConstraint",
    "IntentTrace",
    "RequirementPriority",
    "AmbiguitySeverity",
    "ActionType",
    "IntentUnitNormalizer",
    "ToolGovernanceAPI",
    "ToolRisk",
    "PermissionType",
    "ActionScope",
    "ActionLifecycle",
    "ToolDefinition",
    "ActionProposal",
    "ExecutionBudget",
    "NormalizedToolResult",
    "StateSnapshot",
    "AgentPermissionProfile",
    "PermissionManager",
    "ActionValidator",
    "DuplicateActionDetector",
    "ExecutionLoopGuard",
    "PostActionValidator",
    "RollbackManager",
    "AIToolGateway",
    "AssetReuseEngineAPI",
    "ReuseDecisionType",
    "AssetMetadata",
    "LibraryAssetRecord",
    "AssetVariant",
    "ReuseDecision",
    "AssetSearchQuery",
    "SearchResultCandidate",
    "FingerprintMatcher",
    "AssetRetrievalEngine",
    "VariantManager",
    "InstancingEngine",
    "ReuseDecisionMaker",
    "ParametricBuilderAPI",
    "ParametricAssetType",
    "BuildStage",
    "BuildState",
    "ParameterDefinition",
    "ParametricAssetDefinition",
    "ParameterChange",
    "BuildResult",
    "ParameterDependencyGraph",
    "ParameterFormulaEngine",
    "ParametricConstraintSolver",
    "ParameterTransactionManager",
    "GeometryCache",
    "PartialBuilder",
    "MedievalHouseBuilder",
    "VisualReferenceAPI",
    "LandmarkFeature",
    "ProportionFeature",
    "GeometricDiscrepancy",
    "ReferenceProfile",
    "ErrorMap",
    "FeatureExtractor",
    "GeometricMatcher",
    "AutonomousCorrectionLoopAPI",
    "LoopStatus",
    "CorrectionStep",
    "CorrectionPlan",
    "LoopIterationRecord",
    "AutonomousLoopResult",
    "CorrectionPlanner",
    "FeedbackLoopController",
    "LearnedPatternsAPI",
    "PatternState",
    "MemorySource",
    "ProblemSignature",
    "TrustLevel",
    "PatternScope",
    "MemoryEntry",
    "AssetMemoryRecord",
    "BuildMemoryRecord",
    "CorrectionMemoryRecord",
    "PatternRecord",
    "FailureMemoryRecord",
    "ReferenceMemoryRecord",
    "ProjectMemoryRecord",
    "RootCauseEngine",
    "PatternMatcher",
    "PatternLifecycleManager",
    "MemoryStore",
    "CompositeSceneAPI",
    "SceneType",
    "ConstraintPriority",
    "SpatialRelationType",
    "PlanningStage",
    "CompositeSceneState",
    "LockState",
    "CollisionSeverity",
    "SocketDefinition",
    "AssetInstance",
    "SceneArea",
    "SceneRegion",
    "SceneBudget",
    "SceneSpecification",
    "SceneBuildPlan",
    "SceneDiagnosticReport",
    "SceneManifest",
    "CompositionGraph",
    "GraphNode",
    "GraphEdge",
    "SocketMatcher",
    "SceneCollisionValidator",
    "SceneSpatialSolver",
    "HierarchicalPlanner",
    "SceneOptimizer",
    "SceneQualityGate",
    "BlenderSceneAdapter",
    "GameplayAwareAPI",
    "ActorType",
    "InteractionType",
    "CollisionLayer",
    "CollisionPurpose",
    "SurfaceWalkability",
    "TraversalType",
    "GameplayTag",
    "GameplaySeverity",
    "ActorProfile",
    "InteractionPoint",
    "GameplayCollisionProfile",
    "SpawnPoint",
    "StairDefinition",
    "DoorGameplayDefinition",
    "GameplayContract",
    "GameplayValidationReport",
    "GameplaySpecification",
    "GameplayScaleValidator",
    "GameplayNavigationValidator",
    "GameplayTraversalValidator",
    "GameplayInteractionValidator",
    "GameplaySpawnValidator",
    "GameplayTestAgent",
    "ParameterImpactGraph",
    "BuildOrchestratorAPI",
    "AgentType",
    "TaskState",
    "LockType",
    "RiskLevel",
    "OrchestratorExecutionMode",
    "MessageType",
    "ScopeType",
    "AgentDefinition",
    "Task",
    "Checkpoint",
    "ChangeSet",
    "OrchestrationCorrectionPlan",
    "ExecutionReport",
    "OrchestratorConfig",
    "AgentRegistry",
    "CorrectionAgent",
    "TaskManager",
    "AssetLockManager",
    "CheckpointManager",
    "ReworkDetector",
    "AIOrchestrator",
    "IntentSpecificationAPI",
    "ConstraintType",
    "ValueType",
    "UnitType",
    "AISpecStatus",
    "ApprovalState",
    "AIRequirementStatus",
    "AISpec",
    "StyleSpec",
    "VisualIntent",
    "DoorSpec",
    "WindowSpec",
    "StairSpec",
    "SpecBudget",
    "RequirementEntry",
    "AssumptionEntry",
    "SpecDiffResult",
    "ImpactAnalysisResult",
    "SemanticDictionary",
    "IntentCompiler",
    "SpecificationValidator",
    "SpecDiffEngine",
    "SpecTaskCompiler",
    "ProceduralAssetAPI",
    "PrimitiveType",
    "QualityLevel",
    "ConstructionPass",
    "RoofStyle",
    "OpeningType",
    "GeometryPrimitive",
    "ProceduralGraphNode",
    "AssetDNA",
    "AssetConstructionGraph",
    "GeometryReport",
    "ProceduralBuildManifest",
    "FoundationBuilder",
    "WallBuilder",
    "DoorBuilder",
    "WindowBuilder",
    "RoofBuilder",
    "StairBuilder",
    "ProceduralAssetBuilder",
    "BlenderGeometryAdapter",
    "WorldStateAPI",
    "WorldAssetStatus",
    "WorldChangeType",
    "WorldChangeScope",
    "WorldConstraintType",
    "ReconciliationState",
    "ContextLevel",
    "TransactionStatus",
    "ComponentMetadata",
    "WorldAssetState",
    "ProjectState",
    "WorldState",
    "ChangeRequest",
    "ChangePlan",
    "DryRunResult",
    "SceneSnapshot",
    "TransactionRecord",
    "WorldStateManager",
    "WorldDependencyGraph",
    "TargetResolver",
    "ConstraintRegistry",
    "ChangePlanner",
    "ReconciliationEngine",
    "TransactionManager",
    "AITaskCompilerAPI",
    "TaskSource",
    "TaskAction",
    "SemanticOperation",
    "TaskScope",
    "TaskPriority",
    "TaskRiskLevel",
    "TaskStatusEnum",
    "AmbiguityType",
    "TaskPermissionType",
    "ConstraintTypeEnum",
    "TargetSpec",
    "IntentModel",
    "TaskConstraint",
    "TaskPreference",
    "TaskEnvelope",
    "TaskPreview",
    "TaskDecomposition",
    "ClarificationRequest",
    "TaskResult",
    "ToolFirewall",
    "TaskDecomposer",
    "TaskCompiler",
    # Phase 71: Multi-Agent Orchestration Layer
    "MultiAgentOrchestrationAPI",
    "OrchestrationEngine",
    "OrchestrationPlan",
    "OrchestrationPolicy",
    "MultiAgentRegistry",
    "AgentContract",
    "AgentContext",
    "AgentResult",
    "AssetMutation",
    "Agent",
    "Task",
    "TaskGraph",
    "TaskScheduler",
    "OrchestrationEvent",
    "OrchestrationEventLog",
    "AgentPermission",
    "PerceptionAgent",
    "DesignAnalysisAgent",
    "StrategyAgent",
    "GeometryAgent",
    "MaterialAgent",
    "BlenderExecutionAgent",
    "PackagingAgent",
    # Phase 72: Agent Contracts & Tool Governance
    "AgentContractsToolGovernanceAPI",
    "AgentContractV2",
    "ContractValidator",
    "ContractRegistry",
    "Permission",
    "ResourceClassification",
    "RiskLevel",
    "AuthorizationStatus",
    "PermissionManager",
    "CapabilityDefinition",
    "CapabilityRegistry",
    "ToolDefinition",
    "ToolRegistry",
    "ResourceScope",
    "ResourceManager",
    "PolicySnapshot",
    "EmergencyStopController",
    "AuditRecord",
    "AuditLogger",
    "AuthorizationRequest",
    "AuthorizationDecision",
    "MutationRecord",
    "MutationGuard",
    # Phase 73: Context & Memory Management
    "ContextMemoryAPI",
    "MemoryRecord",
    "MemoryType",
    "MemoryScope",
    "MemoryStatus",
    "MemorySource",
    "MemoryStore",
    "ContextRelevanceEngine",
    "ContextConflictDetector",
    "ContextBuilder",
    "ExecutionContext",
    "ContextSnapshot",
    "ContextSnapshotManager",
    "MemoryConsolidator",
    "MemoryGovernanceGuard",
    # Context System
    "GlobalContext",
    "AssetContext",
    "TaskContext",
    "AgentContext",
    "JobContext",
    "ContextPriority",
    "ConflictStatus",
    "ContextPackage",
    "ContextConflict",
    "ContextPackager",
    "ContextRecoveryService",
    "ContextManager",
    # Knowledge Graph (F74)
    "NodeType",
    "KnowledgeGraphNode",
    "RelationshipType",
    "KnowledgeGraphEdge",
    "ProjectKnowledgeGraphStore",
    "DuplicateSemanticIdentityError",
    "GraphQueryEngine",
    "GraphImpactAnalyzer",
    "ImpactReport",
    "GraphConsistencyValidator",
    "GraphConsistencyReport",
    "DependencyCycleDetectedError",
    "GraphDiff",
    "GraphDiffEngine",
    "GraphSnapshotService",
    "GraphSnapshotRecord",
    "GraphProvenanceTracker",
    "BlenderGraphExtractor",
    "GraphGovernanceGuard",
    "GraphPermissionDeniedError",
    "ProjectKnowledgeGraphAPI",
    # Evaluation Benchmark (F75)
    "EvaluationDimension",
    "DefectSeverity",
    "DefectStatus",
    "BenchmarkStatus",
    "AcceptanceDecision",
    "EvaluationDefect",
    "DimensionScore",
    "EvaluationProfile",
    "EvaluationBenchmark",
    "create_weapon_profile",
    "create_unreal_ready_profile",
    "create_visual_asset_profile",
    "ProfileRegistry",
    "DimensionEvaluator",
    "ABComparisonEngine",
    "ABComparisonResult",
    "BenchmarkRegressionDetector",
    "RegressionReport",
    "EvaluationStore",
    "BenchmarkCorruptedError",
    "BenchmarkFinalizedImmutableError",
    "EvaluationGovernanceGuard",
    "EvaluationPermissionDeniedError",
    "KnowledgeGraphEvaluationBridge",
    "EvaluationBenchmarkAPI",
    # Golden Assets (F76)
    "GoldenStatus",
    "ReferenceStatus",
    "PromotionState",
    "ComparisonOutcome",
    "VersionBumpType",
    "GoldenAssetException",
    "GoldenIntegrityError",
    "GoldenImmutableError",
    "GoldenDuplicateError",
    "GoldenPromotionError",
    "GoldenPermissionDeniedError",
    "GoldenVersion",
    "GoldenVersionInfo",
    "GoldenBaseline",
    "ReferenceAsset",
    "GoldenAsset",
    "GoldenAssetRegistry",
    "ReferenceRegistry",
    "BaselineRegistry",
    "GoldenValidator",
    "GoldenAssetStore",
    "GoldenGovernanceGuard",
    "GoldenKnowledgeGraphBridge",
    "GoldenAssetAPI",
    # Golden Library (F76 core)
    "GoldenAssetStatus",
    "MutationType",
    "RegressionLevel",
    "GoldenImmutabilityError",
    "GoldenAuthorizationError",
    "GoldenIdentityHelper",
    "AssetFingerprinter",
    "GeometryFingerprinter",
    "MaterialFingerprinter",
    "SceneFingerprinter",
    "ReferenceFingerprinter",
    "GoldenRegistry",
    "VersionRegistry",
    "GoldenStore",
    "ManifestStore",
    "IntegrityStore",
    "RegressionPolicy",
    "CompatibilityChecker",
    "ImmutabilityGuard",
    "MutationDetector",
    "AuthorizationGuard",
    "EvaluationBridge",
    "RecoveryBridge",
    "GoldenAPI",
    # Diagnostics & Self-Debugging (F77)
    "FailureStatus",
    "FailureType",
    "ResolutionStatus",
    "FailureSeverity",
    "FailureRecord",
    "RootCause",
    "DiagnosticReport",
    "FailureCapture",
    "ExceptionNormalizer",
    "EventCollector",
    "FailureClassifier",
    "FailureSignature",
    "CategoryRules",
    "EvidenceItem",
    "StateSnapshot",
    "BlenderEvidenceCollector",
    "EvidenceCollector",
    "RootCauseAnalyzer",
    "DependencyAnalyzer",
    "ImpactAnalyzer",
    "ConfidenceEngine",
    "CorrectiveAction",
    "CorrectionPlanner",
    "CorrectionExecutor",
    "CorrectionValidator",
    "IncidentStore",
    "FailureHistory",
    "PatternDetector",
    "GovernanceBridge",
    "JobRecoveryBridge",
    "GoldenBridge",
    "DiagnosticsKnowledgeGraphBridge",
    "DiagnosticsAPI"
]

from .orchestration import (
    MultiAgentOrchestrationAPI, OrchestrationEngine, OrchestrationPlan, OrchestrationPolicy,
    AgentRegistry as MultiAgentRegistry, AgentContract, AgentContext, AgentResult, AssetMutation, Agent,
    Task, TaskGraph, TaskScheduler, OrchestrationEvent, OrchestrationEventLog,
    AgentPermission, PerceptionAgent, DesignAnalysisAgent, StrategyAgent, GeometryAgent,
    MaterialAgent, BlenderExecutionAgent, VisualCriticAgent, QAAgent,
    PackagingAgent
)

from .governance import (
    AgentContractsToolGovernanceAPI, AgentContractV2, ContractValidator, ContractRegistry,
    Permission, ResourceClassification, RiskLevel, AuthorizationStatus, PermissionManager,
    CapabilityDefinition, CapabilityRegistry, ToolDefinition, ToolRegistry,
    ResourceScope, ResourceManager, PolicySnapshot, EmergencyStopController,
    AuditRecord, AuditLogger, AuthorizationRequest, AuthorizationDecision, AuthorizationEngine,
    MutationRecord, MutationGuard
)

from .memory import (
    ContextMemoryAPI, MemoryRecord, MemoryType, MemoryScope, MemoryStatus, MemorySource,
    MemoryStore, ContextRelevanceEngine, ContextConflictDetector, ContextBuilder, ExecutionContext,
    ContextSnapshot, ContextSnapshotManager, MemoryConsolidator, MemoryGovernanceGuard
)

from .context import (
    GlobalContext, AssetContext, TaskContext, AgentContext, JobContext,
    ContextPriority, ConflictStatus, ContextPackage, ContextConflict, ContextSnapshot as CtxSnapshot,
    ContextPackager, ContextRecoveryService, ContextManager
)

from .knowledge_graph import (
    NodeType, GraphNode as KnowledgeGraphNode, RelationshipType, GraphEdge as KnowledgeGraphEdge, ProjectKnowledgeGraphStore,
    DuplicateSemanticIdentityError, GraphQueryEngine, GraphImpactAnalyzer, ImpactReport,
    GraphConsistencyValidator, GraphConsistencyReport, DependencyCycleDetectedError,
    GraphDiff, GraphDiffEngine, GraphSnapshotService, GraphSnapshotRecord,
    GraphProvenanceTracker, BlenderGraphExtractor, GraphGovernanceGuard,
    GraphPermissionDeniedError, ProjectKnowledgeGraphAPI
)

from .evaluation import (
    EvaluationDimension, DefectSeverity, DefectStatus, BenchmarkStatus, AcceptanceDecision,
    EvaluationDefect, DimensionScore, EvaluationProfile, EvaluationBenchmark,
    create_weapon_profile, create_unreal_ready_profile, create_visual_asset_profile, ProfileRegistry,
    DimensionEvaluator, ABComparisonEngine, ABComparisonResult, RegressionDetector as BenchmarkRegressionDetector, RegressionReport,
    EvaluationStore, BenchmarkCorruptedError, BenchmarkFinalizedImmutableError,
    EvaluationGovernanceGuard, EvaluationPermissionDeniedError, KnowledgeGraphEvaluationBridge,
    EvaluationBenchmarkAPI
)

from .golden import (
    GoldenAssetStatus, MutationType, RegressionLevel, GoldenAssetException,
    GoldenImmutabilityError, GoldenIntegrityError, GoldenDuplicateError, GoldenAuthorizationError,
    GoldenAsset, GoldenIdentityHelper, AssetFingerprinter, GeometryFingerprinter,
    MaterialFingerprinter, SceneFingerprinter, ReferenceFingerprinter, GoldenRegistry,
    VersionRegistry, GoldenStore, ManifestStore, IntegrityStore, GoldenComparator,
    GoldenComparisonResult, RegressionPolicy, CompatibilityChecker, ImmutabilityGuard,
    MutationDetector, AuthorizationGuard, EvaluationBridge as GoldenEvaluationBridge, KnowledgeGraphBridge,
    RecoveryBridge, GoldenAPI
)

from .diagnostics import (
    FailureStatus, FailureType, ResolutionStatus, FailureSeverity, FailureRecord,
    RootCause, DiagnosticReport, FailureCapture, ExceptionNormalizer, EventCollector,
    FailureClassifier, FailureSignature, CategoryRules, EvidenceItem, StateSnapshot,
    BlenderEvidenceCollector, EvidenceCollector, RootCauseAnalyzer, DependencyAnalyzer,
    ImpactAnalyzer, ConfidenceEngine, CorrectiveAction, CorrectionPlanner,
    CorrectionExecutor, CorrectionValidator, IncidentStore, FailureHistory,
    PatternDetector, GovernanceBridge, JobRecoveryBridge,
    EvaluationBridge as DiagnosticsEvaluationBridge, GoldenBridge,
    DiagnosticsKnowledgeGraphBridge, DiagnosticsAPI
)

from .failure_analysis import (
    FailureAnalysisAPI, FailureStore, FailureMemory, SolutionReuseEngine,
    FailureStatistics, RecoveryPlan, RecoveryPlanner, RetryStrategy,
    RegenerationStrategy, RollbackStrategy, InterventionPolicy,
    ExceptionDetector, BlenderFailureDetector, PipelineFailureDetector,
    ValidationFailureDetector, RegressionFailureDetector, FailureContext
)

from .strategy_learning import (
    StrategyRecord, StrategyStatus, StrategyOutcome, LearningEvent,
    StrategyOptimizationProfile, FinalStatus,
    ProblemFeatures, FeatureExtractor, ProblemSignature as StrategyProblemSignature, StrategySignature,
    StrategyHistory, OutcomeHistory, ExecutionHistory,
    StrategyAnalyzer, SuccessAnalyzer, FailureAnalyzer, CostAnalyzer, RegressionAnalyzer,
    CandidateScorer, ConfidenceEngine as StrategyConfidenceEngine,
    ExplorationPolicy, StrategyRanker,
    TradeoffOptimizer, ParameterOptimizer, ConstraintOptimizer, StrategyOptimizer,
    OutcomeLearner, PatternLearner, TransferLearning, LearningEngine as StrategyLearningEngine,
    LearningGuard, StrategyGuard, RegressionGuard,
    StrategyLearningStore, StrategyLearningAPI
)

from .cost_performance import (
    CostReport, CostMetric, MeasurementMethod,
    PerformanceReport, QualityFloor, OptimizationProfile as CostOptimizationProfile, ProfileType as CostProfileType,
    BudgetLimits, BudgetStatus,
    CostEvaluator, PerformanceEvaluator, ParetoAnalyzer, TradeoffAnalyzer, BudgetChecker,
    CandidateStrategy, CandidateStatus,
    GeometryOptimizer, MaterialOptimizer, TextureOptimizer, LODOptimizer, CollisionOptimizer,
    OptimizationPlan, PlanBuilder, LifecycleController, LifecycleStage,
    AuditRecord, CostPerformanceStore, CostPerformanceAPI
)

from .production_orchestration import (
    ProductionJob, JobStatus as ProductionJobStatus,
    PipelineStage, StageResult, StageStatus,
    ProductionPlan, ProductionStateMachine,
    ProductionPipeline, StageExecutor, BudgetEnforcer,
    VersionManager as ProductionVersionManager, CrashRecoveryManager, CancellationManager, AuditReporter,
    ProductionStore, ProductionOrchestratorAPI
)

from .learned_construction_patterns import ProblemSignature









