"""
UAF-81.83: Universal Runtime Networking, Entity Replication, State Synchronization & Multiplayer Engine.
"""

from .engine import (
    ClientNetworkEngine,
    DedicatedServerEngine,
    NetworkConnection,
    SimulatedNetworkTransport,
    SimulatedTransportRule,
    UniversalRuntimeNetworkingFabricator,
)
from .models import (
    AuthorityType,
    BandwidthBudget,
    BaselineInvalidatedError,
    ChannelType,
    ClientId,
    ConnectionId,
    ConnectionState,
    ConnectionStateError,
    DesyncError,
    DisconnectReason,
    DormancyState,
    EntitySnapshot,
    InputCommand,
    InterestProfile,
    InvalidAuthorityError,
    NetworkEntityId,
    NetworkError,
    NetworkMetrics,
    NetworkMode,
    NetworkPriority,
    NetworkSession,
    NetworkSnapshot,
    NumericSecurityError,
    OwnershipType,
    Packet,
    PacketHeader,
    PacketValidationError,
    RateLimitExceededError,
    ReplicatedComponent,
    ReplicatedProperty,
    ReplicationPolicy,
    RollbackError,
    RPCMessage,
    RPCType,
    SchemaVersionMismatchError,
    WorldSnapshot,
    ensure_finite_float,
    ensure_finite_vec3,
)
from .package import UniversalRuntimeNetworkingPackager
from .prediction import (
    ClientPredictor,
    HistoryBuffer,
    InputBuffer,
    LagCompensator,
    ReconciliationManager,
    ReconciliationResult,
    RollbackEngine,
    default_movement_simulation,
)
from .protocol import (
    AckManager,
    PacketSerializer,
    ReliableOrderedChannel,
    RPCDispatcher,
    UnreliableSequencedChannel,
    sequence_diff,
    sequence_greater_than,
    sequence_less_than,
)
from .replication import (
    BandwidthArbiter,
    ClientBaselineTracker,
    DeltaCompressor,
    DeltaSnapshot,
    DormancyManager,
    EntityDelta,
    PropertyContainer,
    SpatialRelevancyManager,
    quantize_value,
)
from .validation import (
    NetworkValidationIssue,
    UniversalRuntimeNetworkingValidator,
)

__all__ = [
    # Engine
    "ClientNetworkEngine",
    "DedicatedServerEngine",
    "NetworkConnection",
    "SimulatedNetworkTransport",
    "SimulatedTransportRule",
    "UniversalRuntimeNetworkingFabricator",
    # Models & Identifiers
    "AuthorityType",
    "BandwidthBudget",
    "BaselineInvalidatedError",
    "ChannelType",
    "ClientId",
    "ConnectionId",
    "ConnectionState",
    "ConnectionStateError",
    "DesyncError",
    "DisconnectReason",
    "DormancyState",
    "EntitySnapshot",
    "InputCommand",
    "InterestProfile",
    "InvalidAuthorityError",
    "NetworkEntityId",
    "NetworkError",
    "NetworkMetrics",
    "NetworkMode",
    "NetworkPriority",
    "NetworkSession",
    "NetworkSnapshot",
    "NumericSecurityError",
    "OwnershipType",
    "Packet",
    "PacketHeader",
    "PacketValidationError",
    "RateLimitExceededError",
    "ReplicatedComponent",
    "ReplicatedProperty",
    "ReplicationPolicy",
    "RollbackError",
    "RPCMessage",
    "RPCType",
    "SchemaVersionMismatchError",
    "WorldSnapshot",
    "ensure_finite_float",
    "ensure_finite_vec3",
    # Package
    "UniversalRuntimeNetworkingPackager",
    # Prediction
    "ClientPredictor",
    "HistoryBuffer",
    "InputBuffer",
    "LagCompensator",
    "ReconciliationManager",
    "ReconciliationResult",
    "RollbackEngine",
    "default_movement_simulation",
    # Protocol
    "AckManager",
    "PacketSerializer",
    "ReliableOrderedChannel",
    "RPCDispatcher",
    "UnreliableSequencedChannel",
    "sequence_diff",
    "sequence_greater_than",
    "sequence_less_than",
    # Replication
    "BandwidthArbiter",
    "ClientBaselineTracker",
    "DeltaCompressor",
    "DeltaSnapshot",
    "DormancyManager",
    "EntityDelta",
    "PropertyContainer",
    "SpatialRelevancyManager",
    "quantize_value",
    # Validation
    "NetworkValidationIssue",
    "UniversalRuntimeNetworkingValidator",
]
