"""
Universal Runtime Input Packager (UAF-81.77).
Generates C++ Subsystem wrappers and manifests for Unreal Engine 5 input pipeline.
"""

from __future__ import annotations
import hashlib
import json
import os
from typing import Any, Dict, Optional

from ..models.definition import InputWorld


class UniversalRuntimeInputPackager:
    """Packages runtime input definitions and generates Unreal Engine 5 C++ bindings."""

    def package(self, output_dir: str, world: Optional[InputWorld] = None) -> Dict[str, Any]:
        if world is None:
            world = InputWorld("UUAFRuntimeInputSubsystem")
        res = self.package_for_unreal(world, output_dir)
        res["success"] = True
        return res

    def package_for_unreal(self, world: InputWorld, output_dir: str) -> Dict[str, str]:
        os.makedirs(output_dir, exist_ok=True)
        results: Dict[str, str] = {}

        # 1. Generate Manifest
        manifest_data = {
            "module": "uaf_runtime_input",
            "version": "1.0.0",
            "world": world.to_dict(),
            "files": [
                "UUAFRuntimeInputSubsystem.h",
                "UUAFRuntimeInputSubsystem.cpp",
            ],
        }
        manifest_path = os.path.join(output_dir, "input_manifest.json")
        serialized_manifest = json.dumps(manifest_data, indent=2, sort_keys=True)
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(serialized_manifest)
        results["manifest"] = manifest_path

        # 2. Generate Signature
        sig_path = os.path.join(output_dir, "input_manifest.sig")
        sig_hash = hashlib.sha256(serialized_manifest.encode("utf-8")).hexdigest()
        with open(sig_path, "w", encoding="utf-8") as f:
            f.write(sig_hash)
        results["signature"] = sig_path

        # 3. Generate Header (.h)
        header_code = f"""// Generated by UAF-81.77 Universal Runtime Input Packager
// Safe for Unreal Engine 5.3+ Compilation

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/WorldSubsystem.h"
#include "UAFRuntimeInputSubsystem.generated.h"

UCLASS()
class ASSETORCHESTRATION_API UUAFRuntimeInputSubsystem : public UWorldSubsystem
{{
    GENERATED_BODY()

public:
    virtual void Initialize(FSubsystemCollectionBase& Collection) override;
    virtual void Deinitialize() override;

    UFUNCTION(BlueprintCallable, Category = "UAF|Input")
    bool IsActionTriggered(FString ActionId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Input")
    float GetAxisValue(FString AxisId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Input")
    void PushContext(FString ContextId);

    UFUNCTION(BlueprintCallable, Category = "UAF|Input")
    void PopContext(FString ContextId);

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Input")
    FString InputWorldId = TEXT("{world.input_world_id}");

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Input")
    int32 TotalDevices = {len(world.devices)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Input")
    int32 TotalActions = {len(world.actions)};

    UPROPERTY(BlueprintReadOnly, Category = "UAF|Input")
    int32 TotalAxes = {len(world.axes)};
}};
"""
        header_path = os.path.join(output_dir, "UUAFRuntimeInputSubsystem.h")
        with open(header_path, "w", encoding="utf-8") as f:
            f.write(header_code)
        results["header"] = header_path

        # 4. Generate Source (.cpp)
        cpp_code = f"""// Generated by UAF-81.77 Universal Runtime Input Packager

#include "UUAFRuntimeInputSubsystem.h"

void UUAFRuntimeInputSubsystem::Initialize(FSubsystemCollectionBase& Collection)
{{
    Super::Initialize(Collection);
    UE_LOG(LogTemp, Log, TEXT("UUAFRuntimeInputSubsystem initialized for InputWorld: %s"), *InputWorldId);
}}

void UUAFRuntimeInputSubsystem::Deinitialize()
{{
    UE_LOG(LogTemp, Log, TEXT("UUAFRuntimeInputSubsystem deinitialized for InputWorld: %s"), *InputWorldId);
    Super::Deinitialize();
}}

bool UUAFRuntimeInputSubsystem::IsActionTriggered(FString ActionId)
{{
    // Query action trigger status
    return false;
}}

float UUAFRuntimeInputSubsystem::GetAxisValue(FString AxisId)
{{
    // Query normalized axis value
    return 0.0f;
}}

void UUAFRuntimeInputSubsystem::PushContext(FString ContextId)
{{
    // Push context to active stack
}}

void UUAFRuntimeInputSubsystem::PopContext(FString ContextId)
{{
    // Pop context from stack
}}
"""
        cpp_path = os.path.join(output_dir, "UUAFRuntimeInputSubsystem.cpp")
        with open(cpp_path, "w", encoding="utf-8") as f:
            f.write(cpp_code)
        results["source"] = cpp_path

        return results
