from enum import Enum

class AssetCategoryTag(str, Enum):
    PROP = "PROP"
    WEAPON = "WEAPON"
    ARCHITECTURE = "ARCHITECTURE"
    VEHICLE = "VEHICLE"
    ENVIRONMENT = "ENVIRONMENT"
    CHARACTER = "CHARACTER"
    CREATURE = "CREATURE"
    FURNITURE = "FURNITURE"
    MACHINE = "MACHINE"
    MODULAR_KIT = "MODULAR_KIT"
    DECORATION = "DECORATION"
    ORGANIC = "ORGANIC"
    HARD_SURFACE = "HARD_SURFACE"
    HYBRID = "HYBRID"
    OTHER = "OTHER"

class ComponentConstructionMethod(str, Enum):
    PRIMITIVE = "PRIMITIVE"
    PARAMETRIC = "PARAMETRIC"
    PROCEDURAL = "PROCEDURAL"
    MODULAR = "MODULAR"
    KIT_BASED = "KIT_BASED"
    CURVE_BASED = "CURVE_BASED"
    BOOLEAN_BASED = "BOOLEAN_BASED"
    PROFILE_BASED = "PROFILE_BASED"
    ARRAY_BASED = "ARRAY_BASED"
    GEOMETRY_NODES = "GEOMETRY_NODES"
    SCULPT_REQUIRED = "SCULPT_REQUIRED"
    HAND_AUTHORED = "HAND_AUTHORED"
    REUSED = "REUSED"
    HYBRID = "HYBRID"

class BasePrimitiveType(str, Enum):
    CUBE = "CUBE"
    CYLINDER = "CYLINDER"
    SPHERE = "SPHERE"
    CONE = "CONE"
    TORUS = "TORUS"
    PLANE = "PLANE"
    CURVE = "CURVE"
    PROFILE = "PROFILE"
    CUSTOM_MESH = "CUSTOM_MESH"

class GeometricOperationType(str, Enum):
    CREATE = "CREATE"
    SCALE = "SCALE"
    ROTATE = "ROTATE"
    TRANSLATE = "TRANSLATE"
    EXTRUDE = "EXTRUDE"
    INSET = "INSET"
    BEVEL = "BEVEL"
    BOOLEAN = "BOOLEAN"
    LOOP_CUT = "LOOP_CUT"
    SUBDIVIDE = "SUBDIVIDE"
    MIRROR = "MIRROR"
    ARRAY = "ARRAY"
    SOLIDIFY = "SOLIDIFY"
    CURVE_DEFORM = "CURVE_DEFORM"
    SHRINKWRAP = "SHRINKWRAP"
    REMESH = "REMESH"
    DECIMATE = "DECIMATE"
    WELD = "WELD"
    SEPARATE = "SEPARATE"
    JOIN = "JOIN"

class SymmetryType(str, Enum):
    MIRROR = "MIRROR"
    RADIAL = "RADIAL"
    BILATERAL = "BILATERAL"
    NONE = "NONE"

class DetailLevel(str, Enum):
    PRIMARY_FORM = "PRIMARY_FORM"
    SECONDARY_FORM = "SECONDARY_FORM"
    TERTIARY_DETAIL = "TERTIARY_DETAIL"
    MICRO_DETAIL = "MICRO_DETAIL"

class CollisionStrategyType(str, Enum):
    NONE = "NONE"
    AUTO = "AUTO"
    PRIMITIVE = "PRIMITIVE"
    CUSTOM_UCX = "CUSTOM_UCX"
    HYBRID = "HYBRID"

class PivotStrategyType(str, Enum):
    CENTER = "CENTER"
    BASE_CENTER_GROUNDED = "BASE_CENTER_GROUNDED"
    FUNCTIONAL_HINGE = "FUNCTIONAL_HINGE"
    WORLD_ALIGNED = "WORLD_ALIGNED"
    CUSTOM = "CUSTOM"

class StrategyRiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ReuseStrategyType(str, Enum):
    REUSE_EXISTING = "REUSE_EXISTING"
    CREATE_VARIANT = "CREATE_VARIANT"
    CREATE_NEW = "CREATE_NEW"
